<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>NewAreaBoundaryConditions Method (Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</title><meta name="Language" content="en-us" /><meta name="Description" content="Creates a new Area BoundaryConditions element on a reference." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.Creation" /><meta name="file" content="070c2d73-9a6d-3840-b149-b82bb87d4ed3" /><meta name="guid" content="070c2d73-9a6d-3840-b149-b82bb87d4ed3" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)" />
<meta name="Microsoft.Help.TocParent" content="Overload:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)" /><MSHelp:TOCTitle Title="NewAreaBoundaryConditions Method (Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)" /><MSHelp:RLTitle Title="Document.NewAreaBoundaryConditions Method (Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double) (Autodesk.Revit.Creation)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Creates a new Area BoundaryConditions element on a reference." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><link type="text/css" rel="stylesheet" href="styles/highlight.css" /><script type="text/javascript" src="scripts/highlight.js"> </script>
<script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">Document<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>NewAreaBoundaryConditions Method (Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Document">Document Class</a> <a href="#exampleToggle" onclick="OpenSection(exampleToggle)">Example</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary"> Creates a new Area BoundaryConditions element on a reference. </div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.Creation">Autodesk.Revit.Creation</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.BoundaryConditions">BoundaryConditions</a> <span class="identifier">NewAreaBoundaryConditions</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a> <span class="parameter">reference</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">X_Translation</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">X_TranslationSpringModulus</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">Y_Translation</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">Y_TranslationSpringModulus</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">Z_Translation</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">Z_TranslationSpringModulus</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">NewAreaBoundaryConditions</span> ( _
	<span class="parameter">reference</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a>, _
	<span class="parameter">X_Translation</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a>, _
	<span class="parameter">X_TranslationSpringModulus</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">Y_Translation</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a>, _
	<span class="parameter">Y_TranslationSpringModulus</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">Z_Translation</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a>, _
	<span class="parameter">Z_TranslationSpringModulus</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a> _
) <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.BoundaryConditions">BoundaryConditions</a></pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.BoundaryConditions">BoundaryConditions</a>^ <span class="identifier">NewAreaBoundaryConditions</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a>^ <span class="parameter">reference</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">X_Translation</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">X_TranslationSpringModulus</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">Y_Translation</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">Y_TranslationSpringModulus</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">TranslationRotationValue</a> <span class="parameter">Z_Translation</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">Z_TranslationSpringModulus</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="reference"><dt><span class="parameter">reference</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Reference</a><br /> The Geometry reference obtained from a Wall, Slab or 
Slab Foundation. </dd></dl><dl paramname="X_Translation"><dt><span class="parameter">X_Translation</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>TranslationRotationValue</a><br /> A value indicating the X axis translation option. </dd></dl><dl paramname="X_TranslationSpringModulus"><dt><span class="parameter">X_TranslationSpringModulus</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br /> Translation Spring Modulus for X axis. Ignored if X_Translation is not "Spring". </dd></dl><dl paramname="Y_Translation"><dt><span class="parameter">Y_Translation</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>TranslationRotationValue</a><br /> A value indicating the Y axis translation option. </dd></dl><dl paramname="Y_TranslationSpringModulus"><dt><span class="parameter">Y_TranslationSpringModulus</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br /> Translation Spring Modulus for Y axis. Ignored if Y_Translation is not "Spring". </dd></dl><dl paramname="Z_Translation"><dt><span class="parameter">Z_Translation</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.TranslationRotationValue">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>TranslationRotationValue</a><br /> A value indicating the Z axis translation option. </dd></dl><dl paramname="Z_TranslationSpringModulus"><dt><span class="parameter">Z_TranslationSpringModulus</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br /> Translation Spring Modulus for Z axis. Ignored if Z_Translation is not "Spring". </dd></dl></div><h4 class="subHeading">Return Value</h4>If successful, NewAreaBoundaryConditions returns an object for the newly created BoundaryConditions
with the BoundaryType = 2 - "Area". <span class="keyword"><span class="languageSpecificText"><span class="cs">null</span><span class="vb">Nothing</span><span class="cpp">nullptr</span></span></span><span class="nu">a null reference (<span class="keyword">Nothing</span> in Visual Basic)</span> is returned if the operation fails.</div><h1 class="heading"><span onclick="ExpandCollapse(remarksToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(remarksToggle, event)" tabindex="0"><img id="remarksToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Remarks</span></h1><div id="remarksSection" class="section" name="collapseableSection" style="">This method will only function with the Autodesk Revit Structure application.</div><h1 class="heading"><span onclick="ExpandCollapse(exampleToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exampleToggle, event)" tabindex="0"><img id="exampleToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Examples</span></h1><div id="exampleSection" class="section" name="collapseableSection" style=""><span id="cbc_1" x-lang="CSharp" codelanguage="CSharp"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>C#</div><div class="code"><pre xml:space="preserve"> <span class="highlight-keyword">bool</span> CreateAreaConditionWithReference(Wall wall, Autodesk.Revit.Creation.Document docCreation)
 {
     <span class="highlight-comment">// Get the Geometry reference to the wall</span>
     Reference profileReference = <span class="highlight-keyword">null</span>;
     AnalyticalModel analytical = wall.GetAnalyticalModel() <span class="highlight-keyword">as</span> AnalyticalModel;
     <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> == analytical)
     {
         <span class="highlight-keyword">return</span> <span class="highlight-keyword">false</span>; <span class="highlight-comment">// the profile reference can't be retrieved.</span>
     }

     <span class="highlight-comment">// loop through the curves of the wall and get the first one as a reference</span>
     <span class="highlight-keyword">foreach</span> (Curve curve <span class="highlight-keyword">in</span> analytical.GetCurves(AnalyticalCurveType.ActiveCurves))
     {
         profileReference = curve.Reference;
         <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> != profileReference)
         {
             <span class="highlight-keyword">break</span>;
         }
     }

     BoundaryConditions condition = <span class="highlight-keyword">null</span>;
     <span class="highlight-comment">// Create the Area Boundary Conditions if we have a profileReference</span>
     <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> != profileReference)
     {
         <span class="highlight-comment">// Create Area Boundary Conditions with profile reference.</span>
         condition = docCreation.NewAreaBoundaryConditions(profileReference, TranslationRotationValue.Fixed, <span class="highlight-number">0</span>,
                                                                             TranslationRotationValue.Fixed, <span class="highlight-number">0</span>,
                                                                             TranslationRotationValue.Fixed, <span class="highlight-number">0</span>);
     }
     <span class="highlight-keyword">return</span> (<span class="highlight-keyword">null</span> != condition);
}</pre></div></span><span id="cbc_2" x-lang="VisualBasic" codelanguage="VisualBasic"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>VB.NET</div><div class="code"><pre xml:space="preserve"><span class="highlight-keyword">Private</span> <span class="highlight-keyword">Function</span> CreateAreaConditionWithReference(wall <span class="highlight-keyword">As</span> Wall, docCreation <span class="highlight-keyword">As</span> Autodesk.Revit.Creation.Document) <span class="highlight-keyword">As</span> <span class="highlight-keyword">Boolean</span>
    <span class="highlight-comment">' Get the Geometry reference to the wall</span>
    <span class="highlight-keyword">Dim</span> profileReference <span class="highlight-keyword">As</span> Reference = <span class="highlight-keyword">Nothing</span>
    <span class="highlight-keyword">Dim</span> analytical <span class="highlight-keyword">As</span> AnalyticalModel = <span class="highlight-keyword">TryCast</span>(wall.GetAnalyticalModel(), AnalyticalModel)
    <span class="highlight-keyword">If</span> analytical <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-comment">' the profile reference can't be retrieved.</span>
        <span class="highlight-keyword">Return</span> <span class="highlight-keyword">False</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' loop through the curves of the wall and get the first one as a reference</span>
    <span class="highlight-keyword">For</span> <span class="highlight-keyword">Each</span> curve <span class="highlight-keyword">As</span> Curve <span class="highlight-keyword">In</span> analytical.GetCurves(AnalyticalCurveType.ActiveCurves)
        profileReference = curve.Reference
        <span class="highlight-keyword">If</span> profileReference <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
            <span class="highlight-keyword">Exit</span> <span class="highlight-keyword">For</span>
        <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Next</span>

    <span class="highlight-keyword">Dim</span> condition <span class="highlight-keyword">As</span> BoundaryConditions = <span class="highlight-keyword">Nothing</span>
    <span class="highlight-comment">' Create the Area Boundary Conditions if we have a profileReference</span>
    <span class="highlight-keyword">If</span> profileReference <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-comment">' Create Area Boundary Conditions with profile reference.</span>
        condition = docCreation.NewAreaBoundaryConditions(profileReference, TranslationRotationValue.Fixed, <span class="highlight-number">0</span>, TranslationRotationValue.Fixed, <span class="highlight-number">0</span>, TranslationRotationValue.Fixed, _
            <span class="highlight-number">0</span>)
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> (condition <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span>)
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span></pre></div></span></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Document">Document Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=Overload:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions">NewAreaBoundaryConditions Overload</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.Creation">Autodesk.Revit.Creation Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>