<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>SetFromCurvesAndShape Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="SetFromCurvesAndShape method" /><meta name="System.Keywords" content="RebarContainerItem.SetFromCurvesAndShape method" /><meta name="Description" content="Set an instance of a RebarContainerItem element according to the parameters list. The instance will have the default shape parameters from the RebarShape." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB.Structure" /><meta name="file" content="1bf70fa9-9647-e168-c1bb-78bcdd7ba851" /><meta name="guid" content="1bf70fa9-9647-e168-c1bb-78bcdd7ba851" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape(Autodesk.Revit.DB.Structure.RebarShape,Autodesk.Revit.DB.Structure.RebarBarType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.XYZ,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},Autodesk.Revit.DB.Structure.RebarHookOrientation,Autodesk.Revit.DB.Structure.RebarHookOrientation)" />
<meta name="Microsoft.Help.TocParent" content="Methods.T:Autodesk.Revit.DB.Structure.RebarContainerItem" />
<meta name="Microsoft.Help.TocOrder" content="19" />
<meta name="Microsoft.Help.Keywords" content="RebarContainerItem.SetFromCurvesAndShape method" />
<meta name="Microsoft.Help.Keywords" content="SetFromCurvesAndShape method" />
<meta name="Microsoft.Help.Keywords" content="SetFromCurvesAndShape method" />
<meta name="Microsoft.Help.Keywords" content="RebarContainerItem.SetFromCurvesAndShape method" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape(Autodesk.Revit.DB.Structure.RebarShape,Autodesk.Revit.DB.Structure.RebarBarType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.XYZ,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},Autodesk.Revit.DB.Structure.RebarHookOrientation,Autodesk.Revit.DB.Structure.RebarHookOrientation)" /><MSHelp:TOCTitle Title="SetFromCurvesAndShape Method " /><MSHelp:RLTitle Title="RebarContainerItem.SetFromCurvesAndShape Method  (Autodesk.Revit.DB.Structure)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape(Autodesk.Revit.DB.Structure.RebarShape,Autodesk.Revit.DB.Structure.RebarBarType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.Structure.RebarHookType,Autodesk.Revit.DB.XYZ,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},Autodesk.Revit.DB.Structure.RebarHookOrientation,Autodesk.Revit.DB.Structure.RebarHookOrientation)" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBStructureRebarContainerItemClassSetFromCurvesAndShapeTopic" /><MSHelp:Keyword Index="K" Term="SetFromCurvesAndShape method" /><MSHelp:Keyword Index="K" Term="RebarContainerItem.SetFromCurvesAndShape method" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.Structure.RebarContainerItem.SetFromCurvesAndShape" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Set an instance of a RebarContainerItem element according to the parameters list. The instance will have the default shape parameters from the RebarShape. If the RebarShapeDefinesHooks flag in ReinforcementSettings has been set to true, ..." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">RebarContainerItem<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>SetFromCurvesAndShape Method </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarContainerItem">RebarContainerItem Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">
   Set an instance of a RebarContainerItem element according to the parameters list.
   The instance will have the default shape parameters from the RebarShape.
   If the RebarShapeDefinesHooks flag in ReinforcementSettings has been set to true,
   then both the curves and hooks must match the RebarShape definition.
   Otherwise, the hooks can be different than the defaults specified in the RebarShape
</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Structure">Autodesk.Revit.DB.Structure</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<br /><b>Since:</b> 
   2016
<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">void</span> <span class="identifier">SetFromCurvesAndShape</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShape">RebarShape</a> <span class="parameter">rebarShape</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarBarType">RebarBarType</a> <span class="parameter">barType</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a> <span class="parameter">startHook</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a> <span class="parameter">endHook</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> <span class="parameter">norm</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>&gt; <span class="parameter">curves</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a> <span class="parameter">startHookOrient</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a> <span class="parameter">endHookOrient</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Sub</span> <span class="identifier">SetFromCurvesAndShape</span> ( _
	<span class="parameter">rebarShape</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShape">RebarShape</a>, _
	<span class="parameter">barType</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarBarType">RebarBarType</a>, _
	<span class="parameter">startHook</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a>, _
	<span class="parameter">endHook</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a>, _
	<span class="parameter">norm</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>, _
	<span class="parameter">curves</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>(<span class="keyword">Of</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>), _
	<span class="parameter">startHookOrient</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a>, _
	<span class="parameter">endHookOrient</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a> _
)</pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<span class="keyword">void</span> <span class="identifier">SetFromCurvesAndShape</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShape">RebarShape</a>^ <span class="parameter">rebarShape</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarBarType">RebarBarType</a>^ <span class="parameter">barType</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a>^ <span class="parameter">startHook</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">RebarHookType</a>^ <span class="parameter">endHook</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">norm</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>^&gt;^ <span class="parameter">curves</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a> <span class="parameter">startHookOrient</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">RebarHookOrientation</a> <span class="parameter">endHookOrient</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="rebarShape"><dt><span class="parameter">rebarShape</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShape">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarShape</a><br />
   A RebarShape element that defines the shape of the rebar.
   A RebarShape element matches curves and hooks.
   A RebarShape element provides RebarStyle of the rebar.
</dd></dl><dl paramname="barType"><dt><span class="parameter">barType</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarBarType">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarBarType</a><br />
   A RebarBarType element that defines bar diameter, bend radius and material of the rebar.
</dd></dl><dl paramname="startHook"><dt><span class="parameter">startHook</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarHookType</a><br />
   A RebarHookType element that defines the hook for the start of the bar.
   If this parameter is <span class="keyword"><span class="languageSpecificText"><span class="cs">null</span><span class="vb">Nothing</span><span class="cpp">nullptr</span></span></span><span class="nu">a null reference (<span class="keyword">Nothing</span> in Visual Basic)</span>, it means to create a rebar with no hook.
</dd></dl><dl paramname="endHook"><dt><span class="parameter">endHook</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookType">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarHookType</a><br />
   A RebarHookType element that defines the hook for the end of the bar.
   If this parameter is <span class="keyword"><span class="languageSpecificText"><span class="cs">null</span><span class="vb">Nothing</span><span class="cpp">nullptr</span></span></span><span class="nu">a null reference (<span class="keyword">Nothing</span> in Visual Basic)</span>, it means to create a rebar with no hook.
</dd></dl><dl paramname="norm"><dt><span class="parameter">norm</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>XYZ</a><br />
   The normal to the plane that the rebar curves lie on.
</dd></dl><dl paramname="curves"><dt><span class="parameter">curves</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">System.Collections.Generic<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>IList</a><span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="nu">(</span><span class="fs">&lt;'</span></span><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a><span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="nu">)</span><span class="fs">&gt;</span></span><br />
   An array of curves that define the shape of the rebar curves.
   They must belong to the plane defined by the normal and origin.
   Bends and hooks should not be included in the array of curves.
</dd></dl><dl paramname="startHookOrient"><dt><span class="parameter">startHookOrient</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarHookOrientation</a><br />
   Defines the orientation of the hook plane at the start of the rebar with respect to the orientation of the first curve and the plane normal.
   Only two values are permitted:
   Value = Right: The hook is on your right as you stand at the end of the bar,
   with the bar behind you, taking the bar's normal as "up."
   Value = Left: The hook is on your left as you stand at the end of the bar,
   with the bar behind you, taking the bar's normal as "up."
</dd></dl><dl paramname="endHookOrient"><dt><span class="parameter">endHookOrient</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarHookOrientation">Autodesk.Revit.DB.Structure<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarHookOrientation</a><br />
   Defines the orientation of the hook plane at the end of the rebar with respect to the orientation of the last curve and the plane normal.
   Only two values are permitted:
   Value = Right: The hook is on your right as you stand at the end of the bar,
   with the bar behind you, taking the bar's normal as "up."
   Value = Left: The hook is on your left as you stand at the end of the bar,
   with the bar behind you, taking the bar's normal as "up."
</dd></dl></div></div><h1 class="heading"><span onclick="ExpandCollapse(exceptionsToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exceptionsToggle, event)" tabindex="0"><img id="exceptionsToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Exceptions</span></h1><div id="exceptionsSection" class="section" name="collapseableSection" style=""><div class="tableSection"><table width="100%" cellspacing="2" cellpadding="5" frame="lhs"><tr><th class="exceptionNameColumn">Exception</th><th class="exceptionConditionColumn">Condition</th></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentException</a></td><td>
   The input curves is empty.
   -or-
   The input curves contains at least one curve which is not a bound Line or bound Arc
   and is not supported for this operation.
   -or-
   curves do not form a valid CurveLoop.
   -or-
   The input curves contains at least one helical curve and is not supported for this operation.
   -or-
   The rebarShape has End Treatments
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentNullException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentNullException</a></td><td>
   A non-optional argument was NULL
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentOutOfRangeException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentOutOfRangeException</a></td><td>
   norm has zero length.
   -or-
   A value passed for an enumeration argument is not a member of that enumeration
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentsInconsistentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentsInconsistentException</a></td><td>
   curves contains non-fillet arcs with radii that are less than the
   minimum bend radius for the RebarBarType and RebarShape style.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.DisabledDisciplineException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>DisabledDisciplineException</a></td><td>
   None of the following disciplines is enabled: Structural.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.InvalidOperationException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>InvalidOperationException</a></td><td>
   rebarShape does not match curves.
</td></tr></table></div></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarContainerItem">RebarContainerItem Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Structure">Autodesk.Revit.DB.Structure Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>