<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>Create Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Create method" /><meta name="System.Keywords" content="IndependentTag.Create method" /><meta name="Description" content="Places a tag on an element or subelement." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="1f622654-786a-b8fd-1f81-278698bacd5b" /><meta name="guid" content="1f622654-786a-b8fd-1f81-278698bacd5b" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.DB.IndependentTag.Create(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Reference,System.Boolean,Autodesk.Revit.DB.TagMode,Autodesk.Revit.DB.TagOrientation,Autodesk.Revit.DB.XYZ)" />
<meta name="Microsoft.Help.TocParent" content="Methods.T:Autodesk.Revit.DB.IndependentTag" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="Create method" />
<meta name="Microsoft.Help.Keywords" content="IndependentTag.Create method" />
<meta name="Microsoft.Help.Keywords" content="Create method" />
<meta name="Microsoft.Help.Keywords" content="IndependentTag.Create method" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.IndependentTag.Create" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.IndependentTag.Create" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.DB.IndependentTag.Create(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Reference,System.Boolean,Autodesk.Revit.DB.TagMode,Autodesk.Revit.DB.TagOrientation,Autodesk.Revit.DB.XYZ)" /><MSHelp:TOCTitle Title="Create Method " /><MSHelp:RLTitle Title="IndependentTag.Create Method  (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.DB.IndependentTag.Create(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Reference,System.Boolean,Autodesk.Revit.DB.TagMode,Autodesk.Revit.DB.TagOrientation,Autodesk.Revit.DB.XYZ)" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBIndependentTagClassCreateTopic" /><MSHelp:Keyword Index="K" Term="Create method" /><MSHelp:Keyword Index="K" Term="IndependentTag.Create method" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.IndependentTag.Create" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.IndependentTag.Create" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Places a tag on an element or subelement." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><link type="text/css" rel="stylesheet" href="styles/highlight.css" /><script type="text/javascript" src="scripts/highlight.js"> </script>
<script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">IndependentTag<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Create Method </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.IndependentTag">IndependentTag Class</a> <a href="#exampleToggle" onclick="OpenSection(exampleToggle)">Example</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">
   Places a tag on an element or subelement.
</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<br /><b>Since:</b> 
   2018
<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.IndependentTag">IndependentTag</a> <span class="identifier">Create</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a> <span class="parameter">document</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a> <span class="parameter">ownerDBViewId</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a> <span class="parameter">referenceToTag</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">bool</a> <span class="parameter">addLeader</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagMode">TagMode</a> <span class="parameter">tagMode</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagOrientation">TagOrientation</a> <span class="parameter">tagOrientation</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> <span class="parameter">pnt</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">Create</span> ( _
	<span class="parameter">document</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>, _
	<span class="parameter">ownerDBViewId</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>, _
	<span class="parameter">referenceToTag</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a>, _
	<span class="parameter">addLeader</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">Boolean</a>, _
	<span class="parameter">tagMode</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagMode">TagMode</a>, _
	<span class="parameter">tagOrientation</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagOrientation">TagOrientation</a>, _
	<span class="parameter">pnt</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> _
) <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.IndependentTag">IndependentTag</a></pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.IndependentTag">IndependentTag</a>^ <span class="identifier">Create</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>^ <span class="parameter">document</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>^ <span class="parameter">ownerDBViewId</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Reference</a>^ <span class="parameter">referenceToTag</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">bool</a> <span class="parameter">addLeader</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagMode">TagMode</a> <span class="parameter">tagMode</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagOrientation">TagOrientation</a> <span class="parameter">tagOrientation</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">pnt</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="document"><dt><span class="parameter">document</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Document</a><br />
   The document to which the tag will be added.
</dd></dl><dl paramname="ownerDBViewId"><dt><span class="parameter">ownerDBViewId</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ElementId</a><br />
   The view in which the tag will be visible.
</dd></dl><dl paramname="referenceToTag"><dt><span class="parameter">referenceToTag</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Reference">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Reference</a><br />
   The host reference of the tag. The reference can be to an element or subelement in a local or linked document.
</dd></dl><dl paramname="addLeader"><dt><span class="parameter">addLeader</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Boolean</a><br />
   When true, the tag will be created with a straight leader with an attached end.
</dd></dl><dl paramname="tagMode"><dt><span class="parameter">tagMode</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagMode">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>TagMode</a><br />
   This argument determines the type of tag that will be created. Tag by category, multi-category tag, and material tag are allowed.
</dd></dl><dl paramname="tagOrientation"><dt><span class="parameter">tagOrientation</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.TagOrientation">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>TagOrientation</a><br />
   The orientation of the tag's head.
</dd></dl><dl paramname="pnt"><dt><span class="parameter">pnt</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>XYZ</a><br />
   For tags without leaders, this point is the position of the tag head.
   For tags with leaders, this point is the end point of the leader, and a leader of default length will be created from this point to the tag head.
</dd></dl></div><h4 class="subHeading">Return Value</h4>
   If successful the new tag is returned.
</div><h1 class="heading"><span onclick="ExpandCollapse(remarksToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(remarksToggle, event)" tabindex="0"><img id="remarksToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Remarks</span></h1><div id="remarksSection" class="section" name="collapseableSection" style="">
   Single category tags, multi-category tags and material tags can be placed.
</div><h1 class="heading"><span onclick="ExpandCollapse(exampleToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exampleToggle, event)" tabindex="0"><img id="exampleToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Examples</span></h1><div id="exampleSection" class="section" name="collapseableSection" style=""><span id="cbc_1" x-lang="CSharp" codelanguage="CSharp"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>C#</div><div class="code"><pre xml:space="preserve"><span class="highlight-keyword">private</span> IndependentTag CreateIndependentTag(Autodesk.Revit.DB.Document document, Wall wall)
{
    <span class="highlight-comment">// make sure active view is not a 3D view</span>
    Autodesk.Revit.DB.View view = document.ActiveView;

    <span class="highlight-comment">// define tag mode and tag orientation for new tag</span>
    TagMode tagMode = TagMode.TM_ADDBY_CATEGORY;
    TagOrientation tagorn = TagOrientation.Horizontal;

    <span class="highlight-comment">// Add the tag to the middle of the wall</span>
    LocationCurve wallLoc = wall.Location <span class="highlight-keyword">as</span> LocationCurve;
    XYZ wallStart = wallLoc.Curve.GetEndPoint(<span class="highlight-number">0</span>);
    XYZ wallEnd = wallLoc.Curve.GetEndPoint(<span class="highlight-number">1</span>);
    XYZ wallMid = wallLoc.Curve.Evaluate(<span class="highlight-number">0.5</span>, <span class="highlight-keyword">true</span>);
    Reference wallRef = <span class="highlight-keyword">new</span> Reference(wall);

    IndependentTag newTag = IndependentTag.Create(document, view.Id,  wallRef, <span class="highlight-keyword">true</span>, tagMode, tagorn, wallMid);
    <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> == newTag)
    {
        <span class="highlight-keyword">throw</span> <span class="highlight-keyword">new</span> Exception(<span class="highlight-literal">"Create IndependentTag Failed."</span>);
    }

    <span class="highlight-comment">// newTag.TagText is read-only, so we change the Type Mark type parameter to </span>
    <span class="highlight-comment">// set the tag text.  The label parameter for the tag family determines</span>
    <span class="highlight-comment">// what type parameter is used for the tag text.</span>

    WallType type = wall.WallType;

    Parameter foundParameter = type.LookupParameter(<span class="highlight-literal">"Type Mark"</span>);
    <span class="highlight-keyword">bool</span> result = foundParameter.Set(<span class="highlight-literal">"Hello"</span>);

    <span class="highlight-comment">// set leader mode free</span>
    <span class="highlight-comment">// otherwise leader end point move with elbow point</span>

    newTag.LeaderEndCondition = LeaderEndCondition.Free;
    XYZ elbowPnt = wallMid + <span class="highlight-keyword">new</span> XYZ(<span class="highlight-number">5.0</span>, <span class="highlight-number">5.0</span>, <span class="highlight-number">0.0</span>);
    newTag.LeaderElbow = elbowPnt;
    XYZ headerPnt = wallMid + <span class="highlight-keyword">new</span> XYZ(<span class="highlight-number">10.0</span>, <span class="highlight-number">10.0</span>, <span class="highlight-number">0.0</span>);
    newTag.TagHeadPosition = headerPnt;

    <span class="highlight-keyword">return</span> newTag;
}</pre></div></span><span id="cbc_2" x-lang="VisualBasic" codelanguage="VisualBasic"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>VB.NET</div><div class="code"><pre xml:space="preserve"><span class="highlight-keyword">Private</span> <span class="highlight-keyword">Function</span> CreateIndependentTag(document <span class="highlight-keyword">As</span> Autodesk.Revit.DB.Document, wall <span class="highlight-keyword">As</span> Wall) <span class="highlight-keyword">As</span> IndependentTag
      <span class="highlight-comment">' make sure active view is not a 3D view</span>
      <span class="highlight-keyword">Dim</span> view <span class="highlight-keyword">As</span> Autodesk.Revit.DB.View = document.ActiveView

      <span class="highlight-comment">' define tag mode and tag orientation for new tag</span>
      <span class="highlight-keyword">Dim</span> tagMode__1 <span class="highlight-keyword">As</span> TagMode = TagMode.TM_ADDBY_CATEGORY
      <span class="highlight-keyword">Dim</span> tagorn <span class="highlight-keyword">As</span> TagOrientation = TagOrientation.Horizontal

      <span class="highlight-comment">' Add the tag to the middle of the wall</span>
      <span class="highlight-keyword">Dim</span> wallLoc <span class="highlight-keyword">As</span> LocationCurve = <span class="highlight-keyword">TryCast</span>(wall.Location, LocationCurve)
      <span class="highlight-keyword">Dim</span> wallStart <span class="highlight-keyword">As</span> XYZ = wallLoc.Curve.GetEndPoint(<span class="highlight-number">0</span>)
      <span class="highlight-keyword">Dim</span> wallEnd <span class="highlight-keyword">As</span> XYZ = wallLoc.Curve.GetEndPoint(<span class="highlight-number">1</span>)
      <span class="highlight-keyword">Dim</span> wallMid <span class="highlight-keyword">As</span> XYZ = wallLoc.Curve.Evaluate(<span class="highlight-number">0.5</span>, <span class="highlight-keyword">True</span>)
   <span class="highlight-keyword">Dim</span> WallRef <span class="highlight-keyword">As</span> Reference = <span class="highlight-keyword">New</span> Reference(wall)

   <span class="highlight-keyword">Dim</span> newTag <span class="highlight-keyword">As</span> IndependentTag = IndependentTag.Create(document, view.Id, wallRef, <span class="highlight-keyword">True</span>, tagMode__1, tagorn, wallMid)
      <span class="highlight-keyword">If</span> newTag <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
          <span class="highlight-keyword">Throw</span> <span class="highlight-keyword">New</span> Exception(<span class="highlight-literal">"Create IndependentTag Failed."</span>)
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

      <span class="highlight-comment">' newTag.TagText is read-only, so we change the Type Mark type parameter to </span>
      <span class="highlight-comment">' set the tag text.  The label parameter for the tag family determines</span>
      <span class="highlight-comment">' what type parameter is used for the tag text.</span>


      <span class="highlight-keyword">Dim</span> type <span class="highlight-keyword">As</span> WallType = wall.WallType

      <span class="highlight-keyword">Dim</span> foundParameter <span class="highlight-keyword">As</span> Parameter = type.LookupParameter(<span class="highlight-literal">"Type Mark"</span>)
      <span class="highlight-keyword">Dim</span> result <span class="highlight-keyword">As</span> <span class="highlight-keyword">Boolean</span> = foundParameter.[<span class="highlight-keyword">Set</span>](<span class="highlight-literal">"Hello"</span>)

      <span class="highlight-comment">' set leader mode free</span>
      <span class="highlight-comment">' otherwise leader end point move with elbow point</span>


      newTag.LeaderEndCondition = LeaderEndCondition.Free
      <span class="highlight-keyword">Dim</span> elbowPnt <span class="highlight-keyword">As</span> XYZ = wallMid + <span class="highlight-keyword">New</span> XYZ(<span class="highlight-number">5.0</span>, <span class="highlight-number">5.0</span>, <span class="highlight-number">0.0</span>)
      newTag.LeaderElbow = elbowPnt
      <span class="highlight-keyword">Dim</span> headerPnt <span class="highlight-keyword">As</span> XYZ = wallMid + <span class="highlight-keyword">New</span> XYZ(<span class="highlight-number">10.0</span>, <span class="highlight-number">10.0</span>, <span class="highlight-number">0.0</span>)
      newTag.TagHeadPosition = headerPnt

      <span class="highlight-keyword">Return</span> newTag
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span></pre></div></span></div><h1 class="heading"><span onclick="ExpandCollapse(exceptionsToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exceptionsToggle, event)" tabindex="0"><img id="exceptionsToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Exceptions</span></h1><div id="exceptionsSection" class="section" name="collapseableSection" style=""><div class="tableSection"><table width="100%" cellspacing="2" cellpadding="5" frame="lhs"><tr><th class="exceptionNameColumn">Exception</th><th class="exceptionConditionColumn">Condition</th></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentException</a></td><td>
   The ElementId ownerDBViewId does not correspond to a View.
   -or-
   The ElementId ownerDBViewId is a view template.
   -or-
   The ElementId ownerDBViewId is a perspective view.
   -or-
   The 3D view ownerDBViewId is not locked.
   -or-
   The reference can not be tagged.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentNullException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentNullException</a></td><td>
   A non-optional argument was NULL
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentOutOfRangeException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentOutOfRangeException</a></td><td>
   A value passed for an enumeration argument is not a member of that enumeration
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.InternalException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>InternalException</a></td><td>
   Tag creation failed.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.InvalidOperationException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>InvalidOperationException</a></td><td>
   There is no loaded tag type that can be used when tagging referenceToTag with tagMode.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationForbiddenException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationForbiddenException</a></td><td>
   The document is in failure mode: an operation has failed,
   and Revit requires the user to either cancel the operation
   or fix the problem (usually by deleting certain elements).
   -or-
   The document is being loaded, or is in the midst of another
   sensitive process.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationOutsideTransactionException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationOutsideTransactionException</a></td><td>
   The document has no open transaction.
</td></tr></table></div></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.IndependentTag">IndependentTag Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>