<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>CreateSpiralRun Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="CreateSpiralRun method" /><meta name="System.Keywords" content="StairsRun.CreateSpiralRun method" /><meta name="Description" content="Creates a spiral run in the project document by providing the center, start angle and included angle." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB.Architecture" /><meta name="file" content="2f31d042-a202-a1a4-42fe-998b02e26a4d" /><meta name="guid" content="2f31d042-a202-a1a4-42fe-998b02e26a4d" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Double,System.Boolean,Autodesk.Revit.DB.Architecture.StairsRunJustification)" />
<meta name="Microsoft.Help.TocParent" content="Methods.T:Autodesk.Revit.DB.Architecture.StairsRun" />
<meta name="Microsoft.Help.TocOrder" content="2" />
<meta name="Microsoft.Help.Keywords" content="CreateSpiralRun method" />
<meta name="Microsoft.Help.Keywords" content="StairsRun.CreateSpiralRun method" />
<meta name="Microsoft.Help.Keywords" content="CreateSpiralRun method" />
<meta name="Microsoft.Help.Keywords" content="StairsRun.CreateSpiralRun method" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Double,System.Boolean,Autodesk.Revit.DB.Architecture.StairsRunJustification)" /><MSHelp:TOCTitle Title="CreateSpiralRun Method " /><MSHelp:RLTitle Title="StairsRun.CreateSpiralRun Method  (Autodesk.Revit.DB.Architecture)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Double,System.Boolean,Autodesk.Revit.DB.Architecture.StairsRunJustification)" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBArchitectureStairsRunClassCreateSpiralRunTopic" /><MSHelp:Keyword Index="K" Term="CreateSpiralRun method" /><MSHelp:Keyword Index="K" Term="StairsRun.CreateSpiralRun method" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.Architecture.StairsRun.CreateSpiralRun" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Creates a spiral run in the project document by providing the center, start angle and included angle." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">StairsRun<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CreateSpiralRun Method </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">
   Creates a spiral run in the project document by providing the center, start angle and included angle.
</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Architecture">Autodesk.Revit.DB.Architecture</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<br /><b>Since:</b> 
   2013
<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a> <span class="identifier">CreateSpiralRun</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a> <span class="parameter">document</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a> <span class="parameter">stairsId</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> <span class="parameter">center</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">radius</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">startAngle</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">includedAngle</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">bool</a> <span class="parameter">clockwise</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRunJustification">StairsRunJustification</a> <span class="parameter">justification</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateSpiralRun</span> ( _
	<span class="parameter">document</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>, _
	<span class="parameter">stairsId</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>, _
	<span class="parameter">center</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>, _
	<span class="parameter">radius</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">startAngle</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">includedAngle</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">clockwise</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">Boolean</a>, _
	<span class="parameter">justification</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRunJustification">StairsRunJustification</a> _
) <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a></pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a>^ <span class="identifier">CreateSpiralRun</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>^ <span class="parameter">document</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>^ <span class="parameter">stairsId</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">center</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">radius</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">startAngle</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">includedAngle</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">bool</a> <span class="parameter">clockwise</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRunJustification">StairsRunJustification</a> <span class="parameter">justification</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="document"><dt><span class="parameter">document</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Document</a><br />
   The document.
</dd></dl><dl paramname="stairsId"><dt><span class="parameter">stairsId</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ElementId</a><br />
   The stairs that the new stairs run will belong to.
</dd></dl><dl paramname="center"><dt><span class="parameter">center</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>XYZ</a><br />
   The center of the location arc of the spiral run.
   The Z coordinate of the center is the base elevation for the new run (in model coordinates).
   It must be greater than or equal to the stairs base elevation.
</dd></dl><dl paramname="radius"><dt><span class="parameter">radius</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   The radius of the location arc of the spiral run.
</dd></dl><dl paramname="startAngle"><dt><span class="parameter">startAngle</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   The start angle of the location arc of the spiral run.
   The angle's coordinate system is world coordinate system which always is XYZ.BasisX and XYZ.BasisY.
</dd></dl><dl paramname="includedAngle"><dt><span class="parameter">includedAngle</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   The total angle covered by the spiral run. Must be a positive value (direction is determined by the clockwise flag).
</dd></dl><dl paramname="clockwise"><dt><span class="parameter">clockwise</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/a28wyd50" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Boolean</a><br />
   True if the spiral run will be created along clockwise direction, False otherwise.
</dd></dl><dl paramname="justification"><dt><span class="parameter">justification</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRunJustification">Autodesk.Revit.DB.Architecture<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>StairsRunJustification</a><br />
   The location path justification of the new stairs run.
</dd></dl></div><h4 class="subHeading">Return Value</h4>
   The new stairs run.
</div><h1 class="heading"><span onclick="ExpandCollapse(remarksToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(remarksToggle, event)" tabindex="0"><img id="remarksToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Remarks</span></h1><div id="remarksSection" class="section" name="collapseableSection" style="">
   The new stairs run and the document will be regenerated.
   This should be run from within an open transaction.
</div><h1 class="heading"><span onclick="ExpandCollapse(exceptionsToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exceptionsToggle, event)" tabindex="0"><img id="exceptionsToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Exceptions</span></h1><div id="exceptionsSection" class="section" name="collapseableSection" style=""><div class="tableSection"><table width="100%" cellspacing="2" cellpadding="5" frame="lhs"><tr><th class="exceptionNameColumn">Exception</th><th class="exceptionConditionColumn">Condition</th></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentException</a></td><td>
   The stairsId is not a valid stairs element.
   -or-
   The given value for startAngle is not finite
   -or-
   The input center is not a valid center for spiral run (probably the Z coordinate doesn't meet the restrictions)
   -or-
   The includedAngle doesn't satisfy riser restriction to generate spiral run (probably it's too small).
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentNullException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentNullException</a></td><td>
   A non-optional argument was NULL
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentOutOfRangeException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentOutOfRangeException</a></td><td>
   The given value for radius must be greater than 0 and no more than 30000 feet.
   -or-
   The given value for includedAngle must be positive.
   -or-
   A value passed for an enumeration argument is not a member of that enumeration
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentsInconsistentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentsInconsistentException</a></td><td>
   The radius is too small to generate a spiral run at the given justification.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.InvalidOperationException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>InvalidOperationException</a></td><td>
   The stairs element represented by stairsId is not in an active StairsEditScope.
   New components cannot be added to it.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationForbiddenException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationForbiddenException</a></td><td>
   The document is in failure mode: an operation has failed,
   and Revit requires the user to either cancel the operation
   or fix the problem (usually by deleting certain elements).
   -or-
   The document is being loaded, or is in the midst of another
   sensitive process.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationOutsideTransactionException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationOutsideTransactionException</a></td><td>
   The document has no open transaction.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.RegenerationFailedException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RegenerationFailedException</a></td><td>
   The center, radius, startAngle, includedAngle don't satisfy restrictions to generate spiral run.
</td></tr></table></div></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Architecture">Autodesk.Revit.DB.Architecture Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>