<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>CompoundStructure Methods</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="CompoundStructure class, methods" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="3731d7d5-cef4-87ef-24fb-6db7ea4ca36e" /><meta name="guid" content="3731d7d5-cef4-87ef-24fb-6db7ea4ca36e" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="Methods.T:Autodesk.Revit.DB.CompoundStructure" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.CompoundStructure" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="CompoundStructure class, methods" />
<meta name="Microsoft.Help.Keywords" content="CompoundStructure class, methods" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="Methods.T:Autodesk.Revit.DB.CompoundStructure" /><MSHelp:TOCTitle Title="CompoundStructure Methods" /><MSHelp:RLTitle Title="CompoundStructure Methods (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="Methods.T:Autodesk.Revit.DB.CompoundStructure" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBCompoundStructureMethodsTopic" /><MSHelp:Keyword Index="K" Term="CompoundStructure class, methods" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">CompoundStructure Methods</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.CompoundStructure">CompoundStructure Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.CompoundStructure">CompoundStructure</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.AddWallSweep(Autodesk.Revit.DB.WallSweepInfo)">AddWallSweep</a></td><td><div class="summary">
   Adds a new wall sweep or reveal to the compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.AssociateRegionWithLayer(System.Int32,System.Int32)">AssociateRegionWithLayer</a></td><td><div class="summary">
   Associates a region with a layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CanLayerBeStructuralMaterial(System.Int32)">CanLayerBeStructuralMaterial</a></td><td><div class="summary">
   Identifies if the input layer can be designated as defining the structural material for this structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CanLayerBeVariable(System.Int32)">CanLayerBeVariable</a></td><td><div class="summary">
   Identifies if the input layer can be designated as a variable thickness layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CanLayerWidthBeNonZero(System.Int32)">CanLayerWidthBeNonZero</a></td><td><div class="summary">
   Identifies if changing the width of an existing layer from zero to a positive value will create a rectangular region.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.ChangeRegionWidth(System.Int32,System.Double)">ChangeRegionWidth</a></td><td><div class="summary">
   Adjust the width of an existing simple region.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.ClearWallSweeps(Autodesk.Revit.DB.WallSweepType)">ClearWallSweeps</a></td><td><div class="summary">
   Removes all sweeps or reveals from the compound structure.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CreateSimpleCompoundStructure(System.Collections.Generic.IList{Autodesk.Revit.DB.CompoundStructureLayer})">CreateSimpleCompoundStructure</a></td><td><div class="summary">
   Creates a non-vertically compound structure comprised of parallel layers.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CreateSingleLayerCompoundStructure(Autodesk.Revit.DB.MaterialFunctionAssignment,System.Double,Autodesk.Revit.DB.ElementId)">CreateSingleLayerCompoundStructure(MaterialFunctionAssignment, Double, ElementId)</a></td><td><div class="summary">
   Creates a CompoundStructure containing a single layer.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.CreateSingleLayerCompoundStructure(System.Double,Autodesk.Revit.DB.MaterialFunctionAssignment,System.Double,Autodesk.Revit.DB.ElementId)">CreateSingleLayerCompoundStructure(Double, MaterialFunctionAssignment, Double, ElementId)</a></td><td><div class="summary">
   Creates a vertically compound CompoundStructure with one layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.DeleteLayer(System.Int32)">DeleteLayer</a></td><td><div class="summary">
   Deletes the specified layer from this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.Dispose">Dispose</a></td><td /></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.FindEnclosingRegionAndSegments(Autodesk.Revit.DB.UV,Autodesk.Revit.DB.RectangularGridSegmentOrientation,System.Int32@,System.Int32@)">FindEnclosingRegionAndSegments</a></td><td><div class="summary">
   Given a pair of grid coordinates, and a direction for splitting, returns the enclosing region and the two segments
   intersected by a line through the grid point.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetAdjacentRegions(System.Int32)">GetAdjacentRegions</a></td><td><div class="summary">
   Gets the ids of region bound to a specified segment.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetCoreBoundaryLayerIndex(Autodesk.Revit.DB.ShellLayerType)">GetCoreBoundaryLayerIndex</a></td><td><div class="summary">
   Returns the index of the layer just below the core boundary.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetDeckEmbeddingType(System.Int32)">GetDeckEmbeddingType</a></td><td><div class="summary">
   Retrieves the deck embedding type used for the specified structural deck.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetDeckProfileId(System.Int32)">GetDeckProfileId</a></td><td><div class="summary">
   Retrieves the profile loop used for the specified structural deck.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetExtendableRegionIds(System.Boolean)">GetExtendableRegionIds</a></td><td><div class="summary">
   Gets the extendable region ids for the compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetFirstCoreLayerIndex">GetFirstCoreLayerIndex</a></td><td><div class="summary">
   Gets the index of the first core layer.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetLastCoreLayerIndex">GetLastCoreLayerIndex</a></td><td><div class="summary">
   Gets the index of the last core layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetLayerAssociatedToRegion(System.Int32)">GetLayerAssociatedToRegion</a></td><td><div class="summary">
   Gets the layer associated to a particular region.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetLayerFunction(System.Int32)">GetLayerFunction</a></td><td><div class="summary">
   Retrieves the function of the specified layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetLayers">GetLayers</a></td><td><div class="summary">
   A copy of the layers which define this compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetLayerWidth(System.Int32)">GetLayerWidth</a></td><td><div class="summary">
   Retrieves the width of a specified layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetMaterialId(System.Int32)">GetMaterialId</a></td><td><div class="summary">
   Retrieves the material element id of a specified layer.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetMinimumLayerThickness">GetMinimumLayerThickness</a></td><td><div class="summary">
   Get the minimum allowable layer thickness.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetNumberOfShellLayers(Autodesk.Revit.DB.ShellLayerType)">GetNumberOfShellLayers</a></td><td><div class="summary">
   Retrieves the number of interior or exterior shell layers.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetOffsetForLocationLine(Autodesk.Revit.DB.WallLocationLine)">GetOffsetForLocationLine</a></td><td><div class="summary">
   Returns the offset from the center of the compound structure to the given location line value.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetPreviousNonZeroLayerIndex(System.Int32)">GetPreviousNonZeroLayerIndex</a></td><td><div class="summary">
   Returns the index of the nearest non-zero width layer before this layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetRegionEnvelope(System.Int32)">GetRegionEnvelope</a></td><td><div class="summary">
   Gets the envelope that a specified region spans.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetRegionIds">GetRegionIds</a></td><td><div class="summary">
   Gets the region ids of this compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetRegionsAlongLevel(System.Double)">GetRegionsAlongLevel</a></td><td><div class="summary">
   Returns the ids of the regions encountered as the vertically compound structure is traversed
   at a constant height above the bottom a wall to which this structure is applied.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetRegionsAssociatedToLayer(System.Int32)">GetRegionsAssociatedToLayer</a></td><td><div class="summary">
   Gets the set of region ids associated to a particular layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetSegmentCoordinate(System.Int32)">GetSegmentCoordinate</a></td><td><div class="summary">
   Gets the coordinate of a segment.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetSegmentEndPoints(System.Int32,System.Int32,Autodesk.Revit.DB.UV@,Autodesk.Revit.DB.UV@)">GetSegmentEndPoints</a></td><td><div class="summary">
   Gets the end points of a segment.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetSegmentIds">GetSegmentIds</a></td><td><div class="summary">
   Gets the segment ids of this compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetSegmentOrientation(System.Int32)">GetSegmentOrientation</a></td><td><div class="summary">
   Gets the orientation of a segment.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetSimpleCompoundStructure(System.Double,System.Double)">GetSimpleCompoundStructure</a></td><td><div class="summary">
   Takes a horizontal slice through a sample wall to which this CompoundStructure is applied
   and returns a simple compound structure which describes that slice, i.e. a series of
   parallel layers.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetWallSweepsInfo(Autodesk.Revit.DB.WallSweepType)">GetWallSweepsInfo</a></td><td><div class="summary">
   Obtains a list of the intrinsic wall sweeps or reveals in this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetWidth">GetWidth<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">
   The width implied by this compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.GetWidth(System.Int32)">GetWidth(Int32)</a></td><td><div class="summary">
   Computes the width of the envelope (2d bounding box) of the specified region.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsCoreLayer(System.Int32)">IsCoreLayer</a></td><td><div class="summary">
   Checks if the specified layer is a core layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsEqual(Autodesk.Revit.DB.CompoundStructure)">IsEqual</a></td><td><div class="summary">
   Checks whether this CompoundStructure is the same as another CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsLayerValid(System.Int32,Autodesk.Revit.DB.CompoundStructureLayer)">IsLayerValid</a></td><td><div class="summary">
   Verifies that the data in this layer is internally consistent.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsRectangularRegion(System.Int32)">IsRectangularRegion</a></td><td><div class="summary">
   Determines whether the specified region is rectangular.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsSimpleRegion(System.Int32)">IsSimpleRegion</a></td><td><div class="summary">
   Determines whether the region is a simple region in this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsStructuralDeck(System.Int32)">IsStructuralDeck</a></td><td><div class="summary">
   Determines whether a specified layer is a structural deck.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsValid(Autodesk.Revit.DB.Document,System.Collections.Generic.IDictionary{System.Int32,Autodesk.Revit.DB.CompoundStructureError}@,System.Collections.Generic.IDictionary{System.Int32,System.Int32}@)">IsValid</a></td><td><div class="summary">
   Checks for errors or inconsistencies in the data in this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsValidRegionId(System.Int32)">IsValidRegionId</a></td><td><div class="summary">
   Determines whether the specified integer is actually the id of a region in this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsValidSampleHeight(System.Double)">IsValidSampleHeight</a></td><td><div class="summary">
   Is the specified height a valid sample height for this compound structure?
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsValidSegmentId(System.Int32)">IsValidSegmentId</a></td><td><div class="summary">
   Determines whether the specified integer is actually the id of a segment in this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.IsVerticallyHomogeneous">IsVerticallyHomogeneous</a></td><td><div class="summary">
   Indicates whether this CompoundStructure represents a single set of parallel layers.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.MergeRegionsAdjacentToSegment(System.Int32,System.Int32)">MergeRegionsAdjacentToSegment</a></td><td><div class="summary">
   Merges the two regions which share the specified segment.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.ParticipatesInWrapping(System.Int32)">ParticipatesInWrapping</a></td><td><div class="summary">
   Identifies if a layer is included in wrapping at inserts and ends.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.RemoveWallSweep(Autodesk.Revit.DB.WallSweepType,System.Int32)">RemoveWallSweep</a></td><td><div class="summary">
   Removes a single sweep or reveal from the compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetDeckEmbeddingType(System.Int32,Autodesk.Revit.DB.StructDeckEmbeddingType)">SetDeckEmbeddingType</a></td><td><div class="summary">
   Sets the deck embedding type to use for the specified structural deck.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetDeckProfileId(System.Int32,Autodesk.Revit.DB.ElementId)">SetDeckProfileId</a></td><td><div class="summary">
   Sets the profile loop to use for the specified structural deck.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetExtendableRegionIds(System.Boolean,System.Collections.Generic.IList{System.Int32})">SetExtendableRegionIds</a></td><td><div class="summary">
   Sets the extendable region ids for the compound structure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetLayer(System.Int32,Autodesk.Revit.DB.CompoundStructureLayer)">SetLayer</a></td><td><div class="summary">
   Sets a single layer for this CompoundStructure.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetLayerFunction(System.Int32,Autodesk.Revit.DB.MaterialFunctionAssignment)">SetLayerFunction</a></td><td><div class="summary">
   Sets the function of the specified layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetLayers(System.Collections.Generic.IList{Autodesk.Revit.DB.CompoundStructureLayer})">SetLayers</a></td><td><div class="summary">
   Completely resets this CompoundStructure and applies a new set of layers.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetLayerWidth(System.Int32,System.Double)">SetLayerWidth</a></td><td><div class="summary">
   Sets the width of a specified layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetMaterialId(System.Int32,Autodesk.Revit.DB.ElementId)">SetMaterialId</a></td><td><div class="summary">
   Sets a material element for a specified layer.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetNumberOfShellLayers(Autodesk.Revit.DB.ShellLayerType,System.Int32)">SetNumberOfShellLayers</a></td><td><div class="summary">
   Sets the number of interior or exterior shell layers.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SetParticipatesInWrapping(System.Int32,System.Boolean)">SetParticipatesInWrapping</a></td><td><div class="summary">
   Assigns if a layer is included in wrapping at inserts and ends.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SplitRegion(Autodesk.Revit.DB.UV,Autodesk.Revit.DB.RectangularGridSegmentOrientation)">SplitRegion(UV, RectangularGridSegmentOrientation)</a></td><td><div class="summary">
   Splits the region which contains the specified grid point by a line with the specified direction.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.CompoundStructure.SplitRegion(Autodesk.Revit.DB.UV,Autodesk.Revit.DB.RectangularGridSegmentOrientation,System.Int32@)">SplitRegion(UV, RectangularGridSegmentOrientation, Int32<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">
   Splits the region which contains the specified grid point by a line with the specified direction.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.CompoundStructure">CompoundStructure Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>