<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>Document Methods</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Document class, methods" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.Creation" /><meta name="file" content="37523148-0dd8-7a2a-8ce9-220095429dd9" /><meta name="guid" content="37523148-0dd8-7a2a-8ce9-220095429dd9" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="Methods.T:Autodesk.Revit.Creation.Document" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.Creation.Document" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="Document class, methods" />
<meta name="Microsoft.Help.Keywords" content="Document class, methods" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="Methods.T:Autodesk.Revit.Creation.Document" /><MSHelp:TOCTitle Title="Document Methods" /><MSHelp:RLTitle Title="Document Methods (Autodesk.Revit.Creation)" /><MSHelp:Keyword Index="A" Term="Methods.T:Autodesk.Revit.Creation.Document" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitCreationDocumentMethodsTopic" /><MSHelp:Keyword Index="K" Term="Document class, methods" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">Document Methods</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Document">Document Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Document">Document</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.APIObject.Dispose">Dispose</a></td><td><div class="summary">Causes the object to release immediately any resources it may be utilizing.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewAlignment(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Reference)">NewAlignment</a></td><td><div class="summary">Add a new locked alignment into the Autodesk Revit document.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewArea(Autodesk.Revit.DB.ViewPlan,Autodesk.Revit.DB.UV)">NewArea</a></td><td><div class="summary">Creates a new area</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)">NewAreaBoundaryConditions(Element, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</a></td><td><div class="summary"> Creates a new Area BoundaryConditions element on a host element. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewAreaBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)">NewAreaBoundaryConditions(Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</a></td><td><div class="summary"> Creates a new Area BoundaryConditions element on a reference. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewAreaBoundaryLine(Autodesk.Revit.DB.SketchPlane,Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.ViewPlan)">NewAreaBoundaryLine</a></td><td><div class="summary">Creates a new boundary line as an Area border.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewAreas(System.Collections.Generic.List{Autodesk.Revit.Creation.AreaCreationData})">NewAreas</a></td><td><div class="summary">Creates new areas</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewAreaTag(Autodesk.Revit.DB.ViewPlan,Autodesk.Revit.DB.Area,Autodesk.Revit.DB.UV)">NewAreaTag</a></td><td><div class="summary">Creates a new area tag.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewCrossFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">NewCrossFitting</a></td><td><div class="summary">Add a new family instance of a cross fitting into the Autodesk Revit document,
using four connectors.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewCurtainSystem(Autodesk.Revit.DB.FaceArray,Autodesk.Revit.DB.CurtainSystemType)">NewCurtainSystem</a></td><td><div class="summary">Creates a new CurtainSystem element from a set of faces.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewCurtainSystem2(Autodesk.Revit.DB.ReferenceArray,Autodesk.Revit.DB.CurtainSystemType)">NewCurtainSystem2</a></td><td><div class="summary">Creates a new CurtainSystem element from a set of face references.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewDetailCurve(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Curve)">NewDetailCurve</a></td><td><div class="summary"> Creates a new detail curve element. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewDetailCurveArray(Autodesk.Revit.DB.View,Autodesk.Revit.DB.CurveArray)">NewDetailCurveArray</a></td><td><div class="summary"> Creates an array of new detail curve elements. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewDimension(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.ReferenceArray)">NewDimension(View, Line, ReferenceArray)</a></td><td><div class="summary"> Creates a new linear dimension object using the default dimension style.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewDimension(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.ReferenceArray,Autodesk.Revit.DB.DimensionType)">NewDimension(View, Line, ReferenceArray, DimensionType)</a></td><td><div class="summary"> Creates a new linear dimension object using the specified dimension style.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewElbowFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">NewElbowFitting</a></td><td><div class="summary">Add a new family instance of an elbow fitting into the Autodesk Revit document,
using two connectors.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewElectricalSystem(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Electrical.ElectricalSystemType)">NewElectricalSystem(Connector, ElectricalSystemType)</a></td><td> <font color="red"><b>Obsolete. </b></font><div class="summary">Creates a new MEP Electrical System element from an unused Connector.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewElectricalSystem(System.Collections.Generic.ICollection{Autodesk.Revit.DB.ElementId},Autodesk.Revit.DB.Electrical.ElectricalSystemType)">NewElectricalSystem(ICollection<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>ElementId<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, ElectricalSystemType)</a></td><td> <font color="red"><b>Obsolete. </b></font><div class="summary">Creates a new MEP Electrical System element from a set of electrical components.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewExtrusionRoof(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.ReferencePlane,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.RoofType,System.Double,System.Double)">NewExtrusionRoof</a></td><td><div class="summary">Creates a new Extrusion Roof.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.Face,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstance(Face, Line, FamilySymbol)</a></td><td><div class="summary">Inserts a new instance of a family onto a face of an existing element,
 using a line on that face for its position, and a type/symbol.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.Line,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.View)">NewFamilyInstance(Line, FamilySymbol, View)</a></td><td><div class="summary">Add a line based detail family instance into the Autodesk Revit document, 
using an line and a view where the instance should be placed.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstance(Reference, Line, FamilySymbol)</a></td><td><div class="summary">Inserts a new instance of a family onto a face referenced by the input Reference instance,
 using a line on that face for its position, and a type/symbol.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(XYZ, FamilySymbol, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document, using a location and a
type/symbol.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.View)">NewFamilyInstance(XYZ, FamilySymbol, View)</a></td><td><div class="summary">Add a new family instance into the Autodesk Revit document, 
using an origin and a view where the instance should be placed.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFamilyInstance(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(Curve, FamilySymbol, Level, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document, 
using a curve, type/symbol and reference level.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.Face,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstance(Face, XYZ, XYZ, FamilySymbol)</a></td><td><div class="summary">Inserts a new instance of a family onto a face of an existing element,
 using a location, reference direction, and a type/symbol.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstance(Reference, XYZ, XYZ, FamilySymbol)</a></td><td><div class="summary">Inserts a new instance of a family onto a face referenced by the input Reference instance,
 using a location, reference direction, and a type/symbol.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(XYZ, FamilySymbol, Level, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document, using a location,
type/symbol and a base level.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(XYZ, FamilySymbol, Element, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document,
using a location, type/symbol, and the host element.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(XYZ, FamilySymbol, Element, Level, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document,
using a location, type/symbol, the host element and a base level.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstance(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstance(XYZ, FamilySymbol, XYZ, Element, StructuralType)</a></td><td><div class="summary">Inserts a new instance of a family into the document,
using a location, type/symbol, the host element and a reference direction.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewFamilyInstances2(System.Collections.Generic.List{Autodesk.Revit.Creation.FamilyInstanceCreationData})">NewFamilyInstances2</a></td><td><div class="summary"> Creates Family instances within the document.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFascia(Autodesk.Revit.DB.Architecture.FasciaType,Autodesk.Revit.DB.Reference)">NewFascia(FasciaType, Reference)</a></td><td><div class="summary">Creates a fascia along a reference.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFascia(Autodesk.Revit.DB.Architecture.FasciaType,Autodesk.Revit.DB.ReferenceArray)">NewFascia(FasciaType, ReferenceArray)</a></td><td><div class="summary">Creates a fascia along a reference array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexDuct(System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},Autodesk.Revit.DB.Mechanical.FlexDuctType)">NewFlexDuct(IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, FlexDuctType)</a></td><td><div class="summary">Adds a new flexible duct into the document, 
using a point array and duct type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexDuct(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Mechanical.FlexDuctType)">NewFlexDuct(Connector, Connector, FlexDuctType)</a></td><td><div class="summary">Adds a new flexible duct into the document, 
using two connector, and duct type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexDuct(Autodesk.Revit.DB.Connector,System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},Autodesk.Revit.DB.Mechanical.FlexDuctType)">NewFlexDuct(Connector, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, FlexDuctType)</a></td><td><div class="summary">Adds a new flexible duct into the document, 
using a connector, point array and duct type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexPipe(System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},Autodesk.Revit.DB.Plumbing.FlexPipeType)">NewFlexPipe(IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, FlexPipeType)</a></td><td><div class="summary">Adds a new flexible pipe into the document, 
using a point array and pipe type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexPipe(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Plumbing.FlexPipeType)">NewFlexPipe(Connector, Connector, FlexPipeType)</a></td><td><div class="summary">Adds a new flexible pipe into the document, 
using two connector, and flexible pipe type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFlexPipe(Autodesk.Revit.DB.Connector,System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},Autodesk.Revit.DB.Plumbing.FlexPipeType)">NewFlexPipe(Connector, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, FlexPipeType)</a></td><td><div class="summary">Adds a new flexible pipe into the document, 
using a connector, point array and pipe type.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFloor(Autodesk.Revit.DB.CurveArray,System.Boolean)">NewFloor(CurveArray, Boolean)</a></td><td><div class="summary"> Creates a floor within the project with the given horizontal profile using the default floor style.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFloor(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.FloorType,Autodesk.Revit.DB.Level,System.Boolean)">NewFloor(CurveArray, FloorType, Level, Boolean)</a></td><td><div class="summary"> Creates a floor within the project with the given horizontal profile and floor style on the specified level. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFloor(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.FloorType,Autodesk.Revit.DB.Level,System.Boolean,Autodesk.Revit.DB.XYZ)">NewFloor(CurveArray, FloorType, Level, Boolean, XYZ)</a></td><td><div class="summary"> Creates a floor within the project with the given horizontal profile and floor style on the specified level with the specified normal vector. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFootPrintRoof(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.RoofType,Autodesk.Revit.DB.ModelCurveArray@)">NewFootPrintRoof</a></td><td><div class="summary">Creates a new FootPrintRoof element.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewFoundationSlab(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.FloorType,Autodesk.Revit.DB.Level,System.Boolean,Autodesk.Revit.DB.XYZ)">NewFoundationSlab</a></td><td><div class="summary"> Creates a foundation slab within the project with the given horizontal profile and floor style on the specified level. </div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewGroup(System.Collections.Generic.ICollection{Autodesk.Revit.DB.ElementId})">NewGroup</a></td><td><div class="summary">Creates a new type of group.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewGutter(Autodesk.Revit.DB.Architecture.GutterType,Autodesk.Revit.DB.Reference)">NewGutter(GutterType, Reference)</a></td><td><div class="summary">Creates a gutter along a reference.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewGutter(Autodesk.Revit.DB.Architecture.GutterType,Autodesk.Revit.DB.ReferenceArray)">NewGutter(GutterType, ReferenceArray)</a></td><td><div class="summary">Creates a gutter along a reference array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewLineBoundaryConditions(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)">NewLineBoundaryConditions(Element, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</a></td><td><div class="summary"> Creates a new Line BoundaryConditions element on a host element. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewLineBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)">NewLineBoundaryConditions(Reference, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double, TranslationRotationValue, Double)</a></td><td><div class="summary"> Creates a new Line BoundaryConditions element on a reference. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewMechanicalSystem(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.ConnectorSet,Autodesk.Revit.DB.Mechanical.DuctSystemType)">NewMechanicalSystem</a></td><td><div class="summary">Creates a new MEP mechanical system element.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewModelCurve(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.SketchPlane)">NewModelCurve</a></td><td><div class="summary"> Creates a new model line element. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewModelCurveArray(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.SketchPlane)">NewModelCurveArray</a></td><td><div class="summary"> Creates an array of new model line elements. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewOpening(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.Creation.eRefFace)">NewOpening(Element, CurveArray, eRefFace)</a></td><td><div class="summary"> Creates a new opening in a beam, brace and column. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewOpening(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.CurveArray,System.Boolean)">NewOpening(Element, CurveArray, Boolean)</a></td><td><div class="summary"> Creates a new opening in a roof, floor and ceiling. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewOpening(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.CurveArray)">NewOpening(Level, Level, CurveArray)</a></td><td><div class="summary"> Creates a new shaft opening between a set of levels. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewOpening(Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">NewOpening(Wall, XYZ, XYZ)</a></td><td><div class="summary"> Creates a rectangular opening on a wall. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewPipingSystem(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.ConnectorSet,Autodesk.Revit.DB.Plumbing.PipeSystemType)">NewPipingSystem</a></td><td><div class="summary">Creates a new MEP piping system element.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewPointBoundaryConditions(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double,Autodesk.Revit.DB.Structure.TranslationRotationValue,System.Double)">NewPointBoundaryConditions</a></td><td><div class="summary"> Creates a new Point BoundaryConditions Element. </div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewReferencePlane(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.View)">NewReferencePlane</a></td><td><div class="summary"> Creates a new instance of ReferencePlane. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.NewReferencePlane2(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.View)">NewReferencePlane2</a></td><td><div class="summary"> Creates a new instance of ReferencePlane. </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRoom(Autodesk.Revit.DB.Phase)">NewRoom(Phase)</a></td><td><div class="summary"> Creates a new unplaced room and with an assigned phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRoom(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.UV)">NewRoom(Level, UV)</a></td><td><div class="summary"> Creates a new room on a level at a specified point. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRoom(Autodesk.Revit.DB.Architecture.Room,Autodesk.Revit.DB.PlanCircuit)">NewRoom(Room, PlanCircuit)</a></td><td><div class="summary"> Creates a new room within the confines of a plan circuit, or places an unplaced room within the confines of the plan circuit. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRoomBoundaryLines(Autodesk.Revit.DB.SketchPlane,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.View)">NewRoomBoundaryLines</a></td><td><div class="summary">Creates a new boundary line as an Room border.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRooms2(Autodesk.Revit.DB.Level)">NewRooms2(Level)</a></td><td><div class="summary"> Creates new rooms in each plan circuit found in the given level in the last phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRooms2(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Phase)">NewRooms2(Level, Phase)</a></td><td><div class="summary"> Creates new rooms in each plan circuit found in the given level in the given phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRooms2(Autodesk.Revit.DB.Phase,System.Int32)">NewRooms2(Phase, Int32)</a></td><td><div class="summary"> Creates new unplaced rooms in the given phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewRoomTag(Autodesk.Revit.DB.LinkElementId,Autodesk.Revit.DB.UV,Autodesk.Revit.DB.ElementId)">NewRoomTag</a></td><td><div class="summary"> Creates a new RoomTag referencing a room in the host model or in a Revit link. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSlab(Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Line,System.Double,System.Boolean)">NewSlab</a></td><td><div class="summary"> Creates a slab within the project with the given horizontal profile using the default floor style.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSlabEdge(Autodesk.Revit.DB.SlabEdgeType,Autodesk.Revit.DB.Reference)">NewSlabEdge(SlabEdgeType, Reference)</a></td><td><div class="summary">Creates a slab edge along a reference.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSlabEdge(Autodesk.Revit.DB.SlabEdgeType,Autodesk.Revit.DB.ReferenceArray)">NewSlabEdge(SlabEdgeType, ReferenceArray)</a></td><td><div class="summary">Creates a slab edge along a reference array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpace(Autodesk.Revit.DB.Phase)">NewSpace(Phase)</a></td><td><div class="summary"> Creates a new unplaced space on a given phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpace(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.UV)">NewSpace(Level, UV)</a></td><td><div class="summary">Creates a new space element on the given level at the given location.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpace(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Phase,Autodesk.Revit.DB.UV)">NewSpace(Level, Phase, UV)</a></td><td><div class="summary">Creates a new space element on the given level, at the given location, and assigned to the given phase.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpaceBoundaryLines(Autodesk.Revit.DB.SketchPlane,Autodesk.Revit.DB.CurveArray,Autodesk.Revit.DB.View)">NewSpaceBoundaryLines</a></td><td><div class="summary">Creates a new boundary line as an Space border.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpaces2(Autodesk.Revit.DB.Phase,System.Int32)">NewSpaces2(Phase, Int32)</a></td><td><div class="summary"> Creates a set of new unplaced spaces on a given phase. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpaces2(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Phase,Autodesk.Revit.DB.View)">NewSpaces2(Level, Phase, View)</a></td><td><div class="summary"> Creates new spaces on the available plan circuits of a the given level. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpaceTag(Autodesk.Revit.DB.Mechanical.Space,Autodesk.Revit.DB.UV,Autodesk.Revit.DB.View)">NewSpaceTag</a></td><td><div class="summary"> Creates a new SpaceTag. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpotCoordinate(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Boolean)">NewSpotCoordinate</a></td><td><div class="summary"> Generate a new spot coordinate object within the project.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewSpotElevation(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Boolean)">NewSpotElevation</a></td><td><div class="summary"> Generate a new spot elevation object within the project.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewTag(Autodesk.Revit.DB.View,Autodesk.Revit.DB.Element,System.Boolean,Autodesk.Revit.DB.TagMode,Autodesk.Revit.DB.TagOrientation,Autodesk.Revit.DB.XYZ)">NewTag</a></td><td> <font color="red"><b>Obsolete. </b></font><div class="summary"> Creates a new IndependentTag Element. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewTakeoffFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.MEPCurve)">NewTakeoffFitting</a></td><td><div class="summary">Add a new family instance of an takeoff fitting into the Autodesk Revit document,
using one connector and one MEP curve.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewTeeFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">NewTeeFitting</a></td><td><div class="summary">Add a new family instance of a tee fitting into the Autodesk Revit document,
using three connectors.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewTransitionFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">NewTransitionFitting</a></td><td><div class="summary">Add a new family instance of an transition fitting into the Autodesk Revit document,
using two connectors.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewUnionFitting(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">NewUnionFitting</a></td><td><div class="summary">Add a new family instance of an union fitting into the Autodesk Revit document,
using two connectors.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Document.NewZone(Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Phase)">NewZone</a></td><td><div class="summary">Creates a new Zone element.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.ItemFactoryBase.PlaceGroup(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.GroupType)">PlaceGroup</a></td><td><div class="summary">Place an instance of a Model Group into the Autodesk Revit document, using a location
and a group type.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.ItemFactoryBase">ItemFactoryBase</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Document">Document Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.Creation">Autodesk.Revit.Creation Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>