<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BuiltInFailures.CurtainWallFailures Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BuiltInFailures.CurtainWallFailures class" /><meta name="System.Keywords" content="BuiltInFailures.CurtainWallFailures class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="376f0f4f-e1e0-f704-79cb-4d48ced78602" /><meta name="guid" content="376f0f4f-e1e0-f704-79cb-4d48ced78602" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.CurtainWallFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.CurtainWallFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.CurtainWallFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.CurtainWallFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures" /><MSHelp:TOCTitle Title="BuiltInFailures.CurtainWallFailures Members" /><MSHelp:RLTitle Title="BuiltInFailures.CurtainWallFailures Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBuiltInFailuresCurtainWallFailuresMembersTopic" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.CurtainWallFailures class" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.CurtainWallFailures class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CurtainWallFailures Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CurtainWallFailures Class</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p><div class="summary">Provides a container of all Revit built-in FailureDefinitionId instances.</div></p><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CurtainWallFailures</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.AdjustEndCurtainWallParameterNoCorners">AdjustEndCurtainWallParameterNoCorners</a></td><td><div class="summary">
   Can't put Corner Mullion at end joined to non-Curtain Wall.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.AllGridSegmentsRemoved">AllGridSegmentsRemoved</a></td><td><div class="summary">
   Curtain grid lines must have at least one segment.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotApplyGridSpecification">CannotApplyGridSpecification</a></td><td><div class="summary">
   It is not possible to apply the host family's grid specification to this instance.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotDivideCurtainGrid">CannotDivideCurtainGrid</a></td><td><div class="summary">
   Can't divide Curtain Grid by Grid Line.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotGroupCurtainGridHost">CannotGroupCurtainGridHost</a></td><td><div class="summary">
   Curtain grid based elements cannot be grouped.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotHaveIndependentOverlappingGrids">CannotHaveIndependentOverlappingGrids</a></td><td><div class="summary">
   Overlapping independent type associated gridlines are not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotPlaceSplitMullions">CannotPlaceSplitMullions</a></td><td><div class="summary">
   Could not determine how to place the highlighted mullions after the wall was split.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotSplitOldMullions">CannotSplitOldMullions</a></td><td><div class="summary">
   Split does not work on curtain walls containing mullions created in Revit prior to version 4.0.  You may delete the mullions, place them again, and then proceed with splitting the wall.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotSwitchToCurtainWall">CannotSwitchToCurtainWall</a></td><td><div class="summary">
   Can't switch type to Curtain Wall after Edit Elevation Profile.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CannotUseCornerMullion">CannotUseCornerMullion</a></td><td><div class="summary">
   Corner Mullions must be placed at a location that can have neighboring Panels that are not tangent. With the exception of Wall Join locations, Corner Mullions are not currently supported on the external boundaries of Curtain elements.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CurtainGridFaceCannotBeReparamForGridRotation">CurtainGridFaceCannotBeReparamForGridRotation</a></td><td><div class="summary">
   Curtain grids cannot be rotated exactly as requested. Push "Adjust Grids" to get the nearest valid rotation.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CurtainGridOffHost">CurtainGridOffHost</a></td><td><div class="summary">
   Curtain grid has left its host.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.CurtainSystemHostInvisible">CurtainSystemHostInvisible</a></td><td><div class="summary">
   Element defining the Curtain System is invisible in the current view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.DanglingCurtainWallCorner">DanglingCurtainWallCorner</a></td><td><div class="summary">
   A Corner Mullion has been placed at the end of a Curtain Wall that is not joined to another Curtain Wall. The angle of the Corner Mullion will default to 90 degrees.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.DeletingCurtainSystemFaceGridLines">DeletingCurtainSystemFaceGridLines</a></td><td><div class="summary">
   Deleting Grid Lines residing on faces that no longer are part of a Curtain System.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.DependentGridlineMayBeDeleted">DependentGridlineMayBeDeleted</a></td><td><div class="summary">
   Type generated gridlines will become non-associated due to changes in the type.  Press delete if you wish to remove them instead.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.ExceedMaxDrivenGridlines">ExceedMaxDrivenGridlines</a></td><td><div class="summary">
   Changes have been made that cause a curtain wall with type driven grid lines to exceed the maximum allowed number of type driven lines (200 in direction (1) and 200 in direction (2)).  If you really need this many type driven grid lines, please split the affected wall before proceeding.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.ExessiveBeltDistance">ExessiveBeltDistance</a></td><td><div class="summary">
   The requested Measurement Line Offset would place the put the Measurement Line of the face boundaries.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridlinesOutOfBounds">GridlinesOutOfBounds</a></td><td><div class="summary">
   Manually placed curtain grid lines are on the wall edges or outside the wall boundaries.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridlinesOutOfBoundsWarn">GridlinesOutOfBoundsWarn</a></td><td><div class="summary">
   Manually placed curtain grid lines are on the wall edges or outside the wall boundaries.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridlinesOutsideWillBeRedependent">GridlinesOutsideWillBeRedependent</a></td><td><div class="summary">
   Type associated curtain grid lines outside of the edited wall boundaries will be made dependent again in order that they remain on the wall.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridlinesOverlap">GridlinesOverlap</a></td><td><div class="summary">
   Overlapping gridlines should be avoided, unless there are only two and one is host type dependent and the other is not.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridlinesWerePushed">GridlinesWerePushed</a></td><td><div class="summary">
   Panels and mullions created by a curtain grid were created with slight inaccuracies.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridOutOfOrder">GridOutOfOrder</a></td><td><div class="summary">
   Curtain wall grid lines have changed order.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridOutOfOrderError">GridOutOfOrderError</a></td><td><div class="summary">
   Curtain wall grid lines have changed order.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.GridOutsideWall">GridOutsideWall</a></td><td><div class="summary">
   Curtain wall grid lines are outside wall.  If you are trying to shorten the wall, please remove grid lines, including mullions on top of them.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.InvalidSkipSegments">InvalidSkipSegments</a></td><td><div class="summary">
   A curtain grid line had invalid removed segment data.  When correcting data, Revit may have split curtain panels that should be combined.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.MullionLostRefReorder">MullionLostRefReorder</a></td><td><div class="summary">
   Mullions have lost references as a result of gridlines changing order.  These mullions must be deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.MullionsWillBeDeleted">MullionsWillBeDeleted</a></td><td><div class="summary">
   The Mullions between the Panels being joined will be deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.MultipleDominatingMullions">MultipleDominatingMullions</a></td><td><div class="summary">
   Multiple dominating mullions on a grid face may cause ambiguous automatic adjustment of margins.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.MultipleIdsInCurtainSystem">MultipleIdsInCurtainSystem</a></td><td><div class="summary">
   A Curtain System cannot be based on faces from multiple elements.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.MustReplacePanels">MustReplacePanels</a></td><td><div class="summary">
   Missing Curtain Panels will be replaced with System Panels to complete command.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.NegativeBeltDistance">NegativeBeltDistance</a></td><td><div class="summary">
   Measurement Line Offset cannot be negative.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.NonSupportedCurtainWall">NonSupportedCurtainWall</a></td><td><div class="summary">
   Currently, only straight Walls with straight or arc edges are supported for non-rectangular Curtain Walls.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.NoPanelsLoaded">NoPanelsLoaded</a></td><td><div class="summary">
   No Curtain Panel Families loaded. Can't make arced Curtain Wall.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.RequestOrphanMullionDeletion">RequestOrphanMullionDeletion</a></td><td><div class="summary">
   Due to the changes in parameters of their hosts some mullions became non-type driven.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.RuledCurtainElementLostCurves">RuledCurtainElementLostCurves</a></td><td><div class="summary">
   Ruled Curtain System cannot be built. The Lines or Edges used to create it cannot be found.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures.TypePanelsFronNonRectCellsUnlocked">TypePanelsFronNonRectCellsUnlocked</a></td><td><div class="summary">
   Loaded family curtain panels cannot be used in non-rectangular cells of the curtain host. Type-driven panels from non-rectangular cells were unlocked and left unchanged.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.CurtainWallFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CurtainWallFailures Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>