<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>AddListeningDimensionSegmentToBend Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="AddListeningDimensionSegmentToBend method" /><meta name="System.Keywords" content="RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend method" /><meta name="Description" content="Specify a dimension perpendicular to one fixed-direction segment, referring to that segment and some other bend in the shape, measured by a read-only parameter." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB.Structure" /><meta name="file" content="4696bd5b-9eca-44f2-9978-5f6d4c4fd563" /><meta name="guid" content="4696bd5b-9eca-44f2-9978-5f6d4c4fd563" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend(Autodesk.Revit.DB.ElementId,System.Double,System.Double,System.Int32,System.Int32,System.Int32)" />
<meta name="Microsoft.Help.TocParent" content="Methods.T:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments" />
<meta name="Microsoft.Help.TocOrder" content="5" />
<meta name="Microsoft.Help.Keywords" content="AddListeningDimensionSegmentToBend method" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend method" />
<meta name="Microsoft.Help.Keywords" content="AddListeningDimensionSegmentToBend method" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend method" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend(Autodesk.Revit.DB.ElementId,System.Double,System.Double,System.Int32,System.Int32,System.Int32)" /><MSHelp:TOCTitle Title="AddListeningDimensionSegmentToBend Method " /><MSHelp:RLTitle Title="RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend Method  (Autodesk.Revit.DB.Structure)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend(Autodesk.Revit.DB.ElementId,System.Double,System.Double,System.Int32,System.Int32,System.Int32)" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBStructureRebarShapeDefinitionBySegmentsClassAddListeningDimensionSegmentToBendTopic" /><MSHelp:Keyword Index="K" Term="AddListeningDimensionSegmentToBend method" /><MSHelp:Keyword Index="K" Term="RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend method" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments.AddListeningDimensionSegmentToBend" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Specify a dimension perpendicular to one fixed-direction segment, referring to that segment and some other bend in the shape, measured by a read-only parameter." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">RebarShapeDefinitionBySegments<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>AddListeningDimensionSegmentToBend Method </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments">RebarShapeDefinitionBySegments Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">
   Specify a dimension perpendicular to one fixed-direction segment,
   referring to that segment and some other bend in the shape,
   measured by a read-only parameter.
</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Structure">Autodesk.Revit.DB.Structure</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">void</span> <span class="identifier">AddListeningDimensionSegmentToBend</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a> <span class="parameter">paramId</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">constraintDirCoordX</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">constraintDirCoordY</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iSegment0</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iSegment1</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iEnd1</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Sub</span> <span class="identifier">AddListeningDimensionSegmentToBend</span> ( _
	<span class="parameter">paramId</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>, _
	<span class="parameter">constraintDirCoordX</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">constraintDirCoordY</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">iSegment0</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">Integer</a>, _
	<span class="parameter">iSegment1</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">Integer</a>, _
	<span class="parameter">iEnd1</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">Integer</a> _
)</pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<span class="keyword">void</span> <span class="identifier">AddListeningDimensionSegmentToBend</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>^ <span class="parameter">paramId</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">constraintDirCoordX</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">constraintDirCoordY</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iSegment0</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iSegment1</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">int</a> <span class="parameter">iEnd1</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="paramId"><dt><span class="parameter">paramId</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ElementId</a><br />
   Id of a parameter to report the length of the dimension. The parameter will be read-only
   on Rebar instances.
</dd></dl><dl paramname="constraintDirCoordX"><dt><span class="parameter">constraintDirCoordX</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   The x-coordinate of a 2D vector specifying the constraint direction.
</dd></dl><dl paramname="constraintDirCoordY"><dt><span class="parameter">constraintDirCoordY</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   The y-coordinate of a 2D vector specifying the constraint direction.
</dd></dl><dl paramname="iSegment0"><dt><span class="parameter">iSegment0</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Int32</a><br />
   Index of the first segment (0 to NumberOfSegments - 1).
</dd></dl><dl paramname="iSegment1"><dt><span class="parameter">iSegment1</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Int32</a><br />
   Index of the second segment (0 to NumberOfSegments - 1).
</dd></dl><dl paramname="iEnd1"><dt><span class="parameter">iEnd1</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/td2s409d" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Int32</a><br />
   End (0 or 1) of the second segment.
</dd></dl></div></div><h1 class="heading"><span onclick="ExpandCollapse(exceptionsToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exceptionsToggle, event)" tabindex="0"><img id="exceptionsToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Exceptions</span></h1><div id="exceptionsSection" class="section" name="collapseableSection" style=""><div class="tableSection"><table width="100%" cellspacing="2" cellpadding="5" frame="lhs"><tr><th class="exceptionNameColumn">Exception</th><th class="exceptionConditionColumn">Condition</th></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentException</a></td><td>
   paramId is not the id of a shared parameter in the current document,
   or its unit type is not UT_Reinforcement_Length or UT_Angle.
   -or-
   The length of the vector (constraintDirCoordX, constraintDirCoordY) is too close to zero.
   -or-
   iSegment0 is not between 0 and NumberOfSegments.
   -or-
   Edge iSegment0 has a variable angle; it must have a fixed angle perpendicular to (constraintDirCoordX, constraintDirCoordY).
   -or-
   iSegment1 is not between 0 and NumberOfSegments.
   -or-
   iEnd1 is neither 0 nor 1.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentNullException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentNullException</a></td><td>
   A non-optional argument was NULL
</td></tr></table></div></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDefinitionBySegments">RebarShapeDefinitionBySegments Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Structure">Autodesk.Revit.DB.Structure Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>