<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>NurbSpline Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="NurbSpline class" /><meta name="System.Keywords" content="NurbSpline class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.NurbSpline class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="7602714c-85c5-d3ba-e824-8f57590a59c8" /><meta name="guid" content="7602714c-85c5-d3ba-e824-8f57590a59c8" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.NurbSpline" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.NurbSpline" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.NurbSpline class" />
<meta name="Microsoft.Help.Keywords" content="NurbSpline class" />
<meta name="Microsoft.Help.Keywords" content="NurbSpline class, all members" />
<meta name="Microsoft.Help.Keywords" content="NurbSpline class" />
<meta name="Microsoft.Help.Keywords" content="NurbSpline class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.NurbSpline class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.NurbSpline" /><MSHelp:TOCTitle Title="NurbSpline Members" /><MSHelp:RLTitle Title="NurbSpline Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.NurbSpline" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBNurbSplineMembersTopic" /><MSHelp:Keyword Index="K" Term="NurbSpline class" /><MSHelp:Keyword Index="K" Term="NurbSpline class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.NurbSpline class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">NurbSpline Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.NurbSpline">NurbSpline Class</a> <a href="#methodTableToggle" onclick="OpenSection(methodTableToggle)">Methods</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p /><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.NurbSpline">NurbSpline</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Clone">Clone</a></td><td><div class="summary">Returns a copy of this curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.ComputeDerivatives(System.Double,System.Boolean)">ComputeDerivatives</a></td><td><div class="summary">
   Returns the vectors describing the curve at the specified parameter.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.ComputeNormalizedParameter(System.Double)">ComputeNormalizedParameter</a></td><td><div class="summary">Computes the normalized curve parameter from the raw parameter.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.ComputeRawParameter(System.Double)">ComputeRawParameter</a></td><td><div class="summary">Computes the raw parameter from the normalized parameter.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.Create(Autodesk.Revit.DB.HermiteSpline)">Create</a></td><td><div class="summary">
   Creates a new geometric NurbSpline object from a HermiteSpline.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.CreateCurve(Autodesk.Revit.DB.HermiteSpline)">CreateCurve(HermiteSpline)</a></td><td><div class="summary">
   Creates a new geometric Curve object by converting the given HermiteSpline.
   The created curve may be a NURBSpline or a simpler curve such as line or arc.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.CreateCurve(System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},System.Collections.Generic.IList{System.Double})">CreateCurve(IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>Double<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>)</a></td><td><div class="summary">
   Creates a new geometric Curve object from NURBS curve data containing just control points and weights.
   The created curve may be a NURBSpline or a simpler curve such as line or arc.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.CreateCurve(System.Int32,System.Collections.Generic.IList{System.Double},System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ})">CreateCurve(Int32, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>Double<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>)</a></td><td><div class="summary">
   Creates a new geometric Curve object from NURBS curve data, which does not include weights.
   The created curve may be a NURBSpline or a simpler curve such as line or arc.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.CreateCurve(System.Int32,System.Collections.Generic.IList{System.Double},System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},System.Collections.Generic.IList{System.Double})">CreateCurve(Int32, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>Double<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>Double<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>)</a></td><td><div class="summary">
   Creates a new geometric Curve object from NURBS curve data, which includes weights.
   The created curve may be a NURBSpline or a simpler curve such as line or arc.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.CreateOffset(System.Double,Autodesk.Revit.DB.XYZ)">CreateOffset</a></td><td><div class="summary">
   Creates a new curve that is an offset of the existing curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.CreateReversed">CreateReversed</a></td><td><div class="summary">
   Creates a new curve with the opposite orientation of the existing curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.CreateTransformed(Autodesk.Revit.DB.Transform)">CreateTransformed</a></td><td><div class="summary">
   Crates a new instance of a curve as a transformation of this curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.APIObject.Dispose">Dispose</a></td><td><div class="summary">Causes the object to release immediately any resources it may be utilizing.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Distance(Autodesk.Revit.DB.XYZ)">Distance</a></td><td><div class="summary">Returns the shortest distance from the specified point to this curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.GeometryObject.Equals(System.Object)">Equals</a></td><td><div class="summary"> Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.  </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Evaluate(System.Double,System.Boolean)">Evaluate</a></td><td><div class="summary">
   Evaluates and returns the point that matches a parameter along the curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.GetEndParameter(System.Int32)">GetEndParameter</a></td><td><div class="summary">
   Returns the raw parameter value at the start or end of this curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.GetEndPoint(System.Int32)">GetEndPoint</a></td><td><div class="summary">
   Returns the 3D point at the start or end of this curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.GetEndPointReference(System.Int32)">GetEndPointReference</a></td><td><div class="summary">Returns a stable reference to the start point or the end point of the curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.GeometryObject.GetHashCode">GetHashCode</a></td><td><div class="summary">
Gets the integer value of the geometry object as hash code
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Intersect(Autodesk.Revit.DB.Curve)">Intersect(Curve)</a></td><td><div class="summary">Calculates the intersection of this curve with the specified curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Intersect(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.IntersectionResultArray@)">Intersect(Curve, IntersectionResultArray<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">Calculates the intersection of this curve with the specified curve and returns the intersection results.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.IsInside(System.Double)">IsInside(Double)</a></td><td><div class="summary">Indicates whether the specified parameter value is within this curve's bounds.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.IsInside(System.Double,System.Int32@)">IsInside(Double, Int32<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">Indicates whether the specified parameter value is within this curve's bounds and outputs the end index.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.MakeBound(System.Double,System.Double)">MakeBound</a></td><td><div class="summary">Changes the bounds of this curve to the specified values.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.MakeUnbound">MakeUnbound</a></td><td><div class="summary">Makes this curve unbound.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Project(Autodesk.Revit.DB.XYZ)">Project</a></td><td><div class="summary">Projects the specified point on this curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.NurbSpline.SetControlPointsAndWeights(System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ},Autodesk.Revit.DB.DoubleArray)">SetControlPointsAndWeights</a></td><td><div class="summary">Set the control points, weights simultaneously.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.SetGraphicsStyleId(Autodesk.Revit.DB.ElementId)">SetGraphicsStyleId</a></td><td><div class="summary">Sets the graphics style id for this curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Curve.Tessellate">Tessellate</a></td><td><div class="summary">Valid only if the curve is bound. Returns a polyline approximation to the curve.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.ApproximateLength">ApproximateLength</a></td><td><div class="summary">The approximate length of the curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.CtrlPoints">CtrlPoints</a></td><td><div class="summary">Returns the control points of the nurb spline.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.Degree">Degree</a></td><td><div class="summary">Returns the degree of the nurb spline.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.GraphicsStyleId">GraphicsStyleId</a></td><td><div class="summary">The ElementId of the GeometryObject's GraphicsStyle</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.IsBound">IsBound</a></td><td><div class="summary">Describes whether the parameter of the curve is restricted to a particular interval.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.isClosed">isClosed</a></td><td><div class="summary">Return/set the nurb spline's isClosed property.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.IsCyclic">IsCyclic</a></td><td><div class="summary">The boolean value that indicates whether this curve is cyclic.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.IsElementGeometry">IsElementGeometry</a></td><td><div class="summary">Indicates whether this geometry is obtained directly from an Element.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.isRational">isRational</a></td><td><div class="summary">Returns whether the nurb spline is rational or not.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.APIObject.IsReadOnly">IsReadOnly</a></td><td><div class="summary">Identifies if the object is read-only or modifiable.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.Knots">Knots</a></td><td><div class="summary">Return/set the knots of the nurb spline.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.Length">Length</a></td><td><div class="summary">The exact length of the curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.Period">Period</a></td><td><div class="summary">The period of this curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Curve.Reference">Reference</a></td><td><div class="summary">Returns a stable reference to the curve.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.Visibility">Visibility</a></td><td><div class="summary">The visibility.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.NurbSpline.Weights">Weights</a></td><td><div class="summary">Returns the weights of the nurb spline.</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.NurbSpline">NurbSpline Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>