<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>ConicalFace Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="ConicalFace class" /><meta name="System.Keywords" content="ConicalFace class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.ConicalFace class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="7e393f5b-669d-21e7-7990-812488837582" /><meta name="guid" content="7e393f5b-669d-21e7-7990-812488837582" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.ConicalFace" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.ConicalFace" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.ConicalFace class" />
<meta name="Microsoft.Help.Keywords" content="ConicalFace class" />
<meta name="Microsoft.Help.Keywords" content="ConicalFace class, all members" />
<meta name="Microsoft.Help.Keywords" content="ConicalFace class" />
<meta name="Microsoft.Help.Keywords" content="ConicalFace class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.ConicalFace class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.ConicalFace" /><MSHelp:TOCTitle Title="ConicalFace Members" /><MSHelp:RLTitle Title="ConicalFace Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.ConicalFace" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBConicalFaceMembersTopic" /><MSHelp:Keyword Index="K" Term="ConicalFace class" /><MSHelp:Keyword Index="K" Term="ConicalFace class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.ConicalFace class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">ConicalFace Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ConicalFace">ConicalFace Class</a> <a href="#methodTableToggle" onclick="OpenSection(methodTableToggle)">Methods</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p /><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ConicalFace">ConicalFace</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.ComputeDerivatives(Autodesk.Revit.DB.UV)">ComputeDerivatives</a></td><td><div class="summary">Returns the first partial derivatives of the underlying surface at the specified point.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.ComputeNormal(Autodesk.Revit.DB.UV)">ComputeNormal</a></td><td><div class="summary">Returns the normal vector for the face at the given point.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.ComputeSecondDerivatives(Autodesk.Revit.DB.UV)">ComputeSecondDerivatives</a></td><td><div class="summary">Returns the second partial derivatives of the face at the specified point.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.APIObject.Dispose">Dispose</a></td><td><div class="summary">Causes the object to release immediately any resources it may be utilizing.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.GeometryObject.Equals(System.Object)">Equals</a></td><td><div class="summary"> Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.  </div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Evaluate(Autodesk.Revit.DB.UV)">Evaluate</a></td><td><div class="summary">Evaluates and returns the XYZ coordinates of a point at the indicated UV parameterization of the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.GetBoundingBox">GetBoundingBox</a></td><td><div class="summary">Returns the UV bounding box of the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.GetEdgesAsCurveLoops">GetEdgesAsCurveLoops</a></td><td><div class="summary">Returns a list of closed curve loops that correspond to the edge loops of the face. 
Curves in each curve loop correspond to individual edges.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.GeometryObject.GetHashCode">GetHashCode</a></td><td><div class="summary">
Gets the integer value of the geometry object as hash code
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.GetRegions">GetRegions</a></td><td><div class="summary">Gets the face regions (created, for example, by the Split Face command) of the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.GetSurface">GetSurface</a></td><td> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Intersect(Autodesk.Revit.DB.Curve)">Intersect(Curve)</a></td><td><div class="summary">Calculates the intersection of the specified curve with this face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Intersect(Autodesk.Revit.DB.Face)">Intersect(Face)</a></td><td><div class="summary">Calculates the intersection of the specified face with this face and returns the intersection results.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Intersect(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.IntersectionResultArray@)">Intersect(Curve, IntersectionResultArray<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">Calculates the intersection of the specified curve with this face and returns the intersection results.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Intersect(Autodesk.Revit.DB.Face,Autodesk.Revit.DB.Curve@)">Intersect(Face, Curve<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">Calculates the intersection of the specified face with this face and returns the intersection results.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.IsInside(Autodesk.Revit.DB.UV)">IsInside(UV)</a></td><td><div class="summary">Indicates whether the specified point is within this face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.IsInside(Autodesk.Revit.DB.UV,Autodesk.Revit.DB.IntersectionResult@)">IsInside(UV, IntersectionResult<span class="languageSpecificText"><span class="cpp">%</span></span>)</a></td><td><div class="summary">Indicates whether the specified point is within this face and outputs additional information about the point location.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Project(Autodesk.Revit.DB.XYZ)">Project</a></td><td><div class="summary">Projects the specified point on the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Triangulate">Triangulate<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Returns a triangular mesh approximation to the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Face.Triangulate(System.Double)">Triangulate(Double)</a></td><td><div class="summary">Returns a triangular mesh approximation to the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.Area">Area</a></td><td><div class="summary">The area of this face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.ConicalFace.Axis">Axis</a></td><td><div class="summary">Axis of the surface.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.EdgeLoops">EdgeLoops</a></td><td><div class="summary">A collection of edge loops.  Each edge loop represents one of the closed boundaries of the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.GraphicsStyleId">GraphicsStyleId</a></td><td><div class="summary">The ElementId of the GeometryObject's GraphicsStyle</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.ConicalFace.HalfAngle">HalfAngle</a></td><td><div class="summary">Half angle of the surface.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.HasRegions">HasRegions</a></td><td><div class="summary">Identifies if the face contains regions (which can be created, for example, by the Split Face command).</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.IsCyclic(System.Int32)">IsCyclic</a></td><td><div class="summary">Indicates whether the underlying surface is periodic in the specified parametric direction.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.IsElementGeometry">IsElementGeometry</a></td><td><div class="summary">Indicates whether this geometry is obtained directly from an Element.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.APIObject.IsReadOnly">IsReadOnly</a></td><td><div class="summary">Identifies if the object is read-only or modifiable.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.IsTwoSided">IsTwoSided</a></td><td><div class="summary">Determines if a face is two-sided (degenerate).</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.MaterialElementId">MaterialElementId</a></td><td><div class="summary">The element ID of the material from which this face is composed.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.OrientationMatchesSurfaceOrientation">OrientationMatchesSurfaceOrientation</a></td><td> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.ConicalFace.Origin">Origin</a></td><td><div class="summary">Origin of the surface.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.Period(System.Int32)">Period</a></td><td><div class="summary">The period of the underlying surface in the specified parametric direction.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.ConicalFace.Radius(System.Int32)">Radius</a></td><td><div class="summary">Radii of the surface.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Face.Reference">Reference</a></td><td><div class="summary">Returns a stable reference to the face.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Face">Face</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.GeometryObject.Visibility">Visibility</a></td><td><div class="summary">The visibility.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.GeometryObject">GeometryObject</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ConicalFace">ConicalFace Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>