<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BuiltInFailures.RebarFailures Properties</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BuiltInFailures.RebarFailures class, properties" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="80dea05d-696d-6b1f-d838-75e5c8f2184f" /><meta name="guid" content="80dea05d-696d-6b1f-d838-75e5c8f2184f" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="Properties.T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RebarFailures class, properties" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RebarFailures class, properties" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="Properties.T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures" /><MSHelp:TOCTitle Title="BuiltInFailures.RebarFailures Properties" /><MSHelp:RLTitle Title="BuiltInFailures.RebarFailures Properties (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="Properties.T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBuiltInFailuresRebarFailuresPropertiesTopic" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.RebarFailures class, properties" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarFailures Properties</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarFailures Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarFailures</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.BarDiameterTooLarge">BarDiameterTooLarge</a></td><td><div class="summary">
   Rebar Bar Diameter is too large.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.BarTypeDoesNotAllowHooksOfCurrentShape">BarTypeDoesNotAllowHooksOfCurrentShape</a></td><td><div class="summary">
   You have selected a Bar Type which does not allow the Hooks used by the current shape.  Please select a different Shape / Bar Type combination,  or change the Hook permissions for the desired Bar Type (see Hook Lengths under Rebar Bar properties).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.BendDiameterTooLarge">BendDiameterTooLarge</a></td><td><div class="summary">
   Rebar Bend Diameter is too large.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.BendDiameterTooSmall">BendDiameterTooSmall</a></td><td><div class="summary">
   Rebar Bend Diameter is too small.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CannotKeepVariabilityOfRebarInGroup">CannotKeepVariabilityOfRebarInGroup</a></td><td><div class="summary">
   Modifications to the rebar set might cause it to revert to a uniform distribution. This can occur for layout changes as well as modifications to the geometry.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CannotPlaceRebar">CannotPlaceRebar</a></td><td><div class="summary">
   Can't find a host for Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CannotPlaceRebarWarn">CannotPlaceRebarWarn</a></td><td><div class="summary">
   Can't find a host for Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CannotSolveRebarShapeUsingDataFromDimension">CannotSolveRebarShapeUsingDataFromDimension</a></td><td><div class="summary">
   Cannot solve rebar shape using the current constraints.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CannotSolveRebarWithDelayedConstraints">CannotSolveRebarWithDelayedConstraints</a></td><td><div class="summary">
   There are rebar handles with invalid selected targets to constrain. The bar preview corresponds to latest valid constraints.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CantMakeFillets">CantMakeFillets</a></td><td><div class="summary">
   The bar cannot be bent in that shape. Check the bending diameter and the bar type.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.ChangeUnitsFormatWarn">ChangeUnitsFormatWarn</a></td><td><div class="summary">
   The modification of the unit will cause the change of the Reinforcement rounding format. Do you want to continue?
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.ClearPresentationForAllBarsInRebarSet">ClearPresentationForAllBarsInRebarSet</a></td><td><div class="summary">
   All Bars in a Free Form Rebar Set have been hidden.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.CoverTooLong">CoverTooLong</a></td><td><div class="summary">
   Rebar Cover length is too large for host thickness.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.DelayedConstraintForHandle">DelayedConstraintForHandle</a></td><td><div class="summary">
   The selected constraint targets do not satisfy a valid constraint. The rebar preview corresponds to latest valid rebar constraints.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.HideAllBarsInRebarSet">HideAllBarsInRebarSet</a></td><td><div class="summary">
   All Bars in Rebar Set have been hidden.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.HostTopologyChange">HostTopologyChange</a></td><td><div class="summary">
   A reinforced host has undergone a major change. The reinforcement must be removed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.IncompleteShape">IncompleteShape</a></td><td><div class="summary">
   Rebar Shape [Family Name] is not fully defined and cannot be loaded into the project.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.InvalidRebarHost">InvalidRebarHost</a></td><td><div class="summary">
   Rebar can be placed only in Concrete Structural elements.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.InvalidRebarHostFamilyCanHostRebarParam">InvalidRebarHostFamilyCanHostRebarParam</a></td><td><div class="summary">
   Rebar can't be placed in this Generic Model element because rebar hosting is disabled in the family [Name].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.InvalidRebarHostNonConcrete">InvalidRebarHostNonConcrete</a></td><td><div class="summary">
   Rebar can't be placed in a structural family unless its [Material Type] is [Concrete].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.InvalidRebarHostNonStructural">InvalidRebarHostNonStructural</a></td><td><div class="summary">
   Rebar can't be placed in a non-structural element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.InvalidRebarHostWrongCategory">InvalidRebarHostWrongCategory</a></td><td><div class="summary">
   Rebar can't be placed in a family of category [Name].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.Inverted3dShape">Inverted3dShape</a></td><td><div class="summary">
   The Rebar Shape XX cannot be inverted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.MaxHookExtensionMultiplierWarn">MaxHookExtensionMultiplierWarn</a></td><td><div class="summary">
   The allowable range of values for the Rebar Hook Extension Multiplier is from 0.01 to 99.0.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.MissingCurrentConstraintForHandle">MissingCurrentConstraintForHandle</a></td><td><div class="summary">
   The current handle has no constraint. Please select a valid target to apply a new constraint.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.NoRebarSelected">NoRebarSelected</a></td><td><div class="summary">
   At least one Rebar should be selected.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.NoSurfPatternOnRebar">NoSurfPatternOnRebar</a></td><td><div class="summary">
   Rebar elements do not support surface patterns. The surface pattern associated with this material will not be displayed on the indicated Rebar Type.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.NoVisibleRebarHandle">NoVisibleRebarHandle</a></td><td><div class="summary">
   Editing of the constraints for the selected rebar with free form geometry is not available. However, the default automatic constraints may still work.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.NoVisibleTargetsForCurrentConstraint">NoVisibleTargetsForCurrentConstraint</a></td><td><div class="summary">
   There are no visible constraint targets in the current view. Please switch to another view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.OutOfPlaneBendDiameterTooSmall">OutOfPlaneBendDiameterTooSmall</a></td><td><div class="summary">
   The Out of Plane Bend Diameter for Rebar Shape XX is too small for Rebar Bar Type YY.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.OutSideOfHost">OutSideOfHost</a></td><td><div class="summary">
   Rebar is placed completely outside of its host.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.PathShapeFailure">PathShapeFailure</a></td><td><div class="summary">
   Can't solve Rebar Shape in Path Reinforcement.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarArrayTooShort">RebarArrayTooShort</a></td><td><div class="summary">
   Rebar Set can't have coincident Bars.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarBendRadiusTooBig">RebarBendRadiusTooBig</a></td><td><div class="summary">
   Rebar Bend Radius is too big. Ignoring bend.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarBendRadiusTooBigWarn">RebarBendRadiusTooBigWarn</a></td><td><div class="summary">
   Rebar Bend Radius is too big. Ignoring bend.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarConstraintWarning">RebarConstraintWarning</a></td><td><div class="summary">
   Structural rebar have automatic constraints that may conflict with dimensional constraints. Using dimensional
   constraints with structural rebar is not recommended and should be avoided.\nGrouped structural rebar is the
   only exception to this recommendation, since the automatic constraints are removed on grouped rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarContainerOutSideOfHostWarning">RebarContainerOutSideOfHostWarning</a></td><td><div class="summary">
   Rebar Container is placed completely outside of its host.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarHooksDontMatchShape">RebarHooksDontMatchShape</a></td><td><div class="summary">
   The Rebar's hooks do not match its Rebar Shape.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarIllegalBarType">RebarIllegalBarType</a></td><td><div class="summary">
   There is Structural Rebar present in the project that no longer meet the criteria defined in Allowable Rebar Bar
   types parameter. Please review all existing Structural Rebar created with this Shape.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarNoConstraints">RebarNoConstraints</a></td><td><div class="summary">
   The constraints for the rebar with free form geometry are not set or modifications have caused the automatic constraints to be deleted.
   You can use Edit Constraints to assign new bar constraints.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarNoMatchingHooks">RebarNoMatchingHooks</a></td><td><div class="summary">
   The Rebar Shape '[Family Name]' has no matching hooks.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarShapeFailure">RebarShapeFailure</a></td><td><div class="summary">
   Can't solve Rebar Shape.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarSpacingTooSmall">RebarSpacingTooSmall</a></td><td><div class="summary">
   Bar Spacing is too small.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarTooShortImperial">RebarTooShortImperial</a></td><td><div class="summary">
   The minimum length of rebar shape is 1 inch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.RebarTooShortMetric">RebarTooShortMetric</a></td><td><div class="summary">
   The minimum length of rebar shape is 25 mm.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.SketchDimensionsRemoved">SketchDimensionsRemoved</a></td><td><div class="summary">
   The sketch dimensions, that were used to create the sketch, have been removed from the completed rebar shape definition.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.SketchDimsBWFRemoved">SketchDimsBWFRemoved</a></td><td><div class="summary">
   The sketch dimensions, that were used to create the sketch, have been removed from the completed bend profile definition.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.SketchFreeFormSet">SketchFreeFormSet</a></td><td><div class="summary">
   Sketching of a free form set produces only a single bar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.SketchNonPlanarFreeForm">SketchNonPlanarFreeForm</a></td><td><div class="summary">
   The selected free form rebar is not planar. Sketching it will discard the current geometry.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.StandardHookBendDiameterTooLarge">StandardHookBendDiameterTooLarge</a></td><td><div class="summary">
   Rebar Standard Hook Bend Diameter is too large.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.StandardHookBendDiameterTooSmall">StandardHookBendDiameterTooSmall</a></td><td><div class="summary">
   Rebar Standard Hook Bend Diameter is too small.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.TooLargeNumberOfBars">TooLargeNumberOfBars</a></td><td><div class="summary">
   Rebar Set must contain at most 1002 bar locations.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.TooSmallNumberOfBars">TooSmallNumberOfBars</a></td><td><div class="summary">
   Rebar Set must contain at least two bar locations.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RebarFailures.TrySmallerBarType">TrySmallerBarType</a></td><td><div class="summary">
   Rebar Bend Diameter is too large. Try a smaller Bar Type.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RebarFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RebarFailures Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>