<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BuiltInFailures.EditingFailures Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BuiltInFailures.EditingFailures class" /><meta name="System.Keywords" content="BuiltInFailures.EditingFailures class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.EditingFailures class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="900bfd40-b8db-86b8-009f-d7dee39471b6" /><meta name="guid" content="900bfd40-b8db-86b8-009f-d7dee39471b6" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.EditingFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.EditingFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.EditingFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.EditingFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.EditingFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.EditingFailures class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures" /><MSHelp:TOCTitle Title="BuiltInFailures.EditingFailures Members" /><MSHelp:RLTitle Title="BuiltInFailures.EditingFailures Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBuiltInFailuresEditingFailuresMembersTopic" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.EditingFailures class" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.EditingFailures class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.BuiltInFailures.EditingFailures class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>EditingFailures Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>EditingFailures Class</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p><div class="summary">Provides a container of all Revit built-in FailureDefinitionId instances.</div></p><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>EditingFailures</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.AllInvisibleInPlanViewWarn">AllInvisibleInPlanViewWarn</a></td><td><div class="summary">
   None of the created elements are visible in [View Type] View. You may want to check the active view, its Parameters, and Visibility settings, as well as any Plan Regions and their settings.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.AllInvisibleInViewWarn">AllInvisibleInViewWarn</a></td><td><div class="summary">
   None of the created elements are visible in [View Type] View. You may want to check the active view, its Parameters, and Visibility settings.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.BorrowElementsAtRisk">BorrowElementsAtRisk</a></td><td><div class="summary">
   Can't obtain permission to edit the element:  The Central Model is inaccessible.  You can check out worksets at risk, but consider carefully!
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotBorrowBusyContention">CannotBorrowBusyContention</a></td><td><div class="summary">
   Can't obtain permission to edit the element.  The Central Model is busy.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotCheckoutWorksets">CannotCheckoutWorksets</a></td><td><div class="summary">
   Can't make workset editable. User '[Borrowers]' has already checked it out.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotDeleteEditedElement">CannotDeleteEditedElement</a></td><td><div class="summary">
   Can't delete element that is being edited.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotDeleteEditedElementError">CannotDeleteEditedElementError</a></td><td><div class="summary">
   Can't delete element that is being edited.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotDeletePredefinedFamilyElement">CannotDeletePredefinedFamilyElement</a></td><td><div class="summary">
   Element is a built-in part of the family definition and cannot be deleted or added to groups.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotDrawInCurrentView">CannotDrawInCurrentView</a></td><td><div class="summary">
   Can't draw because Work Plane is at a very sharp angle in this view. Go to another view or redefine the Work Plane.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotDuplicateType">CannotDuplicateType</a></td><td><div class="summary">
   Cannot Duplicate Type
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotEditDeletedElements">CannotEditDeletedElements</a></td><td><div class="summary">
   Can't edit the element.  It was deleted in the Central Model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotEditDeletedWorkset">CannotEditDeletedWorkset</a></td><td><div class="summary">
   This action has caused deletion of non-editable Workset ' [Name] '.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotEditEditingElements">CannotEditEditingElements</a></td><td><div class="summary">
   Can't obtain permission to edit the element:  The Central Model is inaccessible and another user is editing the element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotEditElements">CannotEditElements</a></td><td><div class="summary">
   Workset is editable, but you can't edit the element until '[Borrowers]' resaves the element to central and relinquishes it and you Reload Latest.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotEditRenamedWorkset">CannotEditRenamedWorkset</a></td><td><div class="summary">
   Can't edit workset ' [Name] '.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMirrorInView">CannotMirrorInView</a></td><td><div class="summary">
   Must specify Work Plane to mirror in a 3d View.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveElement">CannotMoveElement</a></td><td><div class="summary">
   Can't move element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveElementWarn">CannotMoveElementWarn</a></td><td><div class="summary">
   Can't move element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveElementWithoutWorkplane">CannotMoveElementWithoutWorkplane</a></td><td><div class="summary">
   Element(s) need a workplane to be moved in. There's no workplane defined in this view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveHereInViewError">CannotMoveHereInViewError</a></td><td><div class="summary">
   Can't move here at this view angle. Set another Work Plane or adjust the view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveInView">CannotMoveInView</a></td><td><div class="summary">
   Can't move element because the move plane is seen at a very sharp angle in this View
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveInViewError">CannotMoveInViewError</a></td><td><div class="summary">
   Can't move element because the move plane is seen at a very sharp angle in this View
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveLocked">CannotMoveLocked</a></td><td><div class="summary">
   Can't move pinned element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotMoveTogether">CannotMoveTogether</a></td><td><div class="summary">
   Can't move these elements at the same time. One of them is restricted to moving in one direction while the other is restricted to moving in a conflicting direction.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotPickHereInCurrentView">CannotPickHereInCurrentView</a></td><td><div class="summary">
   Can't pick here at this view angle. Set another Work Plane or adjust the view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotRotateLocked">CannotRotateLocked</a></td><td><div class="summary">
   Can't rotate pinned element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.CannotScaleInView">CannotScaleInView</a></td><td><div class="summary">
   Can't scale because Move Plane is at a very sharp angle in this view. Change view angle or go to another view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.DeletedRequestedWarn">DeletedRequestedWarn</a></td><td><div class="summary">
   You have deleted elements that other users requested.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.DeleteElementsError">DeleteElementsError</a></td><td><div class="summary">
   [Description]
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.DeleteElementsWarn">DeleteElementsWarn</a></td><td><div class="summary">
   [Description]
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.DeletePreventedByGroup">DeletePreventedByGroup</a></td><td><div class="summary">
   Grouped elements can only be deleted when the group is being edited. To delete a member select the group and then click the Edit Group button on the toolbar, then delete the member.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementNotEditable">ElementNotEditable</a></td><td><div class="summary">
   One or more elements are not editable.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementReversed">ElementReversed</a></td><td><div class="summary">
   Element is reversed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementsDeleted">ElementsDeleted</a></td><td><div class="summary">
   Elements were deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementsDeletedPastedToKeep">ElementsDeletedPastedToKeep</a></td><td><div class="summary">
   Elements were deleted.  Use Edit Pasted Elements to keep them.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementsNotInPlane">ElementsNotInPlane</a></td><td><div class="summary">
   Elements don't lie on the same plane.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ElementsWillBeDeleted">ElementsWillBeDeleted</a></td><td><div class="summary">
   Elements in [Design Option] will be deleted
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ExtendToOtherCrash">ExtendToOtherCrash</a></td><td><div class="summary">
   Can't keep [Type Name] extended to [Type Name].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ExtendToOtherWarn">ExtendToOtherWarn</a></td><td><div class="summary">
   Can't keep [Type Name] extended to [Type Name].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.GeneratedByMassing">GeneratedByMassing</a></td><td><div class="summary">
   Selected element(s) produced from Massing shape. Once deleted, the selected element(s) will not be regenerated
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.HaveNoPermissionToEdit">HaveNoPermissionToEdit</a></td><td><div class="summary">
   You do not have permission to edit the element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.HiddenBeamsEditingWarning">HiddenBeamsEditingWarning</a></td><td><div class="summary">
   The beam join being modified contains beam that are not visible.  Geometry of visible beams may be affected by hidden beams.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.InvalidArrayObject">InvalidArrayObject</a></td><td><div class="summary">
   Some or all of the selected objects can't be created in an Array (for example, a Camera object for a 3D View).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.InvalidElemsInSelection">InvalidElemsInSelection</a></td><td><div class="summary">
   Can't scale elements together.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.LockedDeleted">LockedDeleted</a></td><td><div class="summary">
   Pinned objects deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.LockedDeletedWarn">LockedDeletedWarn</a></td><td><div class="summary">
   Pinned objects deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.MirrorProjectSuccess">MirrorProjectSuccess</a></td><td><div class="summary">
   [Action] command has successfully processed [Number] elements
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.NElementsDeleted">NElementsDeleted</a></td><td><div class="summary">
   [Number] elements were deleted
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.NElementsWrongPosition">NElementsWrongPosition</a></td><td><div class="summary">
   Review [Number] elements for correct position and shape
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.NoRotateMirrorZ">NoRotateMirrorZ</a></td><td><div class="summary">
   Element cannot be mirrored or rotated in a manner that changes its angle relative to the ground.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.NoRotateMirrorZError">NoRotateMirrorZError</a></td><td><div class="summary">
   Element cannot be mirrored or rotated in a manner that changes its angle relative to the ground.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.OutOfDateElements">OutOfDateElements</a></td><td><div class="summary">
   Workset is editable, but you must Reload Latest before editing the element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.OwnedByOther">OwnedByOther</a></td><td><div class="summary">
   Can't edit the element until '[Partition Name]' resaves the element to central and relinquishes it and you Reload Latest.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.OwnElementsOutOfDate">OwnElementsOutOfDate</a></td><td><div class="summary">
   You now own the element, but your file is out of date.  You must Reload Latest before editing the element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.PinnedObjectHostDeleted">PinnedObjectHostDeleted</a></td><td><div class="summary">
   Some pinned objects were deleted because their parent or host object was deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.PinnedObjectNotDeleted">PinnedObjectNotDeleted</a></td><td><div class="summary">
   Pinned objects were not deleted. To delete them, unpin them before using delete.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.PinnedObjectSomeDeleted">PinnedObjectSomeDeleted</a></td><td><div class="summary">
   Some pinned objects were deleted while others were not.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.PressShowToSee">PressShowToSee</a></td><td><div class="summary">
   Press Show to see the element(s); then Ignore or Cancel
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ReloadBeforeMakeEditable">ReloadBeforeMakeEditable</a></td><td><div class="summary">
   You must Reload Latest before editing the element.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.ReloadNoGood">ReloadNoGood</a></td><td><div class="summary">
   You must Reload Latest before editing the element, but the Central Model is inaccessible or being accessed by another user.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.SourceInEditMode">SourceInEditMode</a></td><td><div class="summary">
   Can't transfer project standards while source document is in an edit mode.  Please exit all edit modes(In-Place
   Family Edit Mode, Group Edit Mode, Sketch Edit Mode, etc.) and try again.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.TargetInEditMode">TargetInEditMode</a></td><td><div class="summary">
   Can't transfer project standards while target document is in an edit mode.  Please exit all edit modes(In-Place
   Family Edit Mode, Group Edit Mode, Sketch Edit Mode, etc.) and try again.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.TemporaryChangesOutOfDate">TemporaryChangesOutOfDate</a></td><td><div class="summary">
   You must Reload Latest before editing the element.  Changes will be temporary, and will not be saved.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.TemporaryChangesTransparentPermissions">TemporaryChangesTransparentPermissions</a></td><td><div class="summary">
   Permission to edit the element cannot be obtained.  Changes will be temporary, and will not be saved.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.UnableFilletSpecifiedRadius">UnableFilletSpecifiedRadius</a></td><td><div class="summary">
   Unable to create Fillet with the specified radius.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.UnableToMakeSourceWorksetEditable">UnableToMakeSourceWorksetEditable</a></td><td><div class="summary">
   Unable to make the necessary Workset ([Name]) editable in the Linked File in order to change the Shared Coordinates.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.UnableToTransformElement">UnableToTransformElement</a></td><td><div class="summary">
   Attempted an invalid element rotate, mirror, or move.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.UnableToTransformElementError">UnableToTransformElementError</a></td><td><div class="summary">
   Attempted an invalid element rotate, mirror, or move.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.EditingFailures.WorksetHasChangedInCentralFile">WorksetHasChangedInCentralFile</a></td><td><div class="summary">
   This workset has changed in the Central Model.  Please Reload Latest before making this workset editable.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.EditingFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>EditingFailures Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>