<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BuiltInFailures.RoomFailures Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BuiltInFailures.RoomFailures class" /><meta name="System.Keywords" content="BuiltInFailures.RoomFailures class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.RoomFailures class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="b1d6acda-da68-b7e2-f3e0-dafe1ea9fcdf" /><meta name="guid" content="b1d6acda-da68-b7e2-f3e0-dafe1ea9fcdf" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.RoomFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RoomFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RoomFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RoomFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.RoomFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.RoomFailures class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures" /><MSHelp:TOCTitle Title="BuiltInFailures.RoomFailures Members" /><MSHelp:RLTitle Title="BuiltInFailures.RoomFailures Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBuiltInFailuresRoomFailuresMembersTopic" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.RoomFailures class" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.RoomFailures class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.BuiltInFailures.RoomFailures class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RoomFailures Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RoomFailures Class</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p><div class="summary">Provides a container of all Revit built-in FailureDefinitionId instances.</div></p><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RoomFailures</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.AreaTagBadViewType">AreaTagBadViewType</a></td><td><div class="summary">
   Can't Copy Area Tags. The target view doesn't have the same Area Scheme as the original view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.AreaUnplaceWarning">AreaUnplaceWarning</a></td><td><div class="summary">
   An Area was deleted from all model views but still remains in this project. \n The area can be removed from any schedule or placed back in the model using the Area command.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.CannotMakeRoomsGeometry">CannotMakeRoomsGeometry</a></td><td><div class="summary">
   Could not create geometry for [Room].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.ExtensionsOverlapWarning">ExtensionsOverlapWarning</a></td><td><div class="summary">
   Vertical Extensions on these Walls overlap. This can cause undesirable Joins. Try starting with no overlap and extend the Walls toward one another.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.InvalidReflectivityPercentage">InvalidReflectivityPercentage</a></td><td><div class="summary">
   The value for Reflectivity must be between 0 and 1.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.InvisibleRoomBoundElemement">InvisibleRoomBoundElemement</a></td><td><div class="summary">
   [Room] Bounding element is invisible in current view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictBoundariesVaryMainAddToOptionSet">OptionConflictBoundariesVaryMainAddToOptionSet</a></td><td><div class="summary">
   Option Conflict between Rooms.\nRoom boundary in the Main Model differs from the apparent boundary in view '[View Name]'.\nTo resolve, select the Main Model Room and use the Add to Design Option Set command.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictBoundariesVaryMainSeparate">OptionConflictBoundariesVaryMainSeparate</a></td><td><div class="summary">
   Option Conflict between Rooms.\nRoom boundary in the Main Model differs from the apparent boundary in view '[View Name]'.\nTo resolve, divide space with Room Separation Lines in the Main Model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictBoundariesVaryOptionSeparate">OptionConflictBoundariesVaryOptionSeparate</a></td><td><div class="summary">
   Option Conflict between Rooms.\nRoom boundary differs from the apparent boundary in view '[View Name]'.\nTo resolve, divide space with Room Separation Lines in the Main Model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictInLinkBoundariesVaryMainAddToOptionSet">OptionConflictInLinkBoundariesVaryMainAddToOptionSet</a></td><td><div class="summary">
   Option conflict between rooms in the Revit link '[Link Instance Name]'.\nThe room boundary in the main model of the Revit link differs from the apparent boundary in the linked view '[View Name from Link]'.\nTo resolve the issue, open the Revit link file for editing, select the main model room, and use the Add to Design Option Set tool.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictInLinkBoundariesVaryMainSeparate">OptionConflictInLinkBoundariesVaryMainSeparate</a></td><td><div class="summary">
   Option conflict between rooms in the Revit link '[Link Instance Name]'.\nThe room boundary in the main model of the Revit link differs from the apparent boundary in the linked view '[View Name from Link]'.\nTo resolve the issue, open the Revit link file for editing, and use room separation lines to divide the space in the main model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictInLinkBoundariesVaryOptionSeparate">OptionConflictInLinkBoundariesVaryOptionSeparate</a></td><td><div class="summary">
   Option conflict between rooms in the Revit link '[Link Instance Name]'.\nThe room boundary differs from the apparent boundary in the linked view '[View Name from Link]'.\nTo resolve the issue, open the Revit link file for editing, and use room separation lines to divide the space in the main model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictInLinkRoomOverlapMain">OptionConflictInLinkRoomOverlapMain</a></td><td><div class="summary">
   Option conflict between rooms in the Revit link '[Link Instance Name]'.\nThe room in the Revit link's option '[Option Name in Link]' overlaps a room in the main model.\nTo resolve the issue, open the Revit link file for editing, select the main model room, and use the Add to Design Option Set tool.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictInLinkRoomOverlapOption">OptionConflictInLinkRoomOverlapOption</a></td><td><div class="summary">
   Option conflict between rooms in the Revit link '[Link Instance Name]'.\nA room in the Revit link's option '[Option #1 Name in Link]' overlaps a room in the Revit link's option '[Option #2 Name in Link]'.\nTo resolve the issue, open the Revit link file for editing, and delete the duplicate room or use room separation lines to divide the space in the main model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictRoomOverlapMain">OptionConflictRoomOverlapMain</a></td><td><div class="summary">
   Option Conflict between Rooms.\nRoom in Option '[Option Name]' overlaps Room in the Main Model.\nTo resolve, select the Main Model Room and use the Add to Design Option Set command.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.OptionConflictRoomOverlapOption">OptionConflictRoomOverlapOption</a></td><td><div class="summary">
   Option Conflict between Rooms.\nRoom in Option '[Option Name]' overlaps Room in Option '[Option Name]'.\nTo resolve, delete the duplicate Room or divide space with Room Separation Lines in the Main Model.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomBaseAboveComputationHeight">RoomBaseAboveComputationHeight</a></td><td><div class="summary">
   [RoomBase]'s lower offset is above the Computation Height
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomBelowCompHeight">RoomBelowCompHeight</a></td><td><div class="summary">
   [Room] Volume is being calculated above the Upper Limit of this [Room]. Change the Upper Limit and Offset or change the height of volume calculations.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomBoundaryMisalignment">RoomBoundaryMisalignment</a></td><td><div class="summary">
   [Room] bounding element might be misaligned.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomHeightNegative">RoomHeightNegative</a></td><td><div class="summary">
   [Room] must have a height greater than 0.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomLevelElevs">RoomLevelElevs</a></td><td><div class="summary">
   A [Room]s Upper Limit must be above its Base Level.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomNotEnclosed">RoomNotEnclosed</a></td><td><div class="summary">
   [Room] is not in a properly enclosed region
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomNotEnclosedAreas">RoomNotEnclosedAreas</a></td><td><div class="summary">
   [Room] is not in a properly enclosed region
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomNotEnclosedRooms">RoomNotEnclosedRooms</a></td><td><div class="summary">
   [Room] is not in a properly enclosed region
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomNotEnclosedSpaces">RoomNotEnclosedSpaces</a></td><td><div class="summary">
   [Room] is not in a properly enclosed region
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsCreatedAutomatically">RoomsCreatedAutomatically</a></td><td><div class="summary">
   [Room] [Room] created automatically.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsFailed">RoomsFailed</a></td><td><div class="summary">
   [Room] computations only succeeded without considering the following elements.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsInSameRegion">RoomsInSameRegion</a></td><td><div class="summary">
   Multiple [Room] are in the same enclosed region.  The correct area and perimeter will be assigned to one [Room] and the others will display     "Redundant [Room]."  You should separate the regions, delete the extra [Room], or move them into different regions.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsInSameRegionAreas">RoomsInSameRegionAreas</a></td><td><div class="summary">
   Multiple [Room] are in the same enclosed region.  The correct area and perimeter will be assigned to one [Room] and the others will display     "Redundant [Room]."  You should separate the regions, delete the extra [Room], or move them into different regions.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsInSameRegionRooms">RoomsInSameRegionRooms</a></td><td><div class="summary">
   Multiple [Room] are in the same enclosed region.  The correct area and perimeter will be assigned to one [Room] and the others will display     "Redundant [Room]."  You should separate the regions, delete the extra [Room], or move them into different regions.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsInSameRegionSpaces">RoomsInSameRegionSpaces</a></td><td><div class="summary">
   Multiple [Room] are in the same enclosed region.  The correct area and perimeter will be assigned to one [Room] and the others will display     "Redundant [Room]."  You should separate the regions, delete the extra [Room], or move them into different regions.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsOverlapInHeight">RoomsOverlapInHeight</a></td><td><div class="summary">
   [Room] volumes overlap. Adjust the Upper Limit and Limit Offset properties of the [rooms].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomsReallyFailed">RoomsReallyFailed</a></td><td><div class="summary">
   [Room] computations failed. Try to modify the following elements.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagBadViewType">RoomTagBadViewType</a></td><td><div class="summary">
   [Room] Tags can only be placed in Floor Plan, Reflected Ceiling Plan and Section Views.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagDeleted">RoomTagDeleted</a></td><td><div class="summary">
   A [Room] Tag was deleted, but the corresponding [Room] still exists.  You can place another tag for the [Room] using the [Room] Tag tool or select the [Room] and delete it.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagNotInRoom">RoomTagNotInRoom</a></td><td><div class="summary">
   [Room] Tag is outside of its [Room].  Enable Leader or move [Room] Tag within its [Room].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagNotInRoomToArea">RoomTagNotInRoomToArea</a></td><td><div class="summary">
   [Room] Tag is outside of its [Room].  Enable Leader or move [Room] Tag within its [Room].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagNotInRoomToRoom">RoomTagNotInRoomToRoom</a></td><td><div class="summary">
   [Room] Tag is outside of its [Room].  Enable Leader or move [Room] Tag within its [Room].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagNotInRoomToSpace">RoomTagNotInRoomToSpace</a></td><td><div class="summary">
   [Room] Tag is outside of its [Room].  Enable Leader or move [Room] Tag within its [Room].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTagVolumeNotComputed">RoomTagVolumeNotComputed</a></td><td><div class="summary">
   [Room] Tag is displaying volume that can't be computed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomTooShort">RoomTooShort</a></td><td><div class="summary">
   [Room] is very short. If this is not intended, change its Upper Limit and Offset.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.RoomUnplaceWarning">RoomUnplaceWarning</a></td><td><div class="summary">
   A Room was deleted from all model views but still remains in this project. \n The room can be removed from any schedule or placed back in the model using the Room command.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.ShowRoomBoundingElements">ShowRoomBoundingElements</a></td><td><div class="summary">
   [Room] Bounding elements are highlighted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.RoomFailures.SpaceUnplaceWarning">SpaceUnplaceWarning</a></td><td><div class="summary">
   A Space was deleted from all model views but still remains in this project. \n The Space can be removed from any schedule or placed back in the model using the Space command.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.RoomFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RoomFailures Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>