<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>CreateSketchedRun Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="CreateSketchedRun method" /><meta name="System.Keywords" content="StairsRun.CreateSketchedRun method" /><meta name="Description" content="Creates a sketched run in the project document by providing a group of boundary curves and riser curves." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB.Architecture" /><meta name="file" content="bb782d95-4792-8335-401c-97170542b96b" /><meta name="guid" content="bb782d95-4792-8335-401c-97170542b96b" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,System.Double,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve})" />
<meta name="Microsoft.Help.TocParent" content="Methods.T:Autodesk.Revit.DB.Architecture.StairsRun" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="CreateSketchedRun method" />
<meta name="Microsoft.Help.Keywords" content="StairsRun.CreateSketchedRun method" />
<meta name="Microsoft.Help.Keywords" content="CreateSketchedRun method" />
<meta name="Microsoft.Help.Keywords" content="StairsRun.CreateSketchedRun method" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,System.Double,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve})" /><MSHelp:TOCTitle Title="CreateSketchedRun Method " /><MSHelp:RLTitle Title="StairsRun.CreateSketchedRun Method  (Autodesk.Revit.DB.Architecture)" /><MSHelp:Keyword Index="A" Term="M:Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,System.Double,System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve},System.Collections.Generic.IList{Autodesk.Revit.DB.Curve})" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBArchitectureStairsRunClassCreateSketchedRunTopic" /><MSHelp:Keyword Index="K" Term="CreateSketchedRun method" /><MSHelp:Keyword Index="K" Term="StairsRun.CreateSketchedRun method" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.Architecture.StairsRun.CreateSketchedRun" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Creates a sketched run in the project document by providing a group of boundary curves and riser curves." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">StairsRun<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>CreateSketchedRun Method </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">
   Creates a sketched run in the project document by providing a group of boundary curves and riser curves.
</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Architecture">Autodesk.Revit.DB.Architecture</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<br /><b>Since:</b> 
   2013
<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a> <span class="identifier">CreateSketchedRun</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a> <span class="parameter">document</span>,
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a> <span class="parameter">stairsId</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">baseElevation</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>&gt; <span class="parameter">boundaryCurves</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>&gt; <span class="parameter">riserCurves</span>,
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>&gt; <span class="parameter">stairsPath</span>
)</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CreateSketchedRun</span> ( _
	<span class="parameter">document</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>, _
	<span class="parameter">stairsId</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>, _
	<span class="parameter">baseElevation</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a>, _
	<span class="parameter">boundaryCurves</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>(<span class="keyword">Of</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>), _
	<span class="parameter">riserCurves</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>(<span class="keyword">Of</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>), _
	<span class="parameter">stairsPath</span> <span class="keyword">As</span> <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>(<span class="keyword">Of</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>) _
) <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a></pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve"><span class="keyword">public</span>:
<span class="keyword">static</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun</a>^ <span class="identifier">CreateSketchedRun</span>(
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Document</a>^ <span class="parameter">document</span>, 
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">ElementId</a>^ <span class="parameter">stairsId</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">double</a> <span class="parameter">baseElevation</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>^&gt;^ <span class="parameter">boundaryCurves</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>^&gt;^ <span class="parameter">riserCurves</span>, 
	<a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">IList</a>&lt;<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a>^&gt;^ <span class="parameter">stairsPath</span>
)</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="document"><dt><span class="parameter">document</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Document">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Document</a><br />
   The document.
</dd></dl><dl paramname="stairsId"><dt><span class="parameter">stairsId</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ElementId">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ElementId</a><br />
   The stairs that the new stairs run will belong to.
</dd></dl><dl paramname="baseElevation"><dt><span class="parameter">baseElevation</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>Double</a><br />
   Base elevation of the new stairs run. It has following restrictions:
   <ul><li>The base elevation is relative to the base elevation of the stairs.</li><li>The base elevation will be rounded automatically to a multiple of the riser height.</li></ul></dd></dl><dl paramname="boundaryCurves"><dt><span class="parameter">boundaryCurves</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">System.Collections.Generic<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>IList</a><span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="nu">(</span><span class="fs">&lt;'</span></span><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a><span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="nu">)</span><span class="fs">&gt;</span></span><br />
   The boundary curves of the new stairs run. The curves have following restriction:
   <ul><li>The curves should consist of bound Line or Arc curves only.</li><li>The curves should be a pair of curve chains(two sets of curves which connect end-to-end
   to form the left and right boundaries).</li><li>The left and right boundary chain curves should not connect to each other.</li><li>They can be single curves or multi-segmented curves(for example, straight lines and
   arcs connected).</li></ul></dd></dl><dl paramname="riserCurves"><dt><span class="parameter">riserCurves</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">System.Collections.Generic<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>IList</a><span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="nu">(</span><span class="fs">&lt;'</span></span><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a><span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="nu">)</span><span class="fs">&gt;</span></span><br />
   The riser curves of the new stairs run. The curves have following restriction:
   <ul><li>The curves should consist of bound Line or Arc curves only.</li><li>The curves should be able to make at least two curve chains.</li><li>The curves in each chain should connect between the left and right boundaries.</li></ul></dd></dl><dl paramname="stairsPath"><dt><span class="parameter">stairsPath</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/5y536ey6" target="_blank">System.Collections.Generic<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>IList</a><span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="nu">(</span><span class="fs">&lt;'</span></span><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Curve">Curve</a><span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="nu">)</span><span class="fs">&gt;</span></span><br />
   The stair path curves of the new stairs run. The curves have following restriction:
   <ul><li>The curves should consist of bound Line or Arc curves only.</li><li>The curves should be able to make one curve chain.</li><li>The curve chain should have intersection with all riser curve chains.</li><li>The curves should connect between the first and last riser chain curves.</li></ul></dd></dl></div><h4 class="subHeading">Return Value</h4>
   The new stairs run.
</div><h1 class="heading"><span onclick="ExpandCollapse(remarksToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(remarksToggle, event)" tabindex="0"><img id="remarksToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Remarks</span></h1><div id="remarksSection" class="section" name="collapseableSection" style="">
   The run type of the new stairs run will be determined by the specified stairs.
   The new stairs run and the document will be regenerated.
   This should be run from within an open transaction.
</div><h1 class="heading"><span onclick="ExpandCollapse(exceptionsToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exceptionsToggle, event)" tabindex="0"><img id="exceptionsToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Exceptions</span></h1><div id="exceptionsSection" class="section" name="collapseableSection" style=""><div class="tableSection"><table width="100%" cellspacing="2" cellpadding="5" frame="lhs"><tr><th class="exceptionNameColumn">Exception</th><th class="exceptionConditionColumn">Condition</th></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentException</a></td><td>
   The stairsId is not a valid stairs element.
   -or-
   The input boundaryCurves is empty.
   -or-
   The input riserCurves is empty.
   -or-
   The input stairsPath is empty.
   -or-
   The input boundaryCurves contains at least one curve which is not a bound Line or bound Arc
   and is not supported for this operation.
   -or-
   The input riserCurves contains at least one curve which is not a bound Line or bound Arc
   and is not supported for this operation.
   -or-
   The input stairsPath contains at least one curve which is not a bound Line or bound Arc
   and is not supported for this operation.
   -or-
   The riserCurves or boundaryCurves or stairsPath don't meet restrictions to create sketch run.
   -or-
   The boundaryCurves has invalid curve used as sketch boundary curve.
   -or-
   The riserCurves has invalid curve used as sketch riser curve.
   -or-
   The stairsPath has invalid curve used as sketch stairspath curve.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentNullException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentNullException</a></td><td>
   A non-optional argument was NULL
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ArgumentOutOfRangeException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ArgumentOutOfRangeException</a></td><td>
   The given value for baseElevation must be no more than 30000 feet in absolute value.
   -or-
   The baseElevation doesn't meet the restriction that bottom of run should not be lower than bottom of stairs.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.InvalidOperationException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>InvalidOperationException</a></td><td>
   The stairs element represented by stairsId is not in an active StairsEditScope.
   New components cannot be added to it.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationForbiddenException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationForbiddenException</a></td><td>
   The document is in failure mode: an operation has failed,
   and Revit requires the user to either cancel the operation
   or fix the problem (usually by deleting certain elements).
   -or-
   The document is being loaded, or is in the midst of another
   sensitive process.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.ModificationOutsideTransactionException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ModificationOutsideTransactionException</a></td><td>
   The document has no open transaction.
</td></tr><tr><td><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Exceptions.RegenerationFailedException">Autodesk.Revit.Exceptions<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>RegenerationFailedException</a></td><td>
   The boundaryCurves, riserCurves, stairsPath don't meet restrictions to generate sketch run.
</td></tr></table></div></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Architecture.StairsRun">StairsRun Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Architecture">Autodesk.Revit.DB.Architecture Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>