<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>FabricationPart Methods</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="FabricationPart class, methods" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="c5e451b2-aee9-c602-e3d0-873b452fa2e7" /><meta name="guid" content="c5e451b2-aee9-c602-e3d0-873b452fa2e7" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="Methods.T:Autodesk.Revit.DB.FabricationPart" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.FabricationPart" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="FabricationPart class, methods" />
<meta name="Microsoft.Help.Keywords" content="FabricationPart class, methods" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="Methods.T:Autodesk.Revit.DB.FabricationPart" /><MSHelp:TOCTitle Title="FabricationPart Methods" /><MSHelp:RLTitle Title="FabricationPart Methods (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="Methods.T:Autodesk.Revit.DB.FabricationPart" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBFabricationPartMethodsTopic" /><MSHelp:Keyword Index="K" Term="FabricationPart class, methods" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">FabricationPart Methods</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.FabricationPart">FabricationPart Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.FabricationPart">FabricationPart</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AddPartCustomData(System.Int32)">AddPartCustomData</a></td><td><div class="summary">
   Add custom data type to the fabrication part. The new data gets the default value defined by the fabrication configuration.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AdjustEndLength(Autodesk.Revit.DB.Connector,System.Double,System.Boolean)">AdjustEndLength</a></td><td><div class="summary">
   Adjusts the length for the specified connector.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AlignPartByConnector(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Double,Autodesk.Revit.DB.Fabrication.FabricationPartJustification,Autodesk.Revit.DB.Transform)">AlignPartByConnector</a></td><td><div class="summary">
   Align the part by its connector to a point and rotation in free space.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AlignPartByConnectors(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,System.Double)">AlignPartByConnectors</a></td><td><div class="summary">
   Moves fabrication part by one of its connectors and aligns it to another connector.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AlignPartByConnectorToConnector(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,System.Double,System.Double,Autodesk.Revit.DB.Fabrication.FabricationPartJustification)">AlignPartByConnectorToConnector</a></td><td><div class="summary">
   Align a part by its connector to another connector. This will replace the FabricationPart::AlignPartByConnectors method.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AlignPartByInsertionPoint(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Double,Autodesk.Revit.DB.Fabrication.FabricationPartJustification,Autodesk.Revit.DB.Transform)">AlignPartByInsertionPoint</a></td><td><div class="summary">
   Align the part by its insertion point to a point and rotation in free space.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.AlignPartByInsertionPointAndCutInToStraight(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,System.Double,System.Double,System.Boolean)">AlignPartByInsertionPointAndCutInToStraight</a></td><td><div class="summary">
   Align the part by its insertion point to a point and rotation on a straight. This will automatically size and connect the part being cut into, if possible.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.ArePhasesModifiable">ArePhasesModifiable</a></td><td><div class="summary">
   Returns true if the properties CreatedPhaseId and DemolishedPhaseId can be modified for this Element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CanAdjustEndLength(Autodesk.Revit.DB.Connector)">CanAdjustEndLength</a></td><td><div class="summary">
   Checks if the end of fabrication part can be adjusted.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CanASlopeBeApplied">CanASlopeBeApplied</a></td><td><div class="summary">
   This will test if a slope can be applied to the part and maintain connections with any connected parts.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.CanBeHidden(Autodesk.Revit.DB.View)">CanBeHidden</a></td><td><div class="summary">Indicates if the element can be hidden in the view.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.CanBeLocked">CanBeLocked</a></td><td><div class="summary">
   Identifies if the element can be locked.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.CanDeleteSubelement(Autodesk.Revit.DB.Subelement)">CanDeleteSubelement</a></td><td><div class="summary">
   Checks if given subelement can be removed from the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.CanHaveAnalyticalModel">CanHaveAnalyticalModel</a></td><td><div class="summary">
   Indicates whether the Element can have an Analytical Model.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.CanHaveTypeAssigned">CanHaveTypeAssigned<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">
   Identifies if the element can have a type assigned.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CanSplitStraight(Autodesk.Revit.DB.XYZ)">CanSplitStraight(XYZ)</a></td><td><div class="summary">
   Validates if the straight can be split into two at the passed in point.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CanSplitStraight(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ)">CanSplitStraight(Document, ElementId, XYZ)</a></td><td><div class="summary">
   Validates if the straight can be split into two at the passed in point.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.ChangeTypeId(Autodesk.Revit.DB.ElementId)">ChangeTypeId(ElementId)</a></td><td><div class="summary">
   Changes the type of the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.ConnectAndCouple(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector)">ConnectAndCouple</a></td><td><div class="summary">
   Makes a connection between the specified connectors and adds coupling if necessary.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.Create(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationServiceButton,System.Int32,Autodesk.Revit.DB.ElementId)">Create(Document, FabricationServiceButton, Int32, ElementId)</a></td><td><div class="summary">
   Creates a fabrication part element based on button.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.Create(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationServiceButton,System.Double,System.Double,Autodesk.Revit.DB.ElementId)">Create(Document, FabricationServiceButton, Double, Double, ElementId)</a></td><td><div class="summary">
   Creates a fabrication part element based on button and size.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CreateHanger(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationServiceButton,System.Int32,Autodesk.Revit.DB.ElementId)">CreateHanger(Document, FabricationServiceButton, Int32, ElementId)</a></td><td><div class="summary">
   Creates a free placed hanger.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CreateHanger(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationServiceButton,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Connector,System.Double,System.Boolean)">CreateHanger(Document, FabricationServiceButton, ElementId, Connector, Double, Boolean)</a></td><td><div class="summary">
   Creates a hanger on the fabrication part.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.CreateHanger(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationServiceButton,System.Int32,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Connector,System.Double,System.Boolean)">CreateHanger(Document, FabricationServiceButton, Int32, ElementId, Connector, Double, Boolean)</a></td><td><div class="summary">
   Creates a hanger on the fabrication part.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.DeleteEntity(Autodesk.Revit.DB.ExtensibleStorage.Schema)">DeleteEntity</a></td><td><div class="summary">
   Deletes the existing entity created by %schema% in the element
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.DeleteSubelement(Autodesk.Revit.DB.Subelement)">DeleteSubelement</a></td><td><div class="summary">
   Removes a subelement from the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.DeleteSubelements(System.Collections.Generic.IList{Autodesk.Revit.DB.Subelement})">DeleteSubelements</a></td><td><div class="summary">
   Removes the subelements from the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.Dispose">Dispose</a></td><td> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetAnalyticalModel">GetAnalyticalModel</a></td><td><div class="summary">
   Retrieves writeable Analytical Model for Element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetAnalyticalModelId">GetAnalyticalModelId</a></td><td><div class="summary">
   Retrieves the Element Id of the Analytical Model Element for this Element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetCalculatedDimensionValue(Autodesk.Revit.DB.FabricationDimensionDefinition)">GetCalculatedDimensionValue</a></td><td><div class="summary">
   Gets the calculated dimension value.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetDimensionCalculatedOptions(Autodesk.Revit.DB.FabricationDimensionDefinition)">GetDimensionCalculatedOptions</a></td><td><div class="summary">
   Gets the calculated options of the fabrication dimension.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetDimensions">GetDimensions</a></td><td><div class="summary">
   Gets all fabrication dimensions.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetDimensionValue(Autodesk.Revit.DB.FabricationDimensionDefinition)">GetDimensionValue</a></td><td><div class="summary">
   Gets the value of the fabrication dimension, returns value in Revit internal units.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetEntity(Autodesk.Revit.DB.ExtensibleStorage.Schema)">GetEntity</a></td><td><div class="summary">
   Returns the existing entity corresponding to the Schema if it has been saved in the
   Element, or an invalid entity otherwise.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetEntitySchemaGuids">GetEntitySchemaGuids</a></td><td><div class="summary">
   Returns the Schema guids of any Entities stored in this element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetExternalFileReference">GetExternalFileReference</a></td><td><div class="summary">
   Gets information pertaining to the external file referenced
   by the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetExternalResourceReference(Autodesk.Revit.DB.ExternalResourceType)">GetExternalResourceReference</a></td><td><div class="summary">
   Gets the ExternalResourceReference associated with a specified external resource type.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetExternalResourceReferences">GetExternalResourceReferences</a></td><td><div class="summary">
   Gets the full map of the external resource references referenced
   by the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetGeneratingElementIds(Autodesk.Revit.DB.GeometryObject)">GetGeneratingElementIds</a></td><td><div class="summary">
   Returns the ids of the element(s) that generated the input geometry object.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetGeometryObjectFromReference(Autodesk.Revit.DB.Reference)">GetGeometryObjectFromReference</a></td><td><div class="summary">
   Retrieve one geometric primitive contained in the element given a reference.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetHostedInfo">GetHostedInfo</a></td><td><div class="summary">
   Gets the fabrication hosted element information.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetMaterialArea(Autodesk.Revit.DB.ElementId,System.Boolean)">GetMaterialArea</a></td><td><div class="summary">
   Gets the area of the material with the given id.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetMaterialIds(System.Boolean)">GetMaterialIds</a></td><td><div class="summary">
   Gets the element ids of all materials present in the element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetMaterialVolume(Autodesk.Revit.DB.ElementId)">GetMaterialVolume</a></td><td><div class="summary">
   Gets the volume of the material with the given id.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetMonitoredLinkElementIds">GetMonitoredLinkElementIds</a></td><td><div class="summary">
   Provides the link instance IDs when the element is monitoring.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetMonitoredLocalElementIds">GetMonitoredLocalElementIds</a></td><td><div class="summary">
   Provides the local element IDs when the element is monitoring.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetOrderedParameters">GetOrderedParameters</a></td><td><div class="summary">
Gets the parameters associated to the element in order. 
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetParameterFormatOptions(Autodesk.Revit.DB.ElementId)">GetParameterFormatOptions</a></td><td><div class="summary">
   Returns a FormatOptions override for the element Parameter, or a default FormatOptions if no override exists.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetParameters(System.String)">GetParameters</a></td><td><div class="summary">Retrieves the parameters from the element via the given name.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetPartAncillaryUsage">GetPartAncillaryUsage</a></td><td><div class="summary">
   Gets a list of all ancillary usage information for the part.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetPartCustomDataInteger(System.Int32)">GetPartCustomDataInteger</a></td><td><div class="summary">
   Get custom data integer value for the specified custom data.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetPartCustomDataReal(System.Int32)">GetPartCustomDataReal</a></td><td><div class="summary">
   Get custom data real value for the specified custom data.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetPartCustomDataText(System.Int32)">GetPartCustomDataText</a></td><td><div class="summary">
   Get custom data text for the specified custom data.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetPhaseStatus(Autodesk.Revit.DB.ElementId)">GetPhaseStatus</a></td><td><div class="summary">
   Gets the status of a given element in the input phase
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetProductListEntryCount">GetProductListEntryCount</a></td><td><div class="summary">
   Gets the number of product entries for this part.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetProductListEntryName(System.Int32)">GetProductListEntryName</a></td><td><div class="summary">
   Gets the specified product list entry name.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetRodInfo">GetRodInfo</a></td><td><div class="summary">
   Gets the fabrication rod information.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetSubelements">GetSubelements</a></td><td><div class="summary">
   Returns the collection of element subelements.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.GetTransform">GetTransform</a></td><td><div class="summary">
   Gets the transformation matrix of the fabrication part element.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetTypeId">GetTypeId</a></td><td><div class="summary">
   Returns the identifier of this element's type.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.GetValidTypes">GetValidTypes<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">
   Obtains a set of types that are valid for this element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.HasCustomData(System.Int32)">HasCustomData</a></td><td><div class="summary">
   Check if fabrication part contains custom data already.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.HasNoConnections">HasNoConnections</a></td><td><div class="summary">
   Checks to see if all the fabrication part's connectors are open.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.HasPhases">HasPhases</a></td><td><div class="summary">
   Returns true if this Element has the properties CreatedPhaseId and DemolishedPhaseId.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsAHanger">IsAHanger</a></td><td><div class="summary">
   Checks whether it is a hanger.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsAStraight">IsAStraight</a></td><td><div class="summary">
   Checks whether it is a straight part.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsATap">IsATap</a></td><td><div class="summary">
   Checks if it is any sort of tap.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsDimensionCalculated(Autodesk.Revit.DB.FabricationDimensionDefinition)">IsDimensionCalculated</a></td><td><div class="summary">
   Checks if the fabrication dimension is calculated.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsExternalFileReference">IsExternalFileReference</a></td><td><div class="summary">
   Determines whether this Element represents an external
   file.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsHidden(Autodesk.Revit.DB.View)">IsHidden</a></td><td><div class="summary">Identifies if the element has been permanently hidden in the view.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsMonitoringLinkElement">IsMonitoringLinkElement</a></td><td><div class="summary">
   Indicate whether an element is monitoring any elements in any linked models.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsMonitoringLocalElement">IsMonitoringLocalElement</a></td><td><div class="summary">
   Indicate whether an element is monitoring other local elements.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsPhaseCreatedValid(Autodesk.Revit.DB.ElementId)">IsPhaseCreatedValid</a></td><td><div class="summary">
   Returns true if createdPhaseId is an allowed value for the property CreatedPhaseId in this Element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsPhaseDemolishedValid(Autodesk.Revit.DB.ElementId)">IsPhaseDemolishedValid</a></td><td><div class="summary">
   Returns true if demolishedPhaseId is an allowed value for the property DemolishedPhaseId in this Element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsProductList">IsProductList</a></td><td><div class="summary">
   Gets whether or not the fabrication part is a product list.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsProductListEntryCompatibleSize(System.Int32)">IsProductListEntryCompatibleSize</a></td><td><div class="summary">
   Checks to see if this part can be changed to the specified product entry without altering any connected dimensions.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsSameAs(Autodesk.Revit.DB.FabricationPart,System.Collections.Generic.IList{Autodesk.Revit.DB.Fabrication.FabricationPartCompareType})">IsSameAs</a></td><td><div class="summary">
   Compare this fabrication part with the part passed and checks the pattern dimensions and options. A list of fields that can be ignored in the comparison check can be specified.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.IsStraightSegment(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)">IsStraightSegment</a></td><td><div class="summary">
   Validates if the part is a straight.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.IsValidType(Autodesk.Revit.DB.ElementId)">IsValidType(ElementId)</a></td><td><div class="summary">
   Checks if given type is valid for this element.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.LookupParameter(System.String)">LookupParameter</a></td><td><div class="summary">Attempts to find a parameter on the element which has the given name.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.OptimizeLengths(Autodesk.Revit.DB.Document,System.Collections.Generic.ISet{Autodesk.Revit.DB.ElementId})">OptimizeLengths</a></td><td><div class="summary">
   Optimizes the length fabrication straight parts.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.PlaceAsTap(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Connector,System.Double,System.Double,System.Double)">PlaceAsTap</a></td><td><div class="summary">
   Places the part by its connector to a specific position on the straight part at the specified distance from the host part connector.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.PlaceFittingAsCutIn(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Connector,System.Double)">PlaceFittingAsCutIn</a></td><td><div class="summary">
   Places the fitting on the straight part by cut in, use the fitting's focal point as the insertion position.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.RefersToExternalResourceReference(Autodesk.Revit.DB.ExternalResourceType)">RefersToExternalResourceReference</a></td><td><div class="summary">
   Determines whether this Element uses external resources associated with
   a specified external resource type.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.RefersToExternalResourceReferences">RefersToExternalResourceReferences</a></td><td><div class="summary">
   Determines whether this Element uses external resources.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.RemovePartCustomData(System.Int32)">RemovePartCustomData</a></td><td><div class="summary">
   Remove custom data from the fabrication part.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.Reposition(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)">Reposition</a></td><td><div class="summary">
   Repositions the fabrication straight part to another end of the run.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.RotateConnectedPartByConnector(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,System.Double)">RotateConnectedPartByConnector</a></td><td><div class="summary">
   Rotates a connected fabrication part around the axis of the specified connector.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.RotateConnectedTap(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.FabricationPart,System.Double,System.Double)">RotateConnectedTap</a></td><td><div class="summary">
   Rotates a connected fabrication tap by the specified angles about the primary and secondary axis.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetCalculatedDimensionValue(Autodesk.Revit.DB.FabricationDimensionDefinition,System.String)">SetCalculatedDimensionValue</a></td><td><div class="summary">
   Sets the calculated dimension value.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetDimensionValue(Autodesk.Revit.DB.FabricationDimensionDefinition,System.Double)">SetDimensionValue</a></td><td><div class="summary">
   Sets the fabrication dimension value. The value is in Revit internal units.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Element.SetEntity(Autodesk.Revit.DB.ExtensibleStorage.Entity)">SetEntity</a></td><td><div class="summary">
   Stores the entity in the element. If an Entity described by the same Schema already
   exists, it is overwritten.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Element">Element</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetPartCustomDataInteger(System.Int32,System.Int32)">SetPartCustomDataInteger</a></td><td><div class="summary">
   Set the custom data integer value for the specified custom data.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetPartCustomDataReal(System.Int32,System.Double)">SetPartCustomDataReal</a></td><td><div class="summary">
   Set the custom data real value for the specified custom data.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetPartCustomDataText(System.Int32,System.String)">SetPartCustomDataText</a></td><td><div class="summary">
   Set the custom data real value for the specified custom data.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SetPositionByEnd(Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.XYZ)">SetPositionByEnd</a></td><td><div class="summary">
   Positions the connector of the fabrication part element by the passed point.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SplitStraight(Autodesk.Revit.DB.XYZ)">SplitStraight(XYZ)</a></td><td><div class="summary">
   Splits the straight into two at the passed in point.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.SplitStraight(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.XYZ)">SplitStraight(Document, ElementId, XYZ)</a></td><td><div class="summary">
   Splits the straight into two at the passed in point.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.FabricationPart.StretchAndFit(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Connector,Autodesk.Revit.DB.Fabrication.FabricationPartRouteEnd,System.Collections.Generic.ISet{Autodesk.Revit.DB.ElementId}@)">StretchAndFit</a></td><td><div class="summary">
   Stretch the fabrication part from the specified connector and fit to the target routing end.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.FabricationPart">FabricationPart Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>