<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BuiltInFailures.SketchFailures Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BuiltInFailures.SketchFailures class" /><meta name="System.Keywords" content="BuiltInFailures.SketchFailures class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.SketchFailures class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="ce55b9a0-e569-f16f-8d5c-daaa442dd2eb" /><meta name="guid" content="ce55b9a0-e569-f16f-8d5c-daaa442dd2eb" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.SketchFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.SketchFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.SketchFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.SketchFailures class" />
<meta name="Microsoft.Help.Keywords" content="BuiltInFailures.SketchFailures class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BuiltInFailures.SketchFailures class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures" /><MSHelp:TOCTitle Title="BuiltInFailures.SketchFailures Members" /><MSHelp:RLTitle Title="BuiltInFailures.SketchFailures Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBuiltInFailuresSketchFailuresMembersTopic" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.SketchFailures class" /><MSHelp:Keyword Index="K" Term="BuiltInFailures.SketchFailures class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.BuiltInFailures.SketchFailures class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>SketchFailures Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>SketchFailures Class</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p><div class="summary">Provides a container of all Revit built-in FailureDefinitionId instances.</div></p><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>SketchFailures</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.AreaLoadNoForce">AreaLoadNoForce</a></td><td><div class="summary">
   Area Load can't have all force components equal to zero.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.AxisNotSpecified">AxisNotSpecified</a></td><td><div class="summary">
   Axis of revolution not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BadNosingProfile">BadNosingProfile</a></td><td><div class="summary">
   Stairs nosing profile must have one loop. Wrong profile will not be shown in profiles list in Stairs Type properties.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BadRailingsProfile">BadRailingsProfile</a></td><td><div class="summary">
   Rail profile must have one closed loop. Wrong profile will not be shown in profiles list for rail definition.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BeamDirectionNotSpecified">BeamDirectionNotSpecified</a></td><td><div class="summary">
   Beam direction not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BeamDirectionNotSpecifiedError">BeamDirectionNotSpecifiedError</a></td><td><div class="summary">
   Beam direction not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetClosedLoopInSketch">BentFabricSheetClosedLoopInSketch</a></td><td><div class="summary">
   The bend profile cannot contain a closed loop. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetEmptySketch">BentFabricSheetEmptySketch</a></td><td><div class="summary">
   The bend profile requires at least one segment to be placed in a host. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetInvalidElementInSketch">BentFabricSheetInvalidElementInSketch</a></td><td><div class="summary">
   Arcs in a bend profile must be separated from one another with a connected straight segment. The bend profile cannot start or end with an arc. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetLinesOverlapOrIntersect">BentFabricSheetLinesOverlapOrIntersect</a></td><td><div class="summary">
   Segments in a bend profile cannot overlap, intersect, or be collinearly contiguous. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetManyLoopsInSketch">BentFabricSheetManyLoopsInSketch</a></td><td><div class="summary">
   The bend profile cannot contain two or more disconnected segments. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BentFabricSheetTooShortSegments">BentFabricSheetTooShortSegments</a></td><td><div class="summary">
   A segment in the bend profile is too short to apply the wire bend diameter. The bent fabric sheet of the selected type cannot be placed in a host. Click Continue to correct the profile or Click Quit sketching to exit the bend profile editor.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BuildingPadNoSurface">BuildingPadNoSurface</a></td><td><div class="summary">
   A Pad can't extend beyond the edge of a Toposurface.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.BuildingPadNoSurfaceError">BuildingPadNoSurfaceError</a></td><td><div class="summary">
   A Pad can't extend beyond the edge of a Toposurface.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotChangeUserSketchPlane">CannotChangeUserSketchPlane</a></td><td><div class="summary">
   Can't change plane of [Element Name] Sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotChangeUserSketchPlaneError">CannotChangeUserSketchPlaneError</a></td><td><div class="summary">
   Can't change plane of [Element Name] Sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotChangeWorkplaneVisibility">CannotChangeWorkplaneVisibility</a></td><td><div class="summary">
   Can't change Work Plane Visibility.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotComputeRailingsElevation">CannotComputeRailingsElevation</a></td><td><div class="summary">
   Can't compute Railings Elevation Profile.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotComputeRailingsElevationError">CannotComputeRailingsElevationError</a></td><td><div class="summary">
   Can't compute Railings Elevation Profile.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotComputeRailingsElevationWarn">CannotComputeRailingsElevationWarn</a></td><td><div class="summary">
   Can't compute Railings Elevation Profile
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotConvertSketch">CannotConvertSketch</a></td><td><div class="summary">
   Can't convert Sketch to Rebar Shape.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotDrawExtrusionRoof">CannotDrawExtrusionRoof</a></td><td><div class="summary">
   Can't make extruded roof.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotDrawProfileRoof">CannotDrawProfileRoof</a></td><td><div class="summary">
   Can't make footprint roof.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotGetSketchReferences">CannotGetSketchReferences</a></td><td><div class="summary">
   Cannot find references to dimension sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotHaveArcs">CannotHaveArcs</a></td><td><div class="summary">
   Sorry, we can't use arcs here.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CannotHaveArcsPath3d">CannotHaveArcsPath3d</a></td><td><div class="summary">
   Sorry, we can't use arcs here.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CircleMultiPlanarShapeInSketch">CircleMultiPlanarShapeInSketch</a></td><td><div class="summary">
   A circle can't be converted to multiplanar shape.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ClosedProfileRoof">ClosedProfileRoof</a></td><td><div class="summary">
   Extrusion roof sketch must be open. The roof's thickness and material composition are defined in its type.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ConstantHeightNotParallel">ConstantHeightNotParallel</a></td><td><div class="summary">
   Constant-height-defining lines must be parallel.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ConstantHeightNotParallelError">ConstantHeightNotParallelError</a></td><td><div class="summary">
   Constant-height-defining lines must be parallel.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ContainedInOtherLoops">ContainedInOtherLoops</a></td><td><div class="summary">
   When creating an opening, you cannot sketch loops within other loops. The highlighted loop(s) are contained within another loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ConvertSplineToLineFailed">ConvertSplineToLineFailed</a></td><td><div class="summary">
   Failed to convert spline to straight line
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CurveFromPickedFailed">CurveFromPickedFailed</a></td><td><div class="summary">
   Can't create boundary from pick.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CurveIntersectsCutFace">CurveIntersectsCutFace</a></td><td><div class="summary">
   The highlighted line intersects the boundary of the face being modified.  To modify a cut face, use open loops that end on the
   existing boundary without intersecting or overlapping existing edges.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CurveIntersectsSplitFace">CurveIntersectsSplitFace</a></td><td><div class="summary">
   The highlighted line intersects the boundary of the face being split.  To split a face at its border, use an open loop that
   ends on the boundary of the face.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.CurveTooShort">CurveTooShort</a></td><td><div class="summary">
   Line is too short.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.DifferentOffsets">DifferentOffsets</a></td><td><div class="summary">
   Adjacent slope-defining lines must have identical eave heights; the highlighted lines do not.  You can use the Align Eaves tool to have the eaves aligned for you.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ElementsSketchTooLarge">ElementsSketchTooLarge</a></td><td><div class="summary">
   The sketch defining the highlighted element is too large.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ElevationSketchNotAllowed">ElevationSketchNotAllowed</a></td><td><div class="summary">
   Wall in a family can't have an elevation profile.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.EndsNotOnCutFace">EndsNotOnCutFace</a></td><td><div class="summary">
   Ends of the sketched loop do not lie on the boundary of the face being modified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.EndsNotOnEdge">EndsNotOnEdge</a></td><td><div class="summary">
   Ends of an open loop in sketch splitting face do not lie on an edge of the face to split.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.FloorCannotAddDirectionCurve">FloorCannotAddDirectionCurve</a></td><td><div class="summary">
   Cannot add the direction curve in the floor sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.FloorCannotAddDirectionCurveError">FloorCannotAddDirectionCurveError</a></td><td><div class="summary">
   Cannot add the direction curve in the floor sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.FloorDirectionNotSpecified">FloorDirectionNotSpecified</a></td><td><div class="summary">
   Structural floor span direction not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.FloorManyDirectionCurves">FloorManyDirectionCurves</a></td><td><div class="summary">
   More than one span direction curve specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidAreaLoadSketch">InvalidAreaLoadSketch</a></td><td><div class="summary">
   Area Load has invalid Sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidAreaLoadSketchError">InvalidAreaLoadSketchError</a></td><td><div class="summary">
   Area Load has invalid Sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidCropAreaSketch">InvalidCropAreaSketch</a></td><td><div class="summary">
   Crop area sketch can either be empty or include one closed, not self-intersecting loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidCropAreaSketchRegen">InvalidCropAreaSketchRegen</a></td><td><div class="summary">
   Crop area sketch can either be empty or include one closed, not self-intersecting loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidElevationSketch">InvalidElevationSketch</a></td><td><div class="summary">
   Elevation Profile sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidElevationSketchError">InvalidElevationSketchError</a></td><td><div class="summary">
   Elevation Profile sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidProfile">InvalidProfile</a></td><td><div class="summary">
   One or more profiles are invalid.  Make sure that every used profile is a closed loop of non-intersecting lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidProfileError">InvalidProfileError</a></td><td><div class="summary">
   One or more profiles are invalid.  Make sure that every used profile is a closed loop of non-intersecting lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidRoofCurveloop">InvalidRoofCurveloop</a></td><td><div class="summary">
   Base sketch for roof is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidRoofCurveloopError">InvalidRoofCurveloopError</a></td><td><div class="summary">
   Base sketch for roof is invalid
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidRoofCurveloopFailure">InvalidRoofCurveloopFailure</a></td><td><div class="summary">
   Base sketch for roof is invalid
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketch">InvalidSketch</a></td><td><div class="summary">
   Sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchError">InvalidSketchError</a></td><td><div class="summary">
   Sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchForBuildingpad">InvalidSketchForBuildingpad</a></td><td><div class="summary">
   Pad sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchForCeiling">InvalidSketchForCeiling</a></td><td><div class="summary">
   Ceiling sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchForFloor">InvalidSketchForFloor</a></td><td><div class="summary">
   Floor sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchForRoofsoffit">InvalidSketchForRoofsoffit</a></td><td><div class="summary">
   Roof Soffit sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.InvalidSketchPath3d">InvalidSketchPath3d</a></td><td><div class="summary">
   Sketch is invalid.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LandingNotEnoughBoundaryCurves">LandingNotEnoughBoundaryCurves</a></td><td><div class="summary">
   Sketch landing require boundaries
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LandingTwoManyLoops">LandingTwoManyLoops</a></td><td><div class="summary">
   Sketch landing can only have one closed loop
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LinesOverlap">LinesOverlap</a></td><td><div class="summary">
   Cannot have overlapping lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LinesOverlapError">LinesOverlapError</a></td><td><div class="summary">
   Cannot have overlapping lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LinesOverlapPath3d">LinesOverlapPath3d</a></td><td><div class="summary">
   Cannot have overlapping lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LoopIntersect">LoopIntersect</a></td><td><div class="summary">
   Lines cannot intersect each other. The highlighted lines currently intersect.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LoopIntersectError">LoopIntersectError</a></td><td><div class="summary">
   Lines cannot intersect each other. The highlighted lines currently intersect.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LoopIntersectPath3d">LoopIntersectPath3d</a></td><td><div class="summary">
   Lines cannot intersect each other. The highlighted lines currently intersect.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LoopsOutsideFaceSplit">LoopsOutsideFaceSplit</a></td><td><div class="summary">
   Some of the lines drawn lie outside of the boundary of the face being split.  All lines used to split a face must be contained
   within the face being split and cannot intersect or overlap any of the boundaries of that face.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.LoopsOutsideFaceSplitterTooShort">LoopsOutsideFaceSplitterTooShort</a></td><td><div class="summary">
   Some of the lines drawn lie outside of the boundary of the face being split.  All lines used to split a face must be contained
   within the face being split and cannot intersect or overlap any of the boundaries of that face.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ManyCCWLoops">ManyCCWLoops</a></td><td><div class="summary">
   Area defined by sketch must be connected.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ManyCCWLoopsError">ManyCCWLoopsError</a></td><td><div class="summary">
   Area defined by sketch must be connected.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ManyDirectionCurves">ManyDirectionCurves</a></td><td><div class="summary">
   More than one direction curve specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ManyDirectionCurvesError">ManyDirectionCurvesError</a></td><td><div class="summary">
   More than one direction curve specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.MoreThanOneAxis">MoreThanOneAxis</a></td><td><div class="summary">
   More than one axes of revolution.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.MutipleStairsPathInOneRunFailure">MutipleStairsPathInOneRunFailure</a></td><td><div class="summary">
   Each stairs run can only have one stairs path.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NestedLoops">NestedLoops</a></td><td><div class="summary">
   Cannot have nested loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NoLoops">NoLoops</a></td><td><div class="summary">
   Sketch is empty.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NoLoopsError">NoLoopsError</a></td><td><div class="summary">
   Sketch is empty.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NoLoopsPath3d">NoLoopsPath3d</a></td><td><div class="summary">
   Sketch is empty.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NonMonotoneRoof">NonMonotoneRoof</a></td><td><div class="summary">
   All parts of an extruded roof must face upward. Make sure that no part of the sketch lies below any other part of the sketch.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NoPlane">NoPlane</a></td><td><div class="summary">
   Highlighted geometry no longer determines a plane
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneCCWLoop">NotOneCCWLoop</a></td><td><div class="summary">
   This sketch defines more than one footprint.  Make sure the sketch contains only one outermost loop and that there are no loops inside inner loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneCurve">NotOneCurve</a></td><td><div class="summary">
   More than one curve not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneCurveError">NotOneCurveError</a></td><td><div class="summary">
   More than one curve not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneCurvePath3d">NotOneCurvePath3d</a></td><td><div class="summary">
   More than one curve not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneLoop">NotOneLoop</a></td><td><div class="summary">
   More than one loop not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.NotOneLoopPath3d">NotOneLoopPath3d</a></td><td><div class="summary">
   More than one loop not allowed.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.OpenAreaLoadLoop">OpenAreaLoadLoop</a></td><td><div class="summary">
   Area Load Sketch can't contain open loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.OpenAreaLoadLoopError">OpenAreaLoadLoopError</a></td><td><div class="summary">
   Area Load Sketch can't contain open loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.OpenLoop">OpenLoop</a></td><td><div class="summary">
   Lines must be in closed loops. The highlighted lines are open on one end.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.OpenLoopError">OpenLoopError</a></td><td><div class="summary">
   Lines must be in closed loops. The highlighted lines are open on one end.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.OpenLoopPath3d">OpenLoopPath3d</a></td><td><div class="summary">
   Lines must be in closed loops. The highlighted lines are open on one end.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PathCannotBeClosedLoop">PathCannotBeClosedLoop</a></td><td><div class="summary">
   Path cannot be a closed loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PathCannotBeClosedLoopPath3d">PathCannotBeClosedLoopPath3d</a></td><td><div class="summary">
   Path cannot be a closed loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PathReinforcementClosedLoop">PathReinforcementClosedLoop</a></td><td><div class="summary">
   Sketch contains a closed loop. Can't create Path Reinforcement.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PathReinforcementEmptySketch">PathReinforcementEmptySketch</a></td><td><div class="summary">
   Sketch is empty. Can't create Path Reinforcement.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PathReinforcementManyLoops">PathReinforcementManyLoops</a></td><td><div class="summary">
   Sketch contains more than one chain. Can't create Path Reinforcement.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.PlanarMultiPlanarShapeInSketch">PlanarMultiPlanarShapeInSketch</a></td><td><div class="summary">
   The current shape is only bent in a single plane. A multi-planar definition is not required. Please redefine the shape on the top plane only.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RailingDoublyConnected">RailingDoublyConnected</a></td><td><div class="summary">
   Railings hosted on Stairs must form a single, open, connected line.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RailingDoublyConnectedError">RailingDoublyConnectedError</a></td><td><div class="summary">
   Railings hosted on Stairs must form a single, open, connected line.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RailingNotConnected">RailingNotConnected</a></td><td><div class="summary">
   The Railing line must be a single connected Sketch. If you want separate pieces of Railing, create two or more separate Railings.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RailingNotConnectedError">RailingNotConnectedError</a></td><td><div class="summary">
   The Railing line must be a single connected Sketch. If you want separate pieces of Railing, create two or more separate Railings.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarEmptySketch">RebarEmptySketch</a></td><td><div class="summary">
   Rebar Sketch is empty. Can't create Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarEmptySketchError">RebarEmptySketchError</a></td><td><div class="summary">
   Rebar Sketch is empty. Can't create Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarManyLoops">RebarManyLoops</a></td><td><div class="summary">
   Rebar Sketch contains more than one loop. Can't create Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarManyLoopsError">RebarManyLoopsError</a></td><td><div class="summary">
   Rebar Sketch contains more than one loop. Can't create Rebar.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarSystemDirectionNotSpecified">RebarSystemDirectionNotSpecified</a></td><td><div class="summary">
   Major direction not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RebarSystemDirectionNotSpecifiedError">RebarSystemDirectionNotSpecifiedError</a></td><td><div class="summary">
   Major direction not specified.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RunInvalidSketch">RunInvalidSketch</a></td><td><div class="summary">
   Invalid sketch, can't create run by this sketch
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.RunNotEnoughBoundaryCurves">RunNotEnoughBoundaryCurves</a></td><td><div class="summary">
   Sketch run require boundaries (chains of one or more Boundary Lines)
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SculptingCurvesCannotFormClosedLoop">SculptingCurvesCannotFormClosedLoop</a></td><td><div class="summary">
   Curves cannot form a closed loop.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SculptingCurvesCrossAxis">SculptingCurvesCrossAxis</a></td><td><div class="summary">
   The highlighted curves cross the axis.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SculptingCurvesTouchAxis">SculptingCurvesTouchAxis</a></td><td><div class="summary">
   The highlighted curves touch the axis.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SculptingLoopsOnBothSidesOfAxis">SculptingLoopsOnBothSidesOfAxis</a></td><td><div class="summary">
   All curves must be on the same side of the axis.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SculptingSingleLineLoopLiesOnAxis">SculptingSingleLineLoopLiesOnAxis</a></td><td><div class="summary">
   The highlighted lines lie on the axis.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ShortCurveInSketch">ShortCurveInSketch</a></td><td><div class="summary">
   The sketch contains an extremely short line.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.ShortCurveInSketchRoof">ShortCurveInSketchRoof</a></td><td><div class="summary">
   The sketch contains an extremely short line.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SiteCannotDrawSurfaceBoundary">SiteCannotDrawSurfaceBoundary</a></td><td><div class="summary">
   Cannot make surface with specified boundary.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchedRunInvalidPath">SketchedRunInvalidPath</a></td><td><div class="summary">
   Invalid stair path. Stair path should connect both start and end riser, and cross all other risers.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchFailurePlanes">SketchFailurePlanes</a></td><td><div class="summary">
   Sketch is no longer parallel to its defining plane
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchingInTheWrongView">SketchingInTheWrongView</a></td><td><div class="summary">
   Detail sketch is only editable in [View Type].
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchingInWrongView">SketchingInWrongView</a></td><td><div class="summary">
   Detail sketch is not editable in this view.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchOverconstrained">SketchOverconstrained</a></td><td><div class="summary">
   Sketch is overconstrained.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchOverconstrainedError">SketchOverconstrainedError</a></td><td><div class="summary">
   Sketch is overconstrained.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchOverconstrainedWarn">SketchOverconstrainedWarn</a></td><td><div class="summary">
   Sketch is overconstrained.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchTooLarge">SketchTooLarge</a></td><td><div class="summary">
   Sketch is too large.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SketchWasDeleted">SketchWasDeleted</a></td><td><div class="summary">
   Sketch was deleted.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairClosedBoundaries">StairClosedBoundaries</a></td><td><div class="summary">
   Stairs Boundaries (chains of one or more Boundary Lines) should not form closed loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairClosedBoundariesError">StairClosedBoundariesError</a></td><td><div class="summary">
   Stairs Boundaries (chains of one or more Boundary Lines) should not form closed loops.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairNotEnoughBoundaryCurves">StairNotEnoughBoundaryCurves</a></td><td><div class="summary">
   Stairs require boundaries (chains of one or more Boundary Lines) on each side of the Stair.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairNotEnoughBoundaryCurvesError">StairNotEnoughBoundaryCurvesError</a></td><td><div class="summary">
   Stairs require boundaries (chains of one or more Boundary Lines) on each side of the Stair.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairNotEnoughRiserCurves">StairNotEnoughRiserCurves</a></td><td><div class="summary">
   Boundaries (chains of one or more Boundary Lines) must be connected by at least two Riser Lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairNotEnoughRiserCurvesError">StairNotEnoughRiserCurvesError</a></td><td><div class="summary">
   Boundaries (chains of one or more Boundary Lines) must be connected by at least two Riser Lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairOnlyOneConnectedBoundary">StairOnlyOneConnectedBoundary</a></td><td><div class="summary">
   Stairs require no less than two boundaries (chains of one or more Boundary Lines)."
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairOnlyOneConnectedBoundaryError">StairOnlyOneConnectedBoundaryError</a></td><td><div class="summary">
   Stairs require no less than two boundaries (chains of one or more Boundary Lines).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairRiserDoesntIntersectBoundary">StairRiserDoesntIntersectBoundary</a></td><td><div class="summary">
   The line representing the top of a riser does not intersect one or both of the boundary lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairRiserDoesntIntersectBoundaryError">StairRiserDoesntIntersectBoundaryError</a></td><td><div class="summary">
   The line representing the top of a riser does not intersect one or both of the boundary lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairTooManyConnectedBoundaries">StairTooManyConnectedBoundaries</a></td><td><div class="summary">
   Stairs require no more than two boundaries (chains of one or more Boundary Lines).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.StairTooManyConnectedBoundariesError">StairTooManyConnectedBoundariesError</a></td><td><div class="summary">
   Stairs require no more than two boundaries (chains of one or more Boundary Lines).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SubregionNoHostSurf">SubregionNoHostSurf</a></td><td><div class="summary">
   A Subregion cannot be created outside the boundary of a Toposurface.
   A Subregion should be completely inside a Toposurface or overlap a Toposurface.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SuggestMakingFamilyNonParametric">SuggestMakingFamilyNonParametric</a></td><td><div class="summary">
   Performance Warning: This family now contains both labeled dimensions and sketches with many segments. This may hurt performance. To improve performance, create elements that require complex sketches as nested families.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.SuspendedSketchWarn">SuspendedSketchWarn</a></td><td><div class="summary">
   Highlighted element's sketch could not regenerate and has been suspended.  Select the element and edit its sketch
   to fix the problem.  The element will display in magenta until you fix the problem
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TooFewParamsForSketch">TooFewParamsForSketch</a></td><td><div class="summary">
   The sketched Structural Rebar element has too many segments to be properly parameterized. Please reduce the number of segments.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TooManyElementsInSketch">TooManyElementsInSketch</a></td><td><div class="summary">
   This sketch is large. Performance will improve if constructed as several independent sketches.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TooManySlopes">TooManySlopes</a></td><td><div class="summary">
   There is more than one slope defined.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TooManySlopesError">TooManySlopesError</a></td><td><div class="summary">
   There is more than one slope defined.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussClosedReference">TrussClosedReference</a></td><td><div class="summary">
   Truss references (chains of one or more reference lines) should not form closed loops."
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussCrossingReferences">TrussCrossingReferences</a></td><td><div class="summary">
   Truss top and bottom references cannot cross.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussMissingReference">TrussMissingReference</a></td><td><div class="summary">
   Trusses require both a top and a bottom chord reference (chain of one or more reference lines).
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussOverlappingReference">TrussOverlappingReference</a></td><td><div class="summary">
   Truss references (chains of one or more reference lines) cannot overlap themselves in the vertical direction.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussSegmentedReference">TrussSegmentedReference</a></td><td><div class="summary">
   Truss reference must form a continuous chain of one or more sketch lines.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussShiftedReferences">TrussShiftedReferences</a></td><td><div class="summary">
   Truss top and bottom references (chains of one or more reference lines) must overlap at least partially in the vertical direction.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.TrussSwappedReferences">TrussSwappedReferences</a></td><td><div class="summary">
   Truss top reference must be above the bottom reference.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.UnsatisfiedSupportAssocProp">UnsatisfiedSupportAssocProp</a></td><td><div class="summary">
   Constraint between a Line created with Pick Support and the Support is not satisfied.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.UnsatisfiedWallAssocProp">UnsatisfiedWallAssocProp</a></td><td><div class="summary">
   Constraint between a Line created with Pick Wall and the Wall is not satisfied.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.VarSketchFailure">VarSketchFailure</a></td><td><div class="summary">
   Constraints defined by highlighted Lines and Dimensions can't be satisfied.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.VarSketchInElementFailure">VarSketchInElementFailure</a></td><td><div class="summary">
   The constraints of the sketch defining the highlighted element cannot be satisfied.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.WrongCutBoundaryLoops">WrongCutBoundaryLoops</a></td><td><div class="summary">
   Only open loops can be used for Edit Cut Profile. All open ends must lie on the boundary of the cut profile, and the loop may not
   touch the boundary anywhere except at its ends.
</div></td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.BuiltInFailures.SketchFailures.WrongFaceSplitterLoopTypesNum">WrongFaceSplitterLoopTypesNum</a></td><td><div class="summary">
   Sketch for splitting the face is invalid.  Faces may be split either by a single closed loop that is contained within the face
   or by one or more open loops whose ends lie on the boundary of the face.  None of the lines in the sketch are allowed to overlap
   or intersect the boundaries of the face.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BuiltInFailures.SketchFailures">BuiltInFailures<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>SketchFailures Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>