<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>ProjectPosition Property </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="ProjectPosition property" /><meta name="System.Keywords" content="ProjectLocation.ProjectPosition property" /><meta name="Description" content="Gets or sets the coordinates of a point in the project location coordinate system." /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="d8e0d449-98fc-6a08-8d88-54f68cdfeb3c" /><meta name="guid" content="d8e0d449-98fc-6a08-8d88-54f68cdfeb3c" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="P:Autodesk.Revit.DB.ProjectLocation.ProjectPosition(Autodesk.Revit.DB.XYZ)" />
<meta name="Microsoft.Help.TocParent" content="Properties.T:Autodesk.Revit.DB.ProjectLocation" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="ProjectLocation.ProjectPosition property" />
<meta name="Microsoft.Help.Keywords" content="ProjectPosition property" />
<meta name="Microsoft.Help.Keywords" content="ProjectPosition property" />
<meta name="Microsoft.Help.Keywords" content="ProjectLocation.ProjectPosition property" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.ProjectLocation.ProjectPosition" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.ProjectLocation.get_ProjectPosition" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.ProjectLocation.set_ProjectPosition" />
<meta name="Microsoft.Help.F1" content="Autodesk.Revit.DB.ProjectLocation.ProjectPosition" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="P:Autodesk.Revit.DB.ProjectLocation.ProjectPosition(Autodesk.Revit.DB.XYZ)" /><MSHelp:TOCTitle Title="ProjectPosition Property " /><MSHelp:RLTitle Title="ProjectLocation.ProjectPosition Property  (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="P:Autodesk.Revit.DB.ProjectLocation.ProjectPosition(Autodesk.Revit.DB.XYZ)" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBProjectLocationClassProjectPositionTopic" /><MSHelp:Keyword Index="K" Term="ProjectPosition property" /><MSHelp:Keyword Index="K" Term="ProjectLocation.ProjectPosition property" /><MSHelp:Keyword Index="F" Term="Autodesk.Revit.DB.ProjectLocation.ProjectPosition" /><MSHelp:Attr Name="APIType" Value="Managed" /><MSHelp:Attr Name="APILocation" Value="RevitAPI.dll" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.ProjectLocation.ProjectPosition" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.ProjectLocation.get_ProjectPosition" /><MSHelp:Attr Name="APIName" Value="Autodesk.Revit.DB.ProjectLocation.set_ProjectPosition" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="Abstract" Value="Gets or sets the coordinates of a point in the project location coordinate system." /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><link type="text/css" rel="stylesheet" href="styles/highlight.css" /><script type="text/javascript" src="scripts/highlight.js"> </script>
<script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">ProjectLocation<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>ProjectPosition Property </span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectLocation">ProjectLocation Class</a> <a href="#exampleToggle" onclick="OpenSection(exampleToggle)">Example</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><div class="summary">Gets or sets the coordinates of a point in the project location coordinate system.</div><p /><b>Namespace:</b> <a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB</a><br /><b>Assembly:</b> <span sdata="assembly">RevitAPI</span> (in RevitAPI.dll) Version: 18.0.0.0 (18.0.0.0)<h1 class="heading"><span onclick="ExpandCollapse(syntaxToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(syntaxToggle, event)" tabindex="0"><img id="syntaxToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Syntax</span></h1><div id="syntaxSection" class="section" name="collapseableSection" style=""><div id="syntaxCodeBlocks" class="code"><span codelanguage="CSharp"><table><tr><th>C#</th></tr><tr><td><pre xml:space="preserve">[<a href="http://msdn2.microsoft.com/en-us/library/fwz0y5c2" target="_blank">ObsoleteAttribute</a>("This property is deprecated in Revit 2018. Use ProjectLocation.Get/SetProjectPosition() instead.")]
<span class="keyword">public</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectPosition">ProjectPosition</a> <span class="keyword">this</span>[
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> <span class="parameter">point</span>
] { <span class="keyword">get</span>; <span class="keyword">set</span>; }</pre></td></tr></table></span><span codelanguage="VisualBasicDeclaration"><table><tr><th>Visual Basic</th></tr><tr><td><pre xml:space="preserve">&lt;<a href="http://msdn2.microsoft.com/en-us/library/fwz0y5c2" target="_blank">ObsoleteAttribute</a>("This property is deprecated in Revit 2018. Use ProjectLocation.Get/SetProjectPosition() instead.")&gt; _
<span class="keyword">Public</span> <span class="keyword">Property</span> <span class="identifier">ProjectPosition</span> ( _
	<span class="parameter">point</span> <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a> _
) <span class="keyword">As</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectPosition">ProjectPosition</a>
	<span class="keyword">Get</span>
	<span class="keyword">Set</span></pre></td></tr></table></span><span codelanguage="ManagedCPlusPlus"><table><tr><th>Visual C++</th></tr><tr><td><pre xml:space="preserve">[<a href="http://msdn2.microsoft.com/en-us/library/fwz0y5c2" target="_blank">ObsoleteAttribute</a>(L"This property is deprecated in Revit 2018. Use ProjectLocation.Get/SetProjectPosition() instead.")]
<span class="keyword">public</span>:
<span class="keyword">property</span> <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectPosition">ProjectPosition</a>^ <span class="identifier">ProjectPosition</span>[<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">point</span>] {
	<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectPosition">ProjectPosition</a>^ <span class="keyword">get</span> (<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">point</span>);
	<span class="keyword">void</span> <span class="keyword">set</span> (<a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">XYZ</a>^ <span class="parameter">point</span>, <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectPosition">ProjectPosition</a>^ <span class="parameter">value</span>);
}</pre></td></tr></table></span></div><div id="parameters"><h4 class="subHeading">Parameters</h4><dl paramname="point"><dt><span class="parameter">point</span></dt><dd>Type: <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.XYZ">Autodesk.Revit.DB<span class="languageSpecificText"><span class="cs">.</span><span class="vb">.</span><span class="cpp">::</span><span class="nu">.</span><span class="fs">.</span></span>XYZ</a><br />The point in model coordinates.</dd></dl></div></div><h1 class="heading"><span onclick="ExpandCollapse(remarksToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(remarksToggle, event)" tabindex="0"><img id="remarksToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Remarks</span></h1><div id="remarksSection" class="section" name="collapseableSection" style=""><p>When getting this property,  the North/South, East/West, and Elevation values report the coordinates of the point
similar to the Revit command "Report Shared Coordinates".  To get the values of the transformations applied by this project location, 
pass XYZ.Zero.</p><p>If the project has acquired shared coordinates from a linked model, the 
shared coordinate transformation will be reflected in the coordinates of the transformed point returned by this property.</p><p>When setting this property, the transformations applied to the location are modified such that the passed point becomes the 
specified North/South, East/West and Elevation, and the coordinate transform will have the designated angular rotation.  
This is similar to the Revit command "Specify Coordinates at Point".</p></div><h1 class="heading"><span onclick="ExpandCollapse(exampleToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(exampleToggle, event)" tabindex="0"><img id="exampleToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Examples</span></h1><div id="exampleSection" class="section" name="collapseableSection" style=""><span id="cbc_1" x-lang="CSharp" codelanguage="CSharp"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>C#</div><div class="code"><pre xml:space="preserve"><span class="highlight-comment">//get and set the value of the projectlocation</span>
<span class="highlight-keyword">public</span> ProjectLocation GetProjectLocation(Autodesk.Revit.DB.Document document)
{
    ProjectLocation currentLocation = document.ActiveProjectLocation;

    <span class="highlight-comment">//get the project position</span>
    XYZ origin = <span class="highlight-keyword">new</span> XYZ(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>);

    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> angleRatio = Math.PI / <span class="highlight-number">180</span>;   <span class="highlight-comment">// angle conversion factor</span>

    ProjectPosition projectPosition = currentLocation.GetProjectPosition(origin);
    <span class="highlight-comment">//Angle from True North</span>
    <span class="highlight-keyword">double</span> angle = <span class="highlight-number">30.0</span> * angleRatio;   <span class="highlight-comment">// convert degrees to radian</span>
    <span class="highlight-keyword">double</span> eastWest = <span class="highlight-number">30.0</span>;     <span class="highlight-comment">//East to West offset</span>
    <span class="highlight-keyword">double</span> northSouth = <span class="highlight-number">23.32</span>;   <span class="highlight-comment">//North to South offset</span>
    <span class="highlight-keyword">double</span> elevation = <span class="highlight-number">22.14</span>;    <span class="highlight-comment">//Elevation above ground level</span>

    <span class="highlight-comment">//create a new project position</span>
    ProjectPosition newPosition =
      document.Application.Create.NewProjectPosition(eastWest, northSouth, elevation, angle);

    <span class="highlight-keyword">if</span> (<span class="highlight-keyword">null</span> != newPosition)
    {
        <span class="highlight-comment">//set the value of the project position</span>
        currentLocation.SetProjectPosition(origin, newPosition);
    }

    <span class="highlight-keyword">return</span> currentLocation;
}</pre></div></span><span id="cbc_2" x-lang="VisualBasic" codelanguage="VisualBasic"><div class="highlight-title"><span class="highlight-copycode" onkeypress="javascript:CopyColorizedCodeCheckKey(this.parentNode, event);" tabindex="0" onmouseover="CopyCodeChangeIcon(this)" onmouseout="CopyCodeChangeIcon(this)" onclick="javascript:CopyColorizedCode(this.parentNode);"><img style="margin-right: 5px;" src="icons/CopyCode.gif" />Copy</span>VB.NET</div><div class="code"><pre xml:space="preserve"><span class="highlight-comment">'get and set the value of the projectlocation</span>
<span class="highlight-keyword">Public</span> <span class="highlight-keyword">Function</span> GetProjectLocation(document <span class="highlight-keyword">As</span> Autodesk.Revit.DB.Document) <span class="highlight-keyword">As</span> ProjectLocation
    <span class="highlight-keyword">Dim</span> currentLocation <span class="highlight-keyword">As</span> ProjectLocation = document.ActiveProjectLocation

    <span class="highlight-comment">'get the project position</span>
    <span class="highlight-keyword">Dim</span> origin <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> XYZ(<span class="highlight-number">0</span>, <span class="highlight-number">0</span>, <span class="highlight-number">0</span>)

    <span class="highlight-keyword">Const</span> angleRatio <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = Math.PI / <span class="highlight-number">180</span>
    <span class="highlight-comment">' angle conversion factor</span>
    <span class="highlight-keyword">Dim</span> projectPosition <span class="highlight-keyword">As</span> ProjectPosition = currentLocation.GetProjectPosition(origin)
    <span class="highlight-comment">'Angle from True North</span>
    <span class="highlight-keyword">Dim</span> angle <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">30.0</span> * angleRatio
    <span class="highlight-comment">' convert degrees to radian</span>
    <span class="highlight-keyword">Dim</span> eastWest <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">30.0</span>
    <span class="highlight-comment">'East to West offset</span>
    <span class="highlight-keyword">Dim</span> northSouth <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">23.32</span>
    <span class="highlight-comment">'North to South offset</span>
    <span class="highlight-keyword">Dim</span> elevation <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">22.14</span>
    <span class="highlight-comment">'Elevation above ground level</span>
    <span class="highlight-comment">'create a new project position</span>
    <span class="highlight-keyword">Dim</span> newPosition <span class="highlight-keyword">As</span> ProjectPosition = document.Application.Create.NewProjectPosition(eastWest, northSouth, elevation, angle)

    <span class="highlight-keyword">If</span> newPosition <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-comment">'set the value of the project position</span>
        currentLocation.SetProjectPosition(origin, newPosition)
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-keyword">Return</span> currentLocation
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span></pre></div></span></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ProjectLocation">ProjectLocation Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>