<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>RebarShapeDrivenAccessor Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="RebarShapeDrivenAccessor class" /><meta name="System.Keywords" content="RebarShapeDrivenAccessor class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB.Structure" /><meta name="file" content="f7f7f744-3ddd-1572-b36f-acf1e26b2ea9" /><meta name="guid" content="f7f7f744-3ddd-1572-b36f-acf1e26b2ea9" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor class" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDrivenAccessor class" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDrivenAccessor class, all members" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDrivenAccessor class" />
<meta name="Microsoft.Help.Keywords" content="RebarShapeDrivenAccessor class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor" /><MSHelp:TOCTitle Title="RebarShapeDrivenAccessor Members" /><MSHelp:RLTitle Title="RebarShapeDrivenAccessor Members (Autodesk.Revit.DB.Structure)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBStructureRebarShapeDrivenAccessorMembersTopic" /><MSHelp:Keyword Index="K" Term="RebarShapeDrivenAccessor class" /><MSHelp:Keyword Index="K" Term="RebarShapeDrivenAccessor class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">RebarShapeDrivenAccessor Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor">RebarShapeDrivenAccessor Class</a> <a href="#methodTableToggle" onclick="OpenSection(methodTableToggle)">Methods</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p /><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor">RebarShapeDrivenAccessor</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.ComputeDrivingCurves">ComputeDrivingCurves</a></td><td><div class="summary">
   Compute the driving curves.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.Dispose">Dispose</a></td><td><div class="summary">Releases all resources used by the <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor">RebarShapeDrivenAccessor</a></div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.GetBarPositionTransform(System.Int32)">GetBarPositionTransform</a></td><td><div class="summary">
   Return a transform representing the relative position of any
   individual bar in the set.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.GetDistributionPath">GetDistributionPath</a></td><td><div class="summary">
   The distribution path of a rebar set.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.ScaleToBox(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)">ScaleToBox</a></td><td><div class="summary">
   Move and resize the bar to fit within a specified box.
   The arguments are interpreted as an arbitrary
   rectangle in 3D with vertices: origin, origin+xVec,
   origin+xVec+yVec, origin+yVec. The algorithm then
   proceeds as follows. First the bar is given the
   default values of the shape parameters from the shape
   definition. Then, if it is possible to do so without
   violating the shape definition, the parameter values
   are scaled so that the width and height of the shape
   (including bar thickness) match the lengths of xVec and yVec.
   If there is no way to do this within the shape definition
   due to overconstraining, a compromise is attempted, such as
   scaling the whole shape until either the width or the
   height is correct. Finally the shape is rotated to
   match the coordinate system of the box. The algorithm
   is the same one used in one-click placement.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.ScaleToBoxFor3D(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Double)">ScaleToBoxFor3D</a></td><td><div class="summary">
   Move and resize a spiral or multiplanar instance to fit within a specified box.
   The arguments are interpreted as an arbitrary rectangle in 3D with
   vertices: origin, origin+xVec, origin+xVec+yVec, origin+yVec. One end of the
   rebar shape is inscribed in this rectangle following the procedure described
   for the ScaleToBox method. The other end is placed in the parallel plane at
   distance (center-to-center) given by the height argument, in the
   direction of (xVec x yVec).
   Note that spiral shapes interpret the input arguments using a different convention
   than multiplanar shapes.  For spiral shapes, the spiral start will be placed in
   the rectangle defined by origin, xVec, yVec, and the end of the spiral will be
   placed in the parallel plane.  For multiplanar shapes, the rebar is placed with
   its primary shape definition located in the parallel plane defined by the height
   argument, and its connector segments extending in the direction opposite (xVec x yVec).
   This method replaces ScaleToBoxForSpiral() from prior releases.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetLayoutAsFixedNumber(System.Int32,System.Double,System.Boolean,System.Boolean,System.Boolean)">SetLayoutAsFixedNumber</a></td><td><div class="summary">
   Sets the Layout Rule property of rebar set to FixedNumber.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetLayoutAsMaximumSpacing(System.Double,System.Double,System.Boolean,System.Boolean,System.Boolean)">SetLayoutAsMaximumSpacing</a></td><td><div class="summary">
   Sets the Layout Rule property of rebar set to MaximumSpacing
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetLayoutAsMinimumClearSpacing(System.Double,System.Double,System.Boolean,System.Boolean,System.Boolean)">SetLayoutAsMinimumClearSpacing</a></td><td><div class="summary">
   Sets the Layout Rule property of rebar set to MinimumClearSpacing
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetLayoutAsNumberWithSpacing(System.Int32,System.Double,System.Boolean,System.Boolean,System.Boolean)">SetLayoutAsNumberWithSpacing</a></td><td><div class="summary">
   Sets the Layout Rule property of rebar set to NumberWithSpacing
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetLayoutAsSingle">SetLayoutAsSingle</a></td><td><div class="summary">
   Sets the Layout Rule property of rebar set to Single.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.SetRebarShapeId(Autodesk.Revit.DB.ElementId)">SetRebarShapeId</a></td><td><div class="summary">
   Changes the RebarShape element that defines the shape of the rebar.
   Changing the value of this member causes the Rebar instance to choose values for its
   shape parameters to preserve its previous shape as closely as possible
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.ArrayLength">ArrayLength</a></td><td><div class="summary">
   Identifies the distribution path length of rebar set.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.BarsOnNormalSide">BarsOnNormalSide</a></td><td><div class="summary">
   Identifies if the bars of the rebar set are on the same side of the rebar plane indicated by the normal.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.BaseFinishingTurns">BaseFinishingTurns</a></td><td><div class="summary">
   For a spiral, the number of finishing turns at the lower end of the spiral.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.Height">Height</a></td><td><div class="summary">
   For a spiral, the overall height.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.IsValidObject">IsValidObject</a></td><td><div class="summary">
   Specifies whether the .NET object represents a valid Revit entity.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.MultiplanarDepth">MultiplanarDepth</a></td><td><div class="summary">
   For a multiplanar rebar, the depth of the instance.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.Normal">Normal</a></td><td><div class="summary">
   A unit-length vector normal to the plane of the rebar
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.Pitch">Pitch</a></td><td><div class="summary">
   For a spiral, the pitch, or vertical distance traveled in one rotation.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor.TopFinishingTurns">TopFinishingTurns</a></td><td><div class="summary">
   For a spiral, the number of finishing turns at the upper end of the spiral.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.Structure.RebarShapeDrivenAccessor">RebarShapeDrivenAccessor Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB.Structure">Autodesk.Revit.DB.Structure Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>