<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>BRepBuilder Members</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="BRepBuilder class" /><meta name="System.Keywords" content="BRepBuilder class, all members" /><meta name="System.Keywords" content="Autodesk.Revit.DB.BRepBuilder class" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.DB" /><meta name="file" content="fa227e06-2aa0-066e-03ac-08fed51023fb" /><meta name="guid" content="fa227e06-2aa0-066e-03ac-08fed51023fb" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="AllMembers.T:Autodesk.Revit.DB.BRepBuilder" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.DB.BRepBuilder" />
<meta name="Microsoft.Help.TocOrder" content="0" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BRepBuilder class" />
<meta name="Microsoft.Help.Keywords" content="BRepBuilder class" />
<meta name="Microsoft.Help.Keywords" content="BRepBuilder class, all members" />
<meta name="Microsoft.Help.Keywords" content="BRepBuilder class" />
<meta name="Microsoft.Help.Keywords" content="BRepBuilder class, all members" />
<meta name="Microsoft.Help.Keywords" content="Autodesk.Revit.DB.BRepBuilder class" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="AllMembers.T:Autodesk.Revit.DB.BRepBuilder" /><MSHelp:TOCTitle Title="BRepBuilder Members" /><MSHelp:RLTitle Title="BRepBuilder Members (Autodesk.Revit.DB)" /><MSHelp:Keyword Index="A" Term="AllMembers.T:Autodesk.Revit.DB.BRepBuilder" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitDBBRepBuilderMembersTopic" /><MSHelp:Keyword Index="K" Term="BRepBuilder class" /><MSHelp:Keyword Index="K" Term="BRepBuilder class, all members" /><MSHelp:Keyword Index="K" Term="Autodesk.Revit.DB.BRepBuilder class" /><MSHelp:Attr Name="HelpPriority" Value="1" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">BRepBuilder Members</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BRepBuilder">BRepBuilder Class</a> <a href="#constructorTableToggle" onclick="OpenSection(constructorTableToggle)">Constructors</a> <a href="#methodTableToggle" onclick="OpenSection(methodTableToggle)">Methods</a> <a href="#propertyTableToggle" onclick="OpenSection(propertyTableToggle)">Properties</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p /><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BRepBuilder">BRepBuilder</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(constructorTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(constructorTableToggle, event)" tabindex="0"><img id="constructorTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Constructors</span></h1><div id="constructorTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.#ctor(Autodesk.Revit.DB.BRepType)">BRepBuilder</a></td><td><div class="summary">
   Construct a BRepBuilder to use in constructing geometry.
</div></td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.AddCoEdge(Autodesk.Revit.DB.BRepBuilderGeometryId,Autodesk.Revit.DB.BRepBuilderGeometryId,System.Boolean)">AddCoEdge</a></td><td><div class="summary">
   Add a co-edge associated to a previously added edge. A co-edge represents the use of an edge on one
   of the edge's faces. BrepBuilder allows at most two faces per edge, hence at most two co-edges per edge,
   and the co-edges must have opposite bCoEdgeIsReversed flags. The co-edges in a loop must be added in the
   order in which they occur in loop (i.e., in their topological order).
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.AddEdge(Autodesk.Revit.DB.BRepBuilderEdgeGeometry)">AddEdge</a></td><td><div class="summary">
   Add a new edge to the geometry being built. The BRepBuilder uses edges only to store edge geometry and to track
   pairs of co-edges that share an edge.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.AddFace(Autodesk.Revit.DB.BRepBuilderSurfaceGeometry,System.Boolean)">AddFace</a></td><td><div class="summary">
   Creates an empty face in the geometry being built. Other BRepBuilder methods are used to add loops to the face.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.AddLoop(Autodesk.Revit.DB.BRepBuilderGeometryId)">AddLoop</a></td><td><div class="summary">
   Creates an empty loop in a given face of the geometry being built. Other BRepBuilder methods are used to add co-edges to the loop.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.AllowRemovalOfProblematicFaces">AllowRemovalOfProblematicFaces</a></td><td><div class="summary">
   Allow BRepBuilder to remove problematic faces (e.g., due to inaccurate edge geometry). If this option is enabled and
   BRepBuilder removes some faces, the output geometry's type will be OpenShell regardless of the expected type specified
   when the BRepBuilder was created.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.CanAddGeometry">CanAddGeometry</a></td><td><div class="summary">
   A validator function that checks the state of this BRepBuilder object. Returns true if this BRepBuilder object is accepting b-rep data, false otherwise.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.ShapeBuilder.Dispose">Dispose</a></td><td> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ShapeBuilder">ShapeBuilder</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.Finish">Finish</a></td><td><div class="summary">
   Complete construction of the geometry. The geometry will be validated and, if valid, stored in this Builder. Otherwise it will be deleted.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.FinishFace(Autodesk.Revit.DB.BRepBuilderGeometryId)">FinishFace</a></td><td><div class="summary">
   Indicates that the caller has finished defining the given face.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.FinishLoop(Autodesk.Revit.DB.BRepBuilderGeometryId)">FinishLoop</a></td><td><div class="summary">
   Indicates that the caller has finished defining the given loop.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.GetResult">GetResult</a></td><td><div class="summary">
   Get the Geometry object built by this BRepBuilder. This will clear the built Geometry stored in the BRepBuilder.
   This function will throw if this BRepBuilder hasn't completed building the b-rep. Use IsResultAvailable() to verify that this BRepBuilder contains a valid result.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;static;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /><img src="icons/static.gif" alt="Static member" title="Static member" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.IsPermittedSurfaceType(Autodesk.Revit.DB.Surface)">IsPermittedSurfaceType</a></td><td><div class="summary">
   A validator function that checks whether the surface object is of type supported as face surface by BRepBuilder.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.IsResultAvailable">IsResultAvailable</a></td><td><div class="summary">
   A validator function that checks the state of this BRepBuilder object. Returns true if this BRepBuilder object has successfully built a b-rep.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.IsValidEdgeId(Autodesk.Revit.DB.BRepBuilderGeometryId)">IsValidEdgeId</a></td><td><div class="summary">
   A validator function that checks whether the edge id corresponds to an edge previously added to this BRepBuilder object.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.IsValidFaceId(Autodesk.Revit.DB.BRepBuilderGeometryId)">IsValidFaceId</a></td><td><div class="summary">
   A validator function that checks whether the face id corresponds to a face previously added to this BRepBuilder object.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.IsValidLoopId(Autodesk.Revit.DB.BRepBuilderGeometryId)">IsValidLoopId</a></td><td><div class="summary">
   A validator function that checks whether the loop id corresponds to a loop previously added to this BRepBuilder object.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.RemovedSomeFaces">RemovedSomeFaces</a></td><td><div class="summary">
   Returns 'true' if BRepBuilder removed some problematic faces from the output geometry, 'false' if not.
   If allowRemovalOfProblematicFaces was not called to enable removal of problematic faces, this function
   will return 'false'. Note that if some faces were removed, the output geometry's type will be OpenShell
   regardless of the expected type that was specified when the BRepBuilder was created.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.SetAllowShortEdges">SetAllowShortEdges</a></td><td><div class="summary">
   Make BRepBuilder allow edges that it would normally disallow as being too short for Revit geometry.
</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.BRepBuilder.SetFaceMaterialId(Autodesk.Revit.DB.BRepBuilderGeometryId,Autodesk.Revit.DB.ElementId)">SetFaceMaterialId</a></td><td><div class="summary">
   Sets material id to a face.
</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(propertyTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(propertyTableToggle, event)" tabindex="0"><img id="propertyTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Properties</span></h1><div id="propertyTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubproperty.gif" alt="Public property" title="Public property" /></td><td><a href="ms-xhelp:///?Id=P:Autodesk.Revit.DB.ShapeBuilder.IsValidObject">IsValidObject</a></td><td><div class="summary">
   Specifies whether the .NET object represents a valid Revit entity.
</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.ShapeBuilder">ShapeBuilder</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.BRepBuilder">BRepBuilder Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.DB">Autodesk.Revit.DB Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>