<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:MSHelp="http://msdn.microsoft.com/mshelp" xmlns:mshelp="http://msdn.microsoft.com/mshelp" xmlns:ddue="http://ddue.schemas.microsoft.com/authoring/2003/5" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:msxsl="urn:schemas-microsoft-com:xslt"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="save" content="history" />
<title>Application Methods</title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Application class, methods" /><link rel="stylesheet" type="text/css" href="styles/Presentation.css" /><link rel="stylesheet" type="text/css" href="HxLink.css" /><script type="text/javascript" src="scripts/EventUtilities.js"> </script>
<script type="text/javascript" src="scripts/SplitScreen.js"> </script>
<script type="text/javascript" src="scripts/Dropdown.js"> </script>
<script type="text/javascript" src="scripts/script_manifold.js"> </script>
<script type="text/javascript" src="scripts/script_feedBack.js"> </script>
<script type="text/javascript" src="scripts/CheckboxMenu.js"> </script>
<script type="text/javascript" src="scripts/CommonUtilities.js"> </script>
<meta name="container" content="Autodesk.Revit.Creation" /><meta name="file" content="fe85870b-7217-0c70-ba09-028a8e3fb6b6" /><meta name="guid" content="fe85870b-7217-0c70-ba09-028a8e3fb6b6" />

<meta name="Microsoft.Help.Locale" content="en-us" />
<meta name="Microsoft.Help.TopicLocale" content="en-us" />
<meta name="Microsoft.Help.SelfBranded" content="true" />
<meta name="Microsoft.Help.Id" content="Methods.T:Autodesk.Revit.Creation.Application" />
<meta name="Microsoft.Help.TocParent" content="T:Autodesk.Revit.Creation.Application" />
<meta name="Microsoft.Help.TocOrder" content="1" />
<meta name="Microsoft.Help.Keywords" content="Application class, methods" />
<meta name="Microsoft.Help.Keywords" content="Application class, methods" />
<meta name="Microsoft.Help.Category" content="RevitAPI" />
<meta name="Microsoft.Help.DisplayVersion" content="" />
<meta name="Microsoft.Help.ContentType" content="Reference" />

<xml><MSHelp:Attr Name="AssetID" Value="Methods.T:Autodesk.Revit.Creation.Application" /><MSHelp:TOCTitle Title="Application Methods" /><MSHelp:RLTitle Title="Application Methods (Autodesk.Revit.Creation)" /><MSHelp:Keyword Index="A" Term="Methods.T:Autodesk.Revit.Creation.Application" /><MSHelp:Keyword Index="A" Term="frlrfAutodeskRevitCreationApplicationMethodsTopic" /><MSHelp:Keyword Index="K" Term="Application class, methods" /><MSHelp:Attr Name="DevLang" Value="CSharp" /><MSHelp:Attr Name="DevLang" Value="VB" /><MSHelp:Attr Name="Locale" Value="en-us" /><MSHelp:Attr Name="TopicType" Value="kbSyntax" /><MSHelp:Attr Name="TopicType" Value="apiref" /><MSHelp:Attr Name="AssemblyVersion" Value="18.0.0.0" /></xml><script type="text/javascript" src="h3m.js"></script>
</head><body><input type="hidden" id="userDataCache" class="userDataStyle" /><input type="hidden" id="hiddenScrollOffset" /><img id="collapseImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" alt="Collapse image" title="Collapse image" /><img id="expandImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" alt="Expand Image" title="Expand Image" /><img id="collapseAllImage" style="display:none; height:0; width:0;" src="icons/collapse_all.gif" /><img id="expandAllImage" style="display:none; height:0; width:0;" src="icons/expand_all.gif" /><img id="dropDownImage" style="display:none; height:0; width:0;" src="icons/dropdown.gif" /><img id="dropDownHoverImage" style="display:none; height:0; width:0;" src="icons/dropdownHover.gif" /><img id="copyImage" style="display:none; height:0; width:0;" src="icons/copycode.gif" alt="Copy image" title="Copy image" /><img id="copyHoverImage" style="display:none; height:0; width:0;" src="icons/copycodeHighlight.gif" alt="CopyHover image" title="CopyHover image" /><div id="header"><table id="topTable" cellspacing="0" cellpadding="0"><tr><td><span onclick="ExpandCollapseAll(toggleAllImage)" style="cursor:default;" onkeypress="ExpandCollapseAll_CheckKey(toggleAllImage, event)" tabindex="0"><img id="toggleAllImage" class="toggleAll" src="icons/collapse_all.gif" /> <label id="collapseAllLabel" for="toggleAllImage" style="display: none;">Collapse All</label><label id="expandAllLabel" for="toggleAllImage" style="display: none;">Expand All</label> </span><span>    </span><span id="devlangsDropdown" class="filter" tabindex="0"><img id="devlangsDropdownImage" src="icons/dropdown.gif" /> <label id="devlangsMenuAllLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: All </nobr></label><label id="devlangsMenuMultipleLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Multiple </nobr></label><label id="devlangsMenuCSharpLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: C# </nobr></label><label id="devlangsMenuVisualBasicLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual Basic </nobr></label><label id="devlangsMenuManagedCPlusPlusLabel" for="devlangsDropdownImage" style="display: none;"><nobr>Code: Visual C++ </nobr></label></span><span>    </span><span id="memberOptionsDropdown" class="filter" tabindex="0"><img id="memberOptionsDropdownImage" src="icons/dropdown.gif" /> <label id="memberOptionsMenuAllLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Show All </nobr></label><label id="memberOptionsMenuMultipleLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuProtectedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label><label id="memberOptionsMenuInheritedLabel" for="memberOptionsDropdownImage" style="display: none;"><nobr>Members: Filtered </nobr></label></span></td></tr></table><div id="devlangsMenu"><input id="CSharpCheckbox" type="checkbox" data="CSharp,cs,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="CSharpCheckbox">C#</label><br /><input id="VisualBasicCheckbox" type="checkbox" data="VisualBasic,vb,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="VisualBasicCheckbox">Visual Basic</label><br /><input id="ManagedCPlusPlusCheckbox" type="checkbox" data="ManagedCPlusPlus,cpp,'persist'" value="on" onclick="SetLanguage(this)" /><label class="checkboxLabel" for="ManagedCPlusPlusCheckbox">Visual C++</label><br /></div><div id="memberOptionsMenu"><input id="ProtectedCheckbox" type="checkbox" data="Protected" value="on" onclick="SetMemberOptions(this, 'vis')" /><label class="checkboxLabel" for="ProtectedCheckbox">Include Protected Members</label><br /><input id="InheritedCheckbox" type="checkbox" data="Inherited" value="on" onclick="SetMemberOptions(this, 'decl')" /><label class="checkboxLabel" for="InheritedCheckbox">Include Inherited Members</label><br /></div><table id="bottomTable" cellpadding="0" cellspacing="0"><tr id="headerTableRow1"><td align="left"><span id="runningHeaderText">Revit 2018 API</span></td></tr><tr id="headerTableRow2"><td align="left"><span id="nsrTitle">Application Methods</span></td></tr><tr id="headerTableRow3"><td align="left"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Application">Application Class</a> <a href="#seeAlsoToggle" onclick="OpenSection(seeAlsoToggle)">See Also</a> <span id="headfeedbackarea" class="feedbackhead"><a href="javascript:SubmitFeedback('revitapifeedback@autodesk.com','Revit 2018 API','','','','%0\dYour%20feedback%20is%20used%20to%20improve%20the%20documentation%20and%20the%20product.%20Your%20e-mail%20address%20will%20not%20be%20used%20for%20any%20other%20purpose%20and%20is%20disposed%20of%20after%20the%20issue%20you%20report%20is%20resolved.%20%20While%20working%20to%20resolve%20the%20issue%20that%20you%20report,%20you%20may%20be%20contacted%20via%20e-mail%20to%20get%20further%20details%20or%20clarification%20on%20the%20feedback%20you%20sent.%20After%20the%20issue%20you%20report%20has%20been%20addressed,%20you%20may%20receive%20an%20e-mail%20to%20let%20you%20know%20that%20your%20feedback%20has%20been%20addressed.%0\A%0\d','Customer%20Feedback');">Send Feedback</a></span></td></tr></table><table id="gradientTable"><tr><td class="nsrBottom" background="../icons/gradient.gif" /></tr></table></div><div id="mainSection"><div id="mainBody"><div id="allHistory" class="saveHistory" onsave="saveAll()" onload="loadAll()" /><span style="color: DarkGray"></span><p>The <a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Application">Application</a> type exposes the following members.</p><h1 class="heading"><span onclick="ExpandCollapse(methodTableToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(methodTableToggle, event)" tabindex="0"><img id="methodTableToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />Methods</span></h1><div id="methodTableSection" class="section" name="collapseableSection" style=""><table id="memberList" class="members" frame="lhs" cellpadding="2"><col width="10%" /><tr><th class="iconColumn">
               
            </th><th class="nameColumn">Name</th><th class="descriptionColumn">Description</th></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.DB.APIObject.Dispose">Dispose</a></td><td><div class="summary">Causes the object to release immediately any resources it may be utilizing.</div> (Inherited from <a href="ms-xhelp:///?Id=T:Autodesk.Revit.DB.APIObject">APIObject</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/bsc2ak47" target="_blank">Equals</a></td><td><div class="summary">Determines whether the specified <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a> is equal to the current <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/zdee4b3y" target="_blank">GetHashCode</a></td><td><div class="summary">Serves as a hash function for a particular type. </div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/dfwy45w9" target="_blank">GetType</a></td><td><div class="summary">Gets the <a href="http://msdn2.microsoft.com/en-us/library/42892f65" target="_blank">Type</a> of the current instance.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewAreaCreationData(Autodesk.Revit.DB.ViewPlan,Autodesk.Revit.DB.UV)">NewAreaCreationData</a></td><td><div class="summary">Creates an object which wraps the arguments of Area for batch creation.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewBoundingBoxUV">NewBoundingBoxUV<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Creates an empty two-dimensional rectangle.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewBoundingBoxUV(System.Double,System.Double,System.Double,System.Double)">NewBoundingBoxUV(Double, Double, Double, Double)</a></td><td><div class="summary">Creates a two-dimensional rectangle with supplied values.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewBoundingBoxXYZ">NewBoundingBoxXYZ</a></td><td><div class="summary">Creates a three-dimensional rectangular box.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewBuildingSiteExportOptions">NewBuildingSiteExportOptions</a></td><td><div class="summary">Creates Building Site Export options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewCategorySet">NewCategorySet</a></td><td><div class="summary">Creates a new instance of a set specifically for holding category objects.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewColor">NewColor</a></td><td><div class="summary">Returns a new color object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewCombinableElementArray">NewCombinableElementArray</a></td><td><div class="summary">Returns an array that can hold combinable element objects.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewCurveArrArray">NewCurveArrArray</a></td><td><div class="summary">Creates an empty array that can store geometric curve loops.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewCurveArray">NewCurveArray</a></td><td><div class="summary">Creates an empty array that can store geometric curves.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewCurveLoopsProfile(Autodesk.Revit.DB.CurveArrArray)">NewCurveLoopsProfile</a></td><td><div class="summary">Creates a new CurveLoopsProfile object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewDoubleArray">NewDoubleArray</a></td><td><div class="summary">Creates a new instance of a double array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewDWFExportOptions">NewDWFExportOptions</a></td><td><div class="summary">Creates DWF Export options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewDWFXExportOptions">NewDWFXExportOptions</a></td><td><div class="summary">Creates DWFX Export options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewElementId">NewElementId</a></td><td><div class="summary">Creates a new Autodesk::Revit::DB::ElementId^ object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewElementSet">NewElementSet</a></td><td><div class="summary">Creates a new instance of a set specifically for holding elements.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFaceArray">NewFaceArray</a></td><td><div class="summary">Creates a new instance of a face array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.FamilySymbol,System.Collections.Generic.IList{Autodesk.Revit.DB.XYZ})">NewFamilyInstanceCreationData(FamilySymbol, IList<span class="languageSpecificText"><span class="cs">&lt;</span><span class="vb">(Of </span><span class="cpp">&lt;</span><span class="fs">&lt;'</span><span class="nu">(</span></span>XYZ<span class="languageSpecificText"><span class="cs">&gt;</span><span class="vb">)</span><span class="cpp">&gt;</span><span class="fs">&gt;</span><span class="nu">)</span></span>)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.Face,Autodesk.Revit.DB.Line,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstanceCreationData(Face, Line, FamilySymbol)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(XYZ, FamilySymbol, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.Curve,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(Curve, FamilySymbol, Level, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.Face,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol)">NewFamilyInstanceCreationData(Face, XYZ, XYZ, FamilySymbol)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(XYZ, FamilySymbol, Element, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(XYZ, FamilySymbol, Level, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Level,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(XYZ, FamilySymbol, Element, Level, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilyInstanceCreationData(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.FamilySymbol,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Structure.StructuralType)">NewFamilyInstanceCreationData(XYZ, FamilySymbol, XYZ, Element, StructuralType)</a></td><td><div class="summary">Creates an object which wraps the arguments of NewFamilyInstance() for batch creation. </div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFamilySymbolProfile(Autodesk.Revit.DB.FamilySymbol)">NewFamilySymbolProfile</a></td><td><div class="summary">Creates a new FamilySymbolProfile object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewFBXExportOptions">NewFBXExportOptions</a></td><td><div class="summary">Creates 3D-Studio Max (FBX) Export options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewGBXMLImportOptions">NewGBXMLImportOptions</a></td><td><div class="summary">Creates Green-Building XML Import options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewGeometryOptions">NewGeometryOptions</a></td><td><div class="summary">Creates an object to specify user preferences in parsing of geometry.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewImageImportOptions">NewImageImportOptions</a></td><td><div class="summary">Creates Image Import options.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewInstanceBinding">NewInstanceBinding<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Creates a new empty instance binding object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewInstanceBinding(Autodesk.Revit.DB.CategorySet)">NewInstanceBinding(CategorySet)</a></td><td><div class="summary">Creates a new instance binding object containing the categories passed as a parameter.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewIntersectionResultArray">NewIntersectionResultArray</a></td><td><div class="summary">Creates a new instance of an IntersectionResult array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointOnEdge(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.PointLocationOnCurve)">NewPointOnEdge</a></td><td><div class="summary">Create a PointOnEdge object which is used to define the placement of a ReferencePoint.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointOnEdgeEdgeIntersection(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Reference)">NewPointOnEdgeEdgeIntersection</a></td><td><div class="summary">Construct a PointOnEdgeEdgeIntersection object which is used to define the placement of a ReferencePoint given two references to edge.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointOnEdgeFaceIntersection(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Reference,System.Boolean)">NewPointOnEdgeFaceIntersection</a></td><td><div class="summary">Construct a PointOnEdgeFaceIntersection object which is used to define the placement of a ReferencePoint given a references to edge and a reference to face.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointOnFace(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.UV)">NewPointOnFace</a></td><td><div class="summary">Construct a PointOnFace object which is used to define the placement of a ReferencePoint given a reference and a location on the face.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointOnPlane(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.UV,Autodesk.Revit.DB.UV,System.Double)">NewPointOnPlane</a></td><td><div class="summary">Construct a PointOnPlane object which is used to define the placement of a ReferencePoint from its property values.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewPointRelativeToPoint(Autodesk.Revit.DB.Reference)">NewPointRelativeToPoint</a></td><td><div class="summary">Create a PointRelativeToPoint object, which is used to define 
the placement of a ReferencePoint relative to a host point.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewProjectPosition(System.Double,System.Double,System.Double,System.Double)">NewProjectPosition</a></td><td><div class="summary">Creates a new project position object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewReferenceArray">NewReferenceArray</a></td><td><div class="summary">Creates a new instance of a reference array.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewReferencePointArray">NewReferencePointArray</a></td><td><div class="summary">Creates an empty array that can store ReferencePoint objects.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewSpaceSet">NewSpaceSet</a></td><td><div class="summary">Creates a new instance of a space set.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewTypeBinding">NewTypeBinding<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Creates a new empty type binding object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewTypeBinding(Autodesk.Revit.DB.CategorySet)">NewTypeBinding(CategorySet)</a></td><td><div class="summary">Creates a new type binding object containing the categories passed as a parameter.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewUV">NewUV<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Creates a UV object at the origin.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewUV(Autodesk.Revit.DB.UV)">NewUV(UV)</a></td><td><div class="summary">Creates a UV object by copying the supplied UV object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewUV(System.Double,System.Double)">NewUV(Double, Double)</a></td><td><div class="summary">Creates a UV object representing coordinates in 2-space with supplied values.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewVertexIndexPair(System.Int32,System.Int32)">NewVertexIndexPair</a></td><td><div class="summary">Creates a new VertexIndexPair object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewVertexIndexPairArray">NewVertexIndexPairArray</a></td><td><div class="summary">Returns an array that can hold VertexIndexPair objects.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewViewSet">NewViewSet</a></td><td><div class="summary">Creates a new instance of a View set.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewXYZ">NewXYZ<span class="languageSpecificText"><span class="cs">()</span><span class="cpp">()</span><span class="nu">()</span><span class="fs">()</span></span></a></td><td><div class="summary">Creates a XYZ object at the origin.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewXYZ(Autodesk.Revit.DB.XYZ)">NewXYZ(XYZ)</a></td><td><div class="summary">Creates a XYZ object by copying the supplied XYZ object.</div></td></tr><tr data="public;declared;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="ms-xhelp:///?Id=M:Autodesk.Revit.Creation.Application.NewXYZ(System.Double,System.Double,System.Double)">NewXYZ(Double, Double, Double)</a></td><td><div class="summary">Creates a XYZ object representing coordinates in 3-space with supplied values.</div></td></tr><tr data="public;inherited;notNetfw;"><td><img src="icons/pubmethod.gif" alt="Public method" title="Public method" /></td><td><a href="http://msdn2.microsoft.com/en-us/library/7bxwbwt2" target="_blank">ToString</a></td><td><div class="summary">Returns a string that represents the current object.</div> (Inherited from <a href="http://msdn2.microsoft.com/en-us/library/e5kfa45b" target="_blank">Object</a>.)</td></tr></table></div><h1 class="heading"><span onclick="ExpandCollapse(seeAlsoToggle)" style="cursor:default;" onkeypress="ExpandCollapse_CheckKey(seeAlsoToggle, event)" tabindex="0"><img id="seeAlsoToggle" class="toggle" name="toggleSwitch" src="icons/collapse_all.gif" />See Also</span></h1><div id="seeAlsoSection" class="section" name="collapseableSection" style=""><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=T:Autodesk.Revit.Creation.Application">Application Class</a></div><div class="seeAlsoStyle"><a href="ms-xhelp:///?Id=N:Autodesk.Revit.Creation">Autodesk.Revit.Creation Namespace</a></div></div></div><div id="footer"><div class="footerLine"><img width="100%" height="3px" src="icons/footer.gif" alt="Footer image" title="Footer image" /></div><a name="feedback"></a><span id="fb" class="feedbackcss"></span><p />Send comments on this topic to
        <a id="HT_MailLink" href="mailto:revitapifeedback%40autodesk.com?Subject=Revit 2018 API">Autodesk</a><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title;
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script>
</div></div><script type="text/javascript">
<!--
h3m_fix();
-->
</script>

</body></html>